(() => {
'use strict';
const $ = id => document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
const keys=['q','w','e','a','s','d','z','x','c'];
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const rounds=[
 {quota:12,time:35,life:1.8,interval:1.12,friends:0,baskets:6},
 {quota:15,time:38,life:1.7,interval:1.06,friends:.10,baskets:6},
 {quota:18,time:42,life:1.55,interval:1,friends:.14,baskets:6},
 {quota:22,time:45,life:1.35,interval:.9,friends:.18,baskets:6},
 {quota:30,time:42,life:.9,interval:.65,friends:.27,baskets:3}
];
const names=['First light','Busy branches','The afternoon rush','Golden hour','Master harvest'];
const positions=Array.from({length:9},(_,i)=>({x:180+(i%3)*270,y:250+Math.floor(i/3)*160}));
let rng=Number(new URLSearchParams(location.search).get('seed'))||92731;
const random=()=>{rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296;};
let level=1,score=0,hits=0,baskets=6,time=35,elapsed=0,spawnIn=.8,actors=Array(9).fill(null),effects=[],streak=0,phase='instructions',resumePhase='playing',sound=true,audio=null,last=0,bannerTime=0,dirty=true,hitLock=0;
let seen=false;try{seen=sessionStorage.getItem('orchard-watch-intro')==='1';}catch(_){}
const buttons=positions.map((p,i)=>{const b=document.createElement('button');b.className='hole';b.style.left=`${(p.x/900-.11)*100}%`;b.style.top=`${(p.y/650-.20)*100}%`;b.setAttribute('aria-label',`Burrow ${i+1}, key ${keys[i].toUpperCase()}`);b.innerHTML=`<span>${keys[i].toUpperCase()}</span>`;$('holes').appendChild(b);b.addEventListener('pointerdown',e=>{e.preventDefault();b.focus({preventScroll:true});thump(i);});b.addEventListener('click',e=>{if(e.detail===0)thump(i);});return b;});
function tone(freq,duration=.07){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+duration);g.gain.setValueAtTime(.075,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch(_){}}
function announce(text){$('banner').textContent=text;bannerTime=2.2;dirty=true;}
function refresh(){const r=rounds[level-1];$('round').textContent=`${level} / 5`;$('quota').textContent=`${hits} / ${r.quota}`;$('lives').textContent=`${baskets} left`;$('time').textContent=`${Math.ceil(time)}s`;$('score').textContent=score.toLocaleString();$('lives').classList.toggle('urgent',baskets<=2);$('time').classList.toggle('urgent',time<=10);}
function startRound(n){level=n;const r=rounds[n-1];hits=0;baskets=r.baskets;time=r.time;elapsed=0;spawnIn=.9;actors.fill(null);effects=[];streak=0;hitLock=0;phase='playing';$('result-modal').classList.remove('is-visible');document.body.classList.remove('gameover-open');announce(`${names[n-1]} · ${r.quota} marmots to chase`);refresh();dirty=true;}
function reset(){score=0;$('pause').textContent='Pause';startRound(1);if($('instruction-modal').classList.contains('is-visible')){resumePhase='playing';phase='instructions';}else buttons[4].focus({preventScroll:true});}
function showHelp(){if(phase==='result')return;resumePhase=phase==='instructions'?resumePhase:phase;phase='instructions';$('instruction-modal').classList.add('is-visible');document.body.classList.add('instructions-open');$('instruction-close').textContent='BACK TO THE ORCHARD';$('instruction-close').focus();dirty=true;}
function dismiss(){try{sessionStorage.setItem('orchard-watch-intro','1');}catch(_){}$('instruction-modal').classList.remove('is-visible');document.body.classList.remove('instructions-open');phase=resumePhase;last=performance.now();buttons[4].focus({preventScroll:true});dirty=true;}
function finish(won){phase='result';document.body.classList.add('gameover-open');$('result-modal').classList.add('is-visible');const next=won&&level<5;$('result-title').textContent=next?'Harvest secured!':won?'Master of the orchard!':'The orchard needs you';$('result-text').textContent=won?`${hits} marmots chased. ${baskets} baskets saved. Score ${score.toLocaleString()}. ${next?'Fresh baskets await in the next round.':'Five harvests protected. Beautiful work.'}`:`Round ${level}: ${hits} of ${rounds[level-1].quota} marmots chased. ${baskets<=0?'Your baskets are empty.':'The harvest bell rang.'} Score ${score.toLocaleString()}. Watch for striped faces and leave the hats alone.`;$('continue').hidden=!next;$('restart').textContent='PLAY AGAIN · ROUND 1';(next?$('continue'):$('restart')).focus();dirty=true;}
function damage(i,text){baskets--;streak=0;effects.push({i,text,life:.85,bad:true});tone(130,.13);announce(`${text} · ${baskets} baskets left`);if(baskets<=0)finish(false);}
function thump(i){if(phase!=='playing'||hitLock>0)return;hitLock=.09;const a=actors[i];if(!a){hitLock=.24;streak=0;effects.push({i,text:'Empty!',life:.5});tone(180,.04);}else{actors[i]=null;if(a.friend)damage(i,'Careful! Gardener');else{hits++;streak++;const points=100+Math.min(5,Math.floor(streak/4))*25;score+=points;if(streak%4===0)announce(`${streak} clean thumps � ${points} points each`);effects.push({i,text:`+${points}`,life:.65,hit:true});tone(400+Math.min(streak,12)*28);if(hits>=rounds[level-1].quota){score+=baskets*100+Math.ceil(time)*10;finish(true);}}}effects=effects.slice(-16);refresh();dirty=true;}
function spawn(){const empty=[];actors.forEach((a,i)=>{if(!a)empty.push(i);});if(!empty.length)return;const i=empty[Math.floor(random()*empty.length)];const friend=random()<rounds[level-1].friends;actors[i]={age:0,life:rounds[level-1].life,friend};}
function step(dt){if(phase!=='playing')return;elapsed+=dt;time=Math.max(0,time-dt);hitLock=Math.max(0,hitLock-dt);spawnIn-=dt;bannerTime-=dt;if(bannerTime<=0)$('banner').textContent='';for(let i=0;i<9;i++){const a=actors[i];if(a){a.age+=dt;if(a.age>=a.life){actors[i]=null;if(!a.friend)damage(i,'One apple lost');if(phase==='result')break;}}}if(phase!=='playing'){refresh();return;}if(time<=0){finish(false);refresh();return;}if(spawnIn<=0){spawn();spawnIn+=rounds[level-1].interval*(.93+random()*.14);}effects.forEach(e=>e.life-=dt);effects=effects.filter(e=>e.life>0);refresh();dirty=true;}
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function line(points,color,width=3){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}
function text(s,x,y,size,color='#fff2cf'){ctx.fillStyle=color;ctx.font=`bold ${size}px Georgia`;ctx.textAlign='center';ctx.fillText(s,x,y);}
const backdrop=document.createElement('canvas');backdrop.width=900;backdrop.height=650;
function drawScene(){ctx.fillStyle='#aac2ae';ctx.fillRect(0,0,900,650);ellipse(710,68,43,43,'#f6d182');ellipse(270,224,430,150,'#6f9470');ellipse(790,235,470,146,'#52765c');ctx.fillStyle='#486043';ctx.fillRect(0,182,900,468);for(let i=0;i<12;i++){const x=i*87-24;ctx.fillStyle='#856645';ctx.fillRect(x,80,10,128);ellipse(x+6,67,63,50,i%2?'#be703e':'#dc9b49');ellipse(x-13,87,38,31,'#cc833e');for(let j=0;j<5;j++)ellipse(x-34+j*18,64+(j%2)*27,7,8,'#b8442a');}line([[0,182],[900,182]],'#ead7a1',9);line([[0,208],[900,208]],'#ccb580',7);for(let i=0;i<12;i++){ctx.fillStyle='#efdda8';ctx.fillRect(i*85+24,160,8,65);}for(let row=0;row<3;row++){ellipse(450,260+row*160,470,62,row%2?'#ac864f':'#bc9259');line([[0,315+row*160],[900,315+row*160]],'#314f3b',8);}positions.forEach((p,i)=>{ellipse(p.x,p.y+21,105,28,'#846141');ellipse(p.x,p.y+11,95,25,'#3c3024');ellipse(p.x,p.y+7,81,17,'#231f1b');for(let j=0;j<4;j++){const x=p.x-92+j*61;line([[x,p.y+31],[x-5,p.y+20],[x+7,p.y+26]],'#6c7846',3);}});for(let i=0;i<42;i++){const x=(i*173+53)%900,y=235+(i*97)%398;ellipse(x,y,4,2,'#d5aa68');}text('EST. 1982',65,36,12,'#385643');text('APPLE HILL',450,83,39,'#233e35');text('HARVEST CO-OPERATIVE',450,110,12,'#233e35');}
drawScene();
// A cached orchard sign adds depth without work in the animation loop.
line([[322,17],[328,50]],'#3b4e36',4);line([[579,17],[573,50]],'#3b4e36',4);
ctx.fillStyle='#423a2840';ctx.fillRect(301,46,304,82);
ctx.fillStyle='#efd9a2';ctx.fillRect(298,40,304,82);
ctx.strokeStyle='#916a3d';ctx.lineWidth=3;ctx.strokeRect(303,45,294,72);
text('APPLE HILL',450,79,31,'#304c37');text('HARVEST CO-OPERATIVE',450,102,11,'#655331');
ellipse(311,53,3,3,'#927341');ellipse(589,53,3,3,'#927341');
backdrop.getContext('2d').drawImage(canvas,0,0);
function drawActor(a,p){const rise=Math.min(1,a.age/.13,(a.life-a.age)/.16);const y=p.y+65*(1-Math.max(0,rise));ctx.save();ctx.beginPath();ctx.rect(p.x-101,p.y-123,202,139);ctx.clip();if(a.friend){ellipse(p.x,y-23,48,60,'#456851');ellipse(p.x,y-61,36,36,'#e9b47d');ellipse(p.x,y-88,60,13,'#f3d799');ctx.fillStyle='#d8b16a';ctx.fillRect(p.x-35,y-119,70,30);line([[p.x-35,y-96],[p.x+35,y-96]],'#9f512e',8);ellipse(p.x-12,y-64,3.5,4,'#352e27');ellipse(p.x+12,y-64,3.5,4,'#352e27');line([[p.x-8,y-49],[p.x,y-44],[p.x+9,y-49]],'#7b5135',3);line([[p.x+39,y-4],[p.x+56,y-57]],'#dae0a0',3);for(let k=0;k<5;k++){const t=k*Math.PI*2/5;ellipse(p.x+56+Math.cos(t)*10,y-58+Math.sin(t)*10,7,7,'#fff2cf');}ellipse(p.x+56,y-58,5,5,'#e5ac3c');}else{ellipse(p.x,y-29,51,65,'#8e5237');ellipse(p.x-35,y-90,17,21,'#74452f');ellipse(p.x+35,y-90,17,21,'#74452f');ellipse(p.x-35,y-90,9,12,'#c89665');ellipse(p.x+35,y-90,9,12,'#c89665');ellipse(p.x,y-64,46,39,'#b97949');ctx.fillStyle='#eed5a2';ctx.beginPath();ctx.moveTo(p.x-9,y-101);ctx.lineTo(p.x+9,y-101);ctx.lineTo(p.x+6,y-46);ctx.lineTo(p.x-6,y-46);ctx.fill();ellipse(p.x-21,y-69,6,7,'#2b2820');ellipse(p.x+21,y-69,6,7,'#2b2820');ellipse(p.x-23,y-72,2,2,'#fff');ellipse(p.x+19,y-72,2,2,'#fff');ellipse(p.x,y-45,24,16,'#e3ba83');ellipse(p.x,y-50,9,6,'#382c24');ctx.fillStyle='#fff0ca';ctx.fillRect(p.x-7,y-36,6,9);ctx.fillRect(p.x+1,y-36,6,9);ellipse(p.x-24,y-7,15,11,'#c48b5a');ellipse(p.x+26,y-7,15,11,'#c48b5a');ellipse(p.x+14,y-15,14,16,'#bd482c');line([[p.x+14,y-29],[p.x+17,y-37]],'#504431',3);ellipse(p.x+23,y-32,9,4,'#768a43');}ctx.restore();const left=Math.max(0,1-a.age/a.life);ctx.fillStyle='#362f22';ctx.fillRect(p.x-38,p.y+36,76,5);ctx.fillStyle=a.friend?'#f7e9c6':left<.3?'#ffe19b':'#d7c987';ctx.fillRect(p.x-38,p.y+36,76*left,5);}
function draw(){ctx.drawImage(backdrop,0,0);actors.forEach((a,i)=>{if(a)drawActor(a,positions[i]);});effects.forEach(e=>{const p=positions[e.i];ctx.globalAlpha=Math.min(1,e.life*3);ellipse(p.x,p.y-48,62,44,e.bad?'#93462ec9':'#fbe6aca6');text(e.text,p.x,p.y-49-(reducedMotion?0:(1-e.life)*22),e.bad?19:25,e.bad?'#fff2cf':'#274939');if(e.hit&&!reducedMotion){ctx.strokeStyle='#fff3c9';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p.x,p.y-48,35+(1-e.life)*38,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;});if(phase==='paused'){ctx.fillStyle='#183b2dd9';ctx.fillRect(0,0,900,650);text('A moment in the shade',450,302,34);text('Tap Resume to return to the harvest',450,340,19);}dirty=false;}
function frame(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;step(dt);if(dirty)draw();requestAnimationFrame(frame);}
function togglePause(){if(phase==='playing'){phase='paused';$('pause').textContent='Resume';}else if(phase==='paused'){phase='playing';$('pause').textContent='Pause';}dirty=true;}
function toggleSound(){sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(!sound));}
$('instruction-close').onclick=dismiss;$('help-button').onclick=showHelp;$('sound').onclick=toggleSound;$('pause').onclick=togglePause;$('reset').onclick=reset;$('restart').onclick=reset;$('continue').onclick=()=>startRound(level+1);
window.addEventListener('vibecade:restart',e=>{e.preventDefault();reset();});
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(keys.includes(key)){if(e.target.closest('.modal.is-visible'))return;e.preventDefault();if(!e.repeat)thump(keys.indexOf(key));}else if(key==='r'&&!e.repeat){e.preventDefault();reset();}else if(key==='m'&&!e.repeat)toggleSound();else if(key==='?'&&!e.repeat)showHelp();else if(key==='escape'&&!e.repeat)togglePause();});
window.addEventListener('blur',()=>{if(phase==='playing')togglePause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='playing')togglePause();});
startRound(1);if(!seen){phase='instructions';$('instruction-close').focus();}else{document.body.classList.remove('instructions-open');$('instruction-modal').classList.remove('is-visible');}
if(new URLSearchParams(location.search).has('test'))window.orchardTest={state:()=>({level,score,hits,baskets,time,elapsed,phase,actors:actors.map(a=>a&&({...a})),rounds}),jump:n=>{startRound(n);},step,thump,setActor:(i,friend=false,age=0)=>{actors[i]={friend,age,life:rounds[level-1].life};dirty=true;},setTime:t=>time=t,draw,clear:()=>actors.fill(null)};
requestAnimationFrame(frame);
})();
