(() => {
  'use strict';
  const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
  const COLS=6, ROWS=12, CELL=60, OX=30, OY=40;
  const symbols=['✳','◆','●','✚','☾','✿'], colors=['#d6e8fb','#eaa36e','#68b7bf','#b2a2d8','#d2c87c','#d08caa'], inks=['#1c4e8a','#62351d','#154b55','#392b61','#544e20','#612846'];
  // Continuous acceleration from matched tiles, without stage boundaries.
  const fallInterval=()=>Math.max(.16,1.05/(1+fired/90));
  const glazeCount=()=>fired<45?4:fired<120?5:6;
  let board, piece, next, fired=0, score=0, clears=3, phase='instructions', elapsed=0, fallClock=0, chain=0, matches=[], flash=0, toast=0, seed=1798, muted=false, audio, held='', repeat=0, last=0;
  const test=new URLSearchParams(location.search).has('test');
  function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
  function batch(){return Array.from({length:3},()=>Math.floor(random()*glazeCount()));}
  function speak(text){$('callout').textContent=text;$('callout').classList.add('show');toast=1.5;}
  function tone(freq=440){if(muted||phase==='instructions'||phase==='paused')return;try{audio ||=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.13);o.start();o.stop(audio.currentTime+.14);}catch{}}
  function clearInput(){held='';repeat=0;document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));}
  function hud(){
    $('speed').textContent=`${(1.05/fallInterval()).toFixed(2)}×`;
    $('progress').textContent=fired.toLocaleString();$('score').textContent=score.toLocaleString();
    $('rescues').textContent=`${clears} left`;$('touch-rescues').textContent=clears;
    document.querySelector('[data-action=rescue]').disabled=clears===0;
    const high=board.slice(0,5).some(row=>row.some(v=>v!==null));
    canvas.classList.toggle('crowded',high);
    $('status').textContent=high?(clears?'KILN CROWDING · X / CLEAR makes breathing room.':'KILN CROWDING · Match low and leave the center open.'):'Match three · Set up a cascade · Keep the center open.';
    $('preview').replaceChildren(...next.map(n=>{const e=document.createElement('span');e.textContent=symbols[n];e.style.background=colors[n];e.style.color=inks[n];e.setAttribute('aria-label',['star','diamond','circle','cross','crescent','flower'][n]);return e;}));
  }
  function fits(x,y){return x>=0&&x<COLS&&y+2<ROWS&&[0,1,2].every(i=>y+i<0||board[y+i][x]===null);}
  function spawn(){piece={x:2,y:0,tiles:next};next=batch();fallClock=0;chain=0;if(!fits(2,0))finish();hud();}
  function start(){clearInput();seed=1798;fired=0;score=0;clears=3;board=Array.from({length:ROWS},()=>Array(COLS).fill(null));next=batch();elapsed=0;matches=[];flash=0;toast=0;phase='play';instructions.saved='play';$('result').classList.remove('is-visible');$('callout').classList.remove('show');$('pause').textContent='Pause';spawn();draw();}
  function finish(){clearInput();phase='result';$('result-title').textContent='The kiln is full';$('result-text').textContent=`${fired} tiles fired · ${score.toLocaleString()} points · ${(1.05/fallInterval()).toFixed(2)}× speed. Keep columns low, cycle the order, and save an emergency clear for a crowded kiln.`;$('result').classList.add('is-visible');$('again').focus();}
  function findMatches(b=board){const found=new Set();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const v=b[y][x];if(v===null)continue;for(const [dx,dy] of [[1,0],[0,1],[1,1],[-1,1]]){let run=[];for(let n=0;n<12;n++){const xx=x+dx*n,yy=y+dy*n;if(xx<0||xx>=COLS||yy>=ROWS||b[yy][xx]!==v)break;run.push(yy*COLS+xx);}if(run.length>=3)run.forEach(i=>found.add(i));}}return [...found];}
  function settle(){for(let x=0;x<COLS;x++){const stack=board.map(r=>r[x]).filter(v=>v!==null);for(let y=ROWS-1;y>=0;y--)board[y][x]=stack.length?stack.pop():null;}}
  function resolve(){matches=findMatches();if(matches.length){chain++;flash=.3;phase='clearing';speak(chain>1?`CASCADE ×${chain}`:`${matches.length} TILES FIRED`);tone(420+chain*130);}else spawn();}
  function lock(){if(piece.y<0){finish();return;}piece.tiles.forEach((v,i)=>board[piece.y+i][piece.x]=v);piece=null;resolve();}
  function action(name){if(phase!=='play')return;if(name==='left'||name==='right'){const x=piece.x+(name==='left'?-1:1);if(fits(x,piece.y))piece.x=x;}else if(name==='rotate'){piece.tiles.push(piece.tiles.shift());tone(270);}else if(name==='down'){if(fits(piece.x,piece.y+1))piece.y++;else lock();fallClock=0;}else if(name==='drop'){while(fits(piece.x,piece.y+1))piece.y++;tone(180);lock();}else if(name==='rescue'&&clears>0){clears--;board.splice(ROWS-3,3);board.unshift(...Array.from({length:3},()=>Array(COLS).fill(null)));speak('BREATHING ROOM');tone(300);hud();}draw();}
  function step(dt){if(!['play','clearing'].includes(phase))return;elapsed+=dt;if(toast>0){toast-=dt;if(toast<=0)$('callout').classList.remove('show');}if(phase==='clearing'){flash-=dt;if(flash<=0){fired+=matches.length;score+=matches.length*10*chain;matches.forEach(i=>board[Math.floor(i/COLS)][i%COLS]=null);settle();phase='play';hud();resolve();}return;}if(held){repeat-=dt;if(repeat<=0){action(held);repeat=.12;}}fallClock+=dt;if(fallClock>=fallInterval()){fallClock=0;action('down');}}
  function tile(v,x,y,ghost=false){ctx.save();ctx.translate(x,y);ctx.fillStyle=ghost?'#adc8e41a':colors[v];ctx.strokeStyle=ghost?'#b5d2ec': '#f6f2e9';ctx.lineWidth=ghost?2:1;ctx.beginPath();ctx.roundRect(3,3,54,54,7);ctx.fill();ctx.stroke();if(!ghost){ctx.strokeStyle=inks[v]+'55';ctx.strokeRect(9,9,42,42);ctx.fillStyle=inks[v];ctx.font='36px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbols[v],30,31);ctx.fillStyle='#ffffff55';ctx.fillRect(12,7,25,2);}else{ctx.fillStyle='#c2d9ec';ctx.font='21px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbols[v],30,30);}ctx.restore();}
  function draw(){ctx.fillStyle='#102d50';ctx.fillRect(0,0,420,800);ctx.strokeStyle='#a0b6ce';ctx.lineWidth=1;ctx.strokeRect(12,12,396,776);ctx.fillStyle='#c6d8ed';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText('T H E   E N D L E S S   K I L N',210,28);ctx.save();ctx.beginPath();ctx.rect(OX,OY,360,ROWS*CELL);ctx.clip();for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){ctx.fillStyle=(x+y)%2?'#193d63':'#17395e';ctx.fillRect(OX+x*CELL,OY+y*CELL,CELL-1,CELL-1);if(board[y][x]!==null)tile(board[y][x],OX+x*CELL,OY+y*CELL);}if(piece){let gy=piece.y;while(fits(piece.x,gy+1))gy++;piece.tiles.forEach((v,i)=>tile(v,OX+piece.x*CELL,OY+(gy+i)*CELL,true));piece.tiles.forEach((v,i)=>tile(v,OX+piece.x*CELL,OY+(piece.y+i)*CELL));}if(phase==='clearing'){for(const i of matches){ctx.fillStyle='#fff9';ctx.fillRect(OX+(i%COLS)*CELL+3,OY+Math.floor(i/COLS)*CELL+3,54,54);}}ctx.restore();ctx.strokeStyle='#ed955a';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(OX,OY+CELL*3);ctx.lineTo(390,OY+CELL*3);ctx.stroke();ctx.setLineDash([]);}
  function pause(){if(phase==='paused'){phase=pause.saved;$('pause').textContent='Pause';$('callout').classList.remove('show');}else if(['play','clearing'].includes(phase)){pause.saved=phase;phase='paused';clearInput();$('pause').textContent='Resume';$('callout').textContent='PAUSED';$('callout').classList.add('show');}}
  function instructions(){if(phase==='result')return;instructions.saved=phase;phase='instructions';clearInput();$('instruction-modal').classList.add('is-visible');$('instruction-close').focus();}
  $('instruction-close').onclick=()=>{try{sessionStorage.setItem('kiln-cascade-endless-v1','1');}catch{}$('instruction-modal').classList.remove('is-visible');phase=instructions.saved&&instructions.saved!=='instructions'?instructions.saved:'play';canvas.focus({preventScroll:true});};
  $('help-button').onclick=instructions;$('pause').onclick=pause;$('reset').onclick=()=>{const gated=phase==='instructions';score=0;start();if(gated)phase='instructions';};$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(muted));};$('again').onclick=()=>{start();canvas.focus({preventScroll:true});};
  const keymap={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'rotate',w:'rotate',ArrowDown:'down',s:'down',' ':'drop',x:'rescue'};
  window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(keymap[k]){if(e.target.tagName==='BUTTON'&&k===' ')return;e.preventDefault();if(!e.repeat){action(keymap[k]);if(['left','right','down'].includes(keymap[k])&&phase==='play'){held=keymap[k];repeat=.22;}}}else if(!e.repeat){if(k==='p')pause();if(k==='r')$('reset').click();if(k==='m')$('sound').click();}});window.addEventListener('keyup',e=>{if(keymap[e.key.length===1?e.key.toLowerCase():e.key]===held)clearInput();});
  document.querySelectorAll('[data-action]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();if(phase!=='play')return;b.setPointerCapture(e.pointerId);b.classList.add('pressed');action(b.dataset.action);if(['left','right'].includes(b.dataset.action)){held=b.dataset.action;repeat=.22;}});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,clearInput);});
  window.addEventListener('blur',()=>{clearInput();if(['play','clearing'].includes(phase))pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(['play','clearing'].includes(phase))pause();}});window.addEventListener('vibecade:reset-input',clearInput);window.addEventListener('vibecade:restart',e=>{e.preventDefault();$('reset').click();});
  start();let seen=false;try{seen=sessionStorage.getItem('kiln-cascade-endless-v1')==='1';}catch{}if(!seen){phase='instructions';}else $('instruction-modal').classList.remove('is-visible');
  if(test)window.kilnTest={state:()=>JSON.parse(JSON.stringify({board,piece,next,fired,score,clears,phase,elapsed,fall:fallInterval(),glazes:glazeCount(),muted})),start,action,step,draw,matches:findMatches,fixture:(b,p)=>{board=b;piece=p;phase='play';},progress:n=>{fired=n;hud();},finish,manual:false};
  function frame(t){const dt=Math.min((t-last)/1000||0,.05);last=t;if(!(test&&window.kilnTest.manual))step(dt);if(['play','clearing'].includes(phase))draw();requestAnimationFrame(frame);}requestAnimationFrame(frame);
})();
