(() => {
  'use strict';
  const W=960,H=600, canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
  const $=id=>document.getElementById(id);
  const profiles=[
    {quota:10,interval:1.4,speed:205,width:140,buckets:5,water:2,throw:60,pairEvery:0,pairGap:0,quick:0,zig:0},
    {quota:15,interval:1.22,speed:220,width:132,buckets:5,water:2,throw:75,pairEvery:4,pairGap:.8,quick:0,zig:0},
    {quota:19,interval:1.1,speed:235,width:128,buckets:5,water:2,throw:85,pairEvery:4,pairGap:.7,quick:0,zig:0},
    {quota:24,interval:1,speed:250,width:123,buckets:5,water:2,throw:95,pairEvery:3,pairGap:.65,quick:.15,zig:0},
    {quota:29,interval:.92,speed:270,width:118,buckets:5,water:2,throw:105,pairEvery:3,pairGap:.64,quick:.2,zig:.12},
    {quota:32,interval:.8,speed:290,width:112,buckets:4,water:1,throw:115,pairEvery:3,pairGap:.55,quick:.24,zig:.15},
    {quota:42,interval:.68,speed:320,width:105,buckets:5,water:0,throw:130,pairEvery:2,pairGap:.58,quick:.3,zig:.2}
  ];
  const state={stage:1,caught:0,score:0,buckets:5,water:2,combo:0,mode:'intro',cartX:480,cartVX:0,bomberX:480,bomberDir:1,spawnClock:0,dropCount:0,hatchX:480,hatchTime:0,spray:0,bombs:[],particles:[],flash:0,shake:0,message:'',messageTime:0,time:0,muted:false};
  let rng=1234567,keys={left:false,right:false},joy=0,last=performance.now(),audio=null,helpWasPaused=false;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  function rand(){rng=(Math.imul(rng,1664525)+1013904223)>>>0;return rng/4294967296;}
  function tone(freq,duration=.08,shape='triangle',volume=.055){if(state.muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=shape;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
  function unlockSound(){if(!audio){const AC=window.AudioContext||window.webkitAudioContext;if(AC)audio=new AC()}audio?.resume?.()}
  function say(message,seconds=1){state.message=message;state.messageTime=seconds;$('announcement').textContent=message}
  function updateHud(){const p=profiles[state.stage-1];$('stage').textContent=`${state.stage} / 7`;$('caught').textContent=`${state.caught} / ${p.quota}`;$('buckets').textContent=String(state.buckets);$('water').textContent=String(state.water);$('score').textContent=state.score.toLocaleString();$('touch-water').disabled=state.water===0;}
  function beginStage(n){const p=profiles[n-1];state.stage=n;state.caught=0;state.buckets=p.buckets;state.water=p.water;state.combo=0;state.cartX=480;state.cartVX=0;state.bomberX=480;state.bomberDir=1;state.spawnClock=.65;state.dropCount=0;state.hatchTime=0;state.spray=0;state.bombs=[];state.particles=[];state.flash=0;state.shake=0;state.time=0;state.mode='playing';rng=(n*88311+5379)>>>0;say(n===1?'FOLLOW THE LANDING ARROWS':`SHIFT ${n}`,n===1?2.6:1.4);updateHud();last=performance.now();canvas.focus({preventScroll:true})}
  function reset(){state.score=0;keys={left:false,right:false};joy=0;$('pause').textContent='Pause';beginStage(1);$('result-modal').classList.remove('is-visible')}
  function reflectX(x){const span=W-36,period=span*2;let n=((x-18)%period+period)%period;return 18+(n>span?period-n:n)}
  function predictLanding(q){let x=q.x,vx=q.vx,y=q.y;const targetY=515;if(q.type==='zig'&&!q.turned&&y<300){const first=(300-y)/q.vy;x=reflectX(x+vx*first);y=300;vx=-vx}return reflectX(x+vx*Math.max(0,(targetY-y)/q.vy))}
  function addBomb(x,type,vx,vy,secondary=false){state.bombs.push({x,y:96,vx,vy,type,turned:false,phase:rand()*6.28,spin:rand()*6.28,secondary})}
  function spawn(){const p=profiles[state.stage-1],r=rand(),type=r<p.zig?'zig':r<p.zig+p.quick?'quick':'normal';const x=clamp(state.bomberX+(rand()-.5)*36,42,W-42);const direction=rand()<.5?-1:1;const vx=direction*p.throw*(.75+rand()*.5);const vy=p.speed*(type==='quick'?1.27:1);addBomb(x,type,vx,vy);state.dropCount++;const pair=Boolean(p.pairEvery&&state.dropCount%p.pairEvery===0);
    if(pair){const landing=reflectX(x+vx*(515-96)/vy),side=landing<260?1:landing>700?-1:rand()<.5?-1:1;const desired=clamp(landing+side*(185+rand()*35),65,895);const secondVx=-side*p.throw*.3;const secondVy=(515-96)/((515-96)/vy+p.pairGap);const secondX=clamp(desired-secondVx*(515-96)/secondVy,42,W-42);addBomb(secondX,'normal',secondVx,secondVy,true);state.hatchX=secondX;state.hatchTime=.45;if(state.dropCount===p.pairEvery)say('DOUBLE DROP',.75)}
    tone(220,.035,'square',.018);return pair}
  function burst(x,y,color,count=10){for(let i=0;i<count;i++){const a=rand()*Math.PI*2,s=35+rand()*115;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+rand()*.42,size:2+rand()*4,color})}if(state.particles.length>140)state.particles.splice(0,state.particles.length-140)}
  function catchBomb(index,water=false){const b=state.bombs[index];state.bombs.splice(index,1);state.caught++;state.combo++;state.score+=(water?50:100)+Math.min(15,state.combo)*10;burst(b.x,b.y,water?'#7dc6d1':'#edb64d',11);tone(350+Math.min(12,state.combo)*35,.08);state.flash=.07;if(state.combo>0&&state.combo%8===0)say(`${state.combo} IN A ROW!`,.8);updateHud();if(state.caught>=profiles[state.stage-1].quota)endStage(true)}
  function missBomb(index){const b=state.bombs[index];state.bombs.splice(index,1);state.buckets--;state.combo=0;state.shake=.24;state.flash=.18;burst(b.x,547,'#b94b38',16);tone(100,.22,'sawtooth',.065);say(state.buckets>0?'BUCKET LOST!':'PATROL ENDED',1);updateHud();if(state.buckets<=0)endStage(false)}
  function sweep(){if(state.mode!=='playing'||state.water<1)return;const inReach=b=>b.y>310&&Math.abs(b.x-state.cartX)<210;if(!state.bombs.some(inReach)){say('MOVE NEAR A LOW BOMB',.8);return}unlockSound();state.water--;let cleaned=0;for(let i=state.bombs.length-1;i>=0;i--)if(inReach(state.bombs[i])){catchBomb(i,true);cleaned++;if(state.mode!=='playing')break}state.spray=.32;burst(state.cartX,520,'#8bd7d2',24);tone(580,.22,'sine',.07);say(`WATER SWEEP +${cleaned}`,.75);updateHud()}
  function endStage(won){state.mode=won?'clear':'over';$('result-modal').classList.add('is-visible');$('next').hidden=!won||state.stage===7;$('again').hidden=won&&state.stage<7;$('result-title').textContent=won?(state.stage===7?'SEVEN SHIFTS SAFE!':`SHIFT ${state.stage} SECURED`):'BUCKETS EMPTY';$('result-text').textContent=won?`${state.caught} caught · ${state.buckets} buckets saved · ${state.score.toLocaleString()} points`:`Caught ${state.caught} of ${profiles[state.stage-1].quota}. Roll out and try again.`;tone(won?660:130,.25,won?'triangle':'sawtooth',.055);($('next').hidden?$('again'):$('next')).focus()}
  function tick(dt){if(state.mode!=='playing')return;const p=profiles[state.stage-1];state.time+=dt;state.flash=Math.max(0,state.flash-dt);state.shake=Math.max(0,state.shake-dt);state.hatchTime=Math.max(0,state.hatchTime-dt);state.spray=Math.max(0,state.spray-dt);if(state.messageTime>0){state.messageTime-=dt;if(state.messageTime<=0){state.message='';$('announcement').textContent=''}}
    const input=clamp((keys.right?1:0)-(keys.left?1:0)+joy,-1,1);const target=input*(590+Math.max(0,state.stage-4)*35);state.cartVX+=(target-state.cartVX)*Math.min(1,dt*11);state.cartX=clamp(state.cartX+state.cartVX*dt,p.width/2+22,W-p.width/2-22);
    state.bomberX+=state.bomberDir*(180+state.stage*26)*dt;if(state.bomberX<70){state.bomberX=70;state.bomberDir=1}else if(state.bomberX>890){state.bomberX=890;state.bomberDir=-1}
    state.spawnClock-=dt;if(state.spawnClock<=0){const pair=spawn();state.spawnClock+=p.interval*(.88+rand()*.24)+(pair?p.pairGap*.75:0)}
    for(let i=state.bombs.length-1;i>=0;i--){const b=state.bombs[i];b.y+=b.vy*dt;b.x+=b.vx*dt;if(b.type==='zig'&&!b.turned&&b.y>=300){b.vx=-b.vx;b.turned=true;burst(b.x,b.y,'#7ab7bb',5)}b.spin+=dt*8;if(b.x<18){b.x=36-b.x;b.vx=Math.abs(b.vx)}else if(b.x>W-18){b.x=(W-18)*2-b.x;b.vx=-Math.abs(b.vx)}if(b.y>=510&&b.y<=555&&Math.abs(b.x-state.cartX)<=p.width/2+10){catchBomb(i);if(state.mode!=='playing')break}else if(b.y>558){missBomb(i);if(state.mode!=='playing')break}}
    for(let i=state.particles.length-1;i>=0;i--){const q=state.particles[i];q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=130*dt;q.life-=dt;if(q.life<=0)state.particles.splice(i,1)}
  }
  const bg=document.createElement('canvas');bg.width=W;bg.height=H;const b=bg.getContext('2d');
  function makeBackground(){b.fillStyle='#eadcbb';b.fillRect(0,0,W,H);b.fillStyle='#dfcda8';for(let y=0;y<H;y+=42){b.fillRect(0,y,W,2);for(let x=(y/42%2)*48;x<W;x+=96)b.fillRect(x,y,2,42)}b.fillStyle='#204554';b.fillRect(0,0,W,87);b.fillStyle='#183b4b';b.fillRect(0,75,W,16);b.fillStyle='#af4636';for(let x=0;x<W;x+=80){b.beginPath();b.moveTo(x,87);b.lineTo(x+40,112);b.lineTo(x+80,87);b.fill()}b.fillStyle='#a8bdaf';for(let x=65;x<W;x+=170){b.fillRect(x,146,82,140);b.fillStyle='#f7edcf';b.fillRect(x+8,154,66,119);b.fillStyle='#a8bdaf';b.fillRect(x+38,154,6,119);b.fillRect(x+8,211,66,6);b.fillStyle='#a8bdaf'}b.fillStyle='#234451';b.fillRect(0,555,W,45);b.fillStyle='#c39159';b.fillRect(0,550,W,8);b.fillStyle='#edce8d';for(let x=20;x<W;x+=80)b.fillRect(x,575,30,4);b.fillStyle='#f0e0bc';b.fillRect(360,10,240,52);b.strokeStyle='#b4523c';b.lineWidth=3;b.strokeRect(360,10,240,52);b.fillStyle='#193b4a';b.font='900 27px Georgia';b.textAlign='center';b.fillText('FUSE PATROL',480,44)}makeBackground();
  function drawBomb(q){ctx.save();ctx.translate(q.x,q.y);ctx.rotate(Math.sin(q.spin)*.12);ctx.fillStyle='rgba(25,49,57,.17)';ctx.beginPath();ctx.ellipse(0,13,17,5,0,0,7);ctx.fill();ctx.fillStyle=q.type==='quick'?'#d99e36':q.type==='zig'?'#5b9aa4':'#bd4c3b';ctx.beginPath();ctx.arc(0,0,15,0,7);ctx.fill();ctx.strokeStyle='#203b45';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#f6dfaa';ctx.beginPath();ctx.arc(-5,-5,4,0,7);ctx.fill();ctx.strokeStyle='#233d45';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(1,-14);ctx.quadraticCurveTo(10,-28,16,-22);ctx.stroke();ctx.fillStyle='#ecb247';ctx.beginPath();ctx.moveTo(16,-22);ctx.lineTo(22,-30);ctx.lineTo(21,-18);ctx.closePath();ctx.fill();ctx.fillStyle='#fff2ba';ctx.fillRect(24,-31,3,3);ctx.fillRect(13,-36,2,2);if(q.type==='zig'){ctx.fillStyle='#fff3c9';ctx.font='900 17px Georgia';ctx.textAlign='center';ctx.fillText('Z',0,6)}ctx.restore()}
  function drawCart(){const p=profiles[state.stage-1],x=state.cartX,w=p.width;ctx.save();ctx.translate(x,0);ctx.fillStyle='#163a49';ctx.fillRect(-w*.58,525,w*1.16,27);ctx.fillStyle='#b84736';ctx.beginPath();ctx.moveTo(-w/2,510);ctx.lineTo(w/2,510);ctx.lineTo(w*.42,549);ctx.lineTo(-w*.42,549);ctx.closePath();ctx.fill();ctx.strokeStyle='#f3dfb3';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-w/2,511);ctx.lineTo(w/2,511);ctx.stroke();ctx.fillStyle='#eed39b';ctx.beginPath();ctx.arc(-w*.35,553,12,0,7);ctx.arc(w*.35,553,12,0,7);ctx.fill();ctx.fillStyle='#223f4b';ctx.font='900 14px Georgia';ctx.textAlign='center';ctx.fillText('SAFE',0,538);ctx.restore()}
  function render(){ctx.save();if(state.shake>0)ctx.translate((Math.random()-.5)*state.shake*20,(Math.random()-.5)*state.shake*10);ctx.drawImage(bg,0,0);
    if(state.hatchTime>0){ctx.globalAlpha=state.hatchTime/.45;ctx.fillStyle='#a84537';ctx.fillRect(state.hatchX-25,82,50,16);ctx.fillStyle='#fff0c7';ctx.fillRect(state.hatchX-17,87,34,5);ctx.globalAlpha=1}
    ctx.fillStyle='#143b49';ctx.fillRect(state.bomberX-47,83,94,24);ctx.fillStyle='#bb4a38';ctx.fillRect(state.bomberX-36,70,72,20);ctx.fillStyle='#f6e4ba';ctx.beginPath();ctx.arc(state.bomberX,69,15,0,7);ctx.fill();ctx.fillStyle='#223d46';ctx.fillRect(state.bomberX-22,55,44,8);ctx.fillRect(state.bomberX-13,42,26,16);ctx.fillStyle='#f8e3b6';ctx.fillRect(state.bomberX-32,89,64,5);
    for(const q of state.bombs){const mark=predictLanding(q),color=q.type==='zig'?'#277d88':'#a84537';ctx.globalAlpha=.35+.25*clamp(q.y/500,0,1);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash([6,8]);ctx.beginPath();ctx.moveTo(q.x,q.y+16);ctx.quadraticCurveTo((q.x+mark)/2,q.y+80,mark,521);ctx.stroke();ctx.setLineDash([]);ctx.globalAlpha=.68+.25*clamp(q.y/500,0,1);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(mark,519);ctx.lineTo(mark-17,539);ctx.lineTo(mark+17,539);ctx.closePath();ctx.fill();ctx.fillRect(mark-3,539,6,9);ctx.globalAlpha=.45;ctx.strokeStyle='#835c43';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(q.x-q.vx*.16,q.y-q.vy*.16);ctx.lineTo(q.x-q.vx*.07,q.y-q.vy*.07);ctx.stroke();ctx.globalAlpha=1;drawBomb(q)}
    drawCart();if(state.spray>0){ctx.globalAlpha=state.spray/.32;ctx.strokeStyle='#78bdc5';ctx.lineWidth=12;ctx.beginPath();ctx.arc(state.cartX,520,204,Math.PI*1.04,Math.PI*1.96);ctx.stroke();ctx.globalAlpha=1}
    for(const q of state.particles){ctx.globalAlpha=clamp(q.life*1.7,0,1);ctx.fillStyle=q.color;ctx.beginPath();ctx.arc(q.x,q.y,q.size,0,7);ctx.fill()}ctx.globalAlpha=1;if(state.flash>0){ctx.fillStyle=`rgba(255,238,185,${state.flash*.55})`;ctx.fillRect(0,0,W,H)}ctx.restore()}
  function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;tick(dt);render();requestAnimationFrame(frame)}
  document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright',' '].includes(k))e.preventDefault();if(state.mode==='intro'||state.mode==='help')return;if(k==='arrowleft'||k==='a')keys.left=true;if(k==='arrowright'||k==='d')keys.right=true;if(k===' '&&!e.repeat)sweep();if(k==='p')togglePause();if(k==='r')reset();if(k==='m')toggleSound()});
  document.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')keys.left=false;if(k==='arrowright'||k==='d')keys.right=false});window.addEventListener('blur',()=>{keys.left=false;keys.right=false;joy=0;if(state.mode==='playing')togglePause()});
  function toggleSound(){state.muted=!state.muted;$('sound').textContent=state.muted?'Sound off':'Sound on';$('touch-sound').textContent=state.muted?'SOUND OFF':'SOUND';if(!state.muted){unlockSound();tone(520)}}
  function togglePause(){if(state.mode==='playing'){state.mode='paused';$('pause').textContent='Resume';say('PAUSED',100000)}else if(state.mode==='paused'){state.mode='playing';$('pause').textContent='Pause';say('',0);last=performance.now()}}
  function showHelp(){helpWasPaused=state.mode==='paused';if(state.mode==='playing'||state.mode==='paused'){state.mode='help';$('instruction-modal').classList.add('is-visible');keys.left=false;keys.right=false;joy=0}}
  function hideHelp(){if(state.mode==='intro'){sessionStorage.setItem('vibecade-fuse-catch-instructions-v2','1');unlockSound();beginStage(1)}else if(state.mode==='help'){state.mode=helpWasPaused?'paused':'playing';if(state.mode==='paused')say('PAUSED',100000);last=performance.now()}$('instruction-modal').classList.remove('is-visible')}
  $('instruction-close').addEventListener('click',hideHelp);$('help-button').addEventListener('click',showHelp);$('pause').addEventListener('click',togglePause);$('reset').addEventListener('click',reset);$('sound').addEventListener('click',toggleSound);$('touch-sound').addEventListener('click',toggleSound);$('touch-water').addEventListener('click',e=>{e.preventDefault();sweep()});$('next').addEventListener('click',()=>{$('result-modal').classList.remove('is-visible');beginStage(state.stage+1)});$('again').addEventListener('click',reset);
  window.addEventListener('vibecade:restart',e=>{e.preventDefault();if(state.mode!=='intro'&&state.mode!=='help')reset()});const bind=()=>window.VibeCadeJoystick?.(document.querySelector('[data-joystick]'),{mode:'horizontal',profile:'precision',onChange:x=>{joy=x}});if(window.VibeCadeJoystick)bind();else window.addEventListener('vibecade-controls-ready',bind,{once:true});
  if(sessionStorage.getItem('vibecade-fuse-catch-instructions-v2')==='1'){$('instruction-modal').classList.remove('is-visible');beginStage(1)}else updateHud();
  if(new URLSearchParams(location.search).has('test'))window.__fuseTest={state,profiles,predictLanding,jump:n=>{if(n>=1&&n<=7){$('instruction-modal').classList.remove('is-visible');$('result-modal').classList.remove('is-visible');beginStage(n)}},tick,spawn,sweep};
  requestAnimationFrame(frame);
})();
