(() => {
  'use strict';
  const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),art=window.HarborArt;
  const params=new URLSearchParams(location.search),test=params.has('test'),C=50,cols=20,rows=12;
  const profiles=[
    {name:'Quiet Anchorage',gaps:4,build:45,ships:3,speed:0,interval:3.5,enemy:9,battle:45,hp:5,mends:2},
    {name:'The Running Tide',gaps:6,build:42,ships:4,speed:24,interval:3.2,enemy:8.5,battle:45,hp:5,mends:2},
    {name:'Iron Sails',gaps:8,build:39,ships:5,speed:29,interval:2.8,enemy:8,battle:48,hp:5,mends:2},
    {name:'Broken Headland',gaps:10,build:36,ships:6,speed:34,interval:2.4,enemy:7,battle:48,hp:5,mends:2},
    {name:'The Grand Armada',gaps:12,build:33,ships:8,speed:39,interval:1.85,enemy:6.3,battle:50,hp:5,mends:2},
    {name:'Master of the Coast',gaps:14,build:24,ships:10,speed:54,interval:1.5,enemy:4.1,battle:48,hp:3,mends:1},
    {name:'The Last Bastion',gaps:16,build:19,ships:12,speed:67,interval:1.25,enemy:3.0,battle:45,hp:2,mends:0}
  ];
  const perimeter=[];for(let x=1;x<=7;x++){perimeter.push([x,2],[x,9]);}for(let y=3;y<=8;y++)perimeter.push([1,y],[7,y]);
  const shapes=[[[0,0],[1,0]],[[0,0],[1,0],[2,0]],[[0,0],[1,0],[0,1]]];
  const state={level:1,phase:'build',mode:'intro',time:0,score:0,muted:false,walls:new Set(),ships:[],shots:[],shells:[],fx:[],aim:{x:725,y:300},cursor:{x:5,y:2},rotation:0,piece:0,cooldown:0,mends:2,hp:5,spawned:0,kills:0};
  let last=0,acc=0,manual=false,pointerFire=false,keyFire=false,dirty=true,audio=null,toastTime=0,previousMode='playing',savedScore=0,held=new Set(),keyWait=0,cannonIndex=0,hudWait=0,fortDirty=true;
  const fort=document.createElement('canvas');fort.width=1000;fort.height=600;const fortCtx=fort.getContext('2d');
  const index=(x,y)=>y*cols+x,active=()=>state.mode==='playing'&&!portrait(),portrait=()=>document.body.classList.contains('touch-device')&&matchMedia('(orientation:portrait)').matches;
  function tone(freq,duration=.07){if(state.muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
  function unlockAudio(){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{});}catch(_){}}
  function message(text,seconds=2.5){$('toast').textContent=text;toastTime=seconds;dirty=true;}
  function resetInput(){held.clear();pointerFire=false;keyFire=false;keyWait=0;}
  function shape(){let points=shapes[state.piece%(state.level>=4?3:2)].map(p=>p.slice());for(let n=0;n<state.rotation;n++)points=points.map(([x,y])=>[-y,x]);const minX=Math.min(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1]));return points.map(([x,y])=>[x-minX,y-minY]);}
  function cells(){return shape().map(([x,y])=>[x+state.cursor.x,y+state.cursor.y]);}
  function valid(){const pts=cells();return pts.every(([x,y])=>x>=0&&x<10&&y>=0&&y<rows&&!(x>=3&&x<=5&&y>=4&&y<=7))&&pts.some(([x,y])=>!state.walls.has(index(x,y)));}
  function enclosure(){const seen=new Set(),queue=[];for(let x=0;x<10;x++)queue.push([x,0],[x,11]);for(let y=1;y<11;y++)queue.push([0,y],[9,y]);for(let i=0;i<queue.length;i++){const [x,y]=queue[i],id=index(x,y);if(seen.has(id)||state.walls.has(id))continue;seen.add(id);for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy;if(nx>=0&&nx<10&&ny>=0&&ny<12&&!seen.has(index(nx,ny)))queue.push([nx,ny]);}}return {sealed:!seen.has(index(4,5)),area:120-seen.size-state.walls.size,seen};}
  function begin(level,keepScore=true){resetInput();$('result-modal').classList.remove('is-visible');state.level=Math.max(1,Math.min(7,level));state.cfg=profiles[state.level-1];state.phase='build';state.mode='playing';state.time=state.cfg.build;state.elapsed=0;state.hp=state.cfg.hp;state.mends=state.cfg.mends;state.walls=new Set(perimeter.map(([x,y])=>index(x,y)));state.ships=[];state.shots=[];state.shells=[];state.fx=[];state.piece=0;state.rotation=0;state.cursor={x:4,y:2};state.cooldown=0;state.spawned=0;state.kills=0;state.spawnTime=0;state.shotsFired=0;state.misses=0;state.damage=0;state.aim={x:725,y:300};if(!keepScore)state.score=0;savedScore=state.score;
    // Spaced gaps remain solvable by overlapping pieces with the intact rampart.
    const order=[4,21,8,17,12,23,2,19,10,25,6,15,0,13,16,22];for(let i=0;i<state.cfg.gaps;i++){const [x,y]=perimeter[order[i]];state.walls.delete(index(x,y));}
    cannonIndex=0;state.interceptions=0;fortDirty=true;hudWait=0;message(state.cfg.name+' · seal the fort',3);sync();dirty=true;
  }
  function place(){if(!active()||state.phase!=='build')return;if(!valid()){message('Keep pieces on land, away from the keep.',1.4);tone(140);return;}for(const [x,y]of cells())state.walls.add(index(x,y));fortDirty=true;state.piece++;state.rotation=0;tone(400);const e=enclosure();if(e.sealed)message('FORT SEALED · choose TO BATTLE',3);sync();dirty=true;}
  function rotate(){if(!active()||state.phase!=='build')return;state.rotation=(state.rotation+1)%4;tone(280,.025);dirty=true;}
  function launch(){if(!active()||state.phase!=='build'||!enclosure().sealed)return;state.score+=enclosure().area*5+Math.ceil(state.time);state.phase='siege';state.time=state.cfg.battle;state.elapsed=0;resetInput();message('Lead your shots. Red shells can be intercepted.',3);sync();dirty=true;}
  function spawn(){const id=state.spawned++,type=state.level>=5&&id%4===3?'galleon':state.level>=3&&id%3===2?'armor':'sloop';state.ships.push({id,type,x:615+(id%3)*135,y:90+(id*137%390),dir:id%2?1:-1,hp:type==='galleon'?3:type==='armor'?2:1,fire:[6,4,3.5,2.5,1.9,1.25,.8][state.level-1]+(id%3)*.2,speed:state.cfg.speed*(type==='galleon'?.85:1)});}
  const cannons=[[320,200],[320,300],[320,400]];
  function fire(){if(!active()||state.phase!=='siege'||state.cooldown>0)return;const start=cannons[cannonIndex++%3],distance=Math.hypot(state.aim.x-start[0],state.aim.y-start[1]);state.shots.push({x:start[0],y:start[1],sx:start[0],sy:start[1],tx:state.aim.x,ty:state.aim.y,t:0,duration:distance/600});burst(start[0]+30,start[1],'#ffdeb0',4);state.cooldown=.42;state.shotsFired++;tone(110,.09);dirty=true;}
  function burst(x,y,color='#f2cd8a',count=12){for(let i=0;i<count&&state.fx.length<100;i++)state.fx.push({x,y,vx:Math.cos(i*2.4)*((i%3)*25+28),vy:Math.sin(i*2.4)*60,life:.65,max:.65,color});}
  function damage(){if(state.mode!=='playing')return;state.hp--;state.damage++;fortDirty=true;burst(243,290,'#d7724b',16);tone(75,.18);message('KEEP HIT · MEND restores walls, not health.',2);if(state.hp<=0)finish(false,'The keep fell. Repair earlier and intercept incoming shells.');}
  function impact(shell){const x=Math.floor(shell.tx/C),y=Math.floor(shell.ty/C),id=index(x,y);if(state.walls.has(id)){state.walls.delete(id);fortDirty=true;burst(shell.tx,shell.ty);message('Wall breached · MEND or intercept the next shell',2);}else if(!enclosure().sealed)damage();else burst(shell.tx,shell.ty,'#d5cd9e',6);dirty=true;}
  function enemyFire(s){const e=enclosure(),breaches=perimeter.filter(([x,y])=>!state.walls.has(index(x,y))&&e.seen.has(index(x,y))),intact=perimeter.filter(([x,y])=>state.walls.has(index(x,y)));const targets=!e.sealed&&breaches.length?breaches:intact;const target=targets[(s.id+state.damage)%targets.length]||[4,5];const [x,y]=target;const t={x:s.x,y:s.y,sx:s.x,sy:s.y,tx:x*C+25,ty:y*C+25,t:0,duration:state.level>=6?1.65:2.4};state.shells.push(t);if(s.type==='galleon'){state.shells.push({...t,tx:t.tx,ty:t.ty,t:-.6});}dirty=true;}
  function mend(){if(!active()||state.phase!=='siege'||state.mends<=0)return;const missing=perimeter.some(([x,y])=>!state.walls.has(index(x,y)));if(!missing&&!state.shells.length){message('Walls intact. Save your MEND.',1.4);return;}state.mends--;perimeter.forEach(([x,y])=>state.walls.add(index(x,y)));fortDirty=true;state.shells=[];message('RAMPART RESTORED · incoming shells cleared',2);tone(650,.18);sync();dirty=true;}
  function finish(win,text){if(state.mode!=='playing')return;resetInput();state.mode=win?'won':'lost';$('result-title').textContent=win?(state.level===7?'The coast is yours.':'Coast secured.'):'A breach in the line.';$('result-text').textContent=text||(state.cfg.name+' · '+state.kills+' ships sunk · '+state.hp+' keep health · '+state.misses+' missed shots.');$('next').hidden=!win||state.level===7;$('retry').hidden=win;$('again').textContent=win&&state.level===7?'SAIL AGAIN':'START AGAIN';$('result-modal').classList.add('is-visible');(win&&state.level<7?$('next'):win?$('again'):$('retry')).focus();tone(win?760:130,.25);sync();dirty=true;}
  function tick(dt){if(!active())return;state.time-=dt;state.elapsed+=dt;state.cooldown=Math.max(0,state.cooldown-dt);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').textContent='';}if(state.time<=0){finish(false,state.phase==='build'?'The repair clock ran out. Overlap stones with existing walls and seal every gap.':'The fleet outlasted your cannons. Lead moving targets and prioritize galleons.');return;}
    if(held.size){keyWait-=dt;if(keyWait<=0){keyWait=state.phase==='build'?.12:1/60;const x=(held.has('ArrowRight')||held.has('d')?1:0)-(held.has('ArrowLeft')||held.has('a')?1:0),y=(held.has('ArrowDown')||held.has('s')?1:0)-(held.has('ArrowUp')||held.has('w')?1:0);move(x,y,state.phase==='build'?1:7);}}
    if(state.phase==='siege'){
      if(pointerFire||keyFire)fire();state.spawnTime-=dt;if(state.spawned<state.cfg.ships&&state.spawnTime<=0){spawn();state.spawnTime=state.cfg.interval;}
      for(const s of state.ships){s.y+=s.dir*s.speed*dt;if(s.y>515){s.y=515;s.dir=-1;}if(s.y<80){s.y=80;s.dir=1;}s.fire-=dt;if(s.fire<=0){enemyFire(s);s.fire=state.cfg.enemy;}}
      for(let i=state.shots.length-1;i>=0;i--){const shot=state.shots[i];shot.t+=dt;const a=Math.min(1,shot.t/shot.duration);shot.x=shot.sx+(shot.tx-shot.sx)*a;shot.y=shot.sy+(shot.ty-shot.sy)*a;if(a>=1){let hit=false;for(let j=state.ships.length-1;j>=0;j--){const s=state.ships[j];if(Math.hypot((shot.tx-s.x)*1.15,shot.ty-s.y)<(s.type==='galleon'?54:46)){s.hp--;hit=true;burst(shot.tx,shot.ty,'#ffe4a3');if(s.hp<=0){state.ships.splice(j,1);state.kills++;state.score+=s.type==='galleon'?400:s.type==='armor'?250:150;tone(540,.1);}break;}}
          for(let j=state.shells.length-1;j>=0;j--){const q=state.shells[j];if(q.t>=0&&Math.hypot(shot.tx-q.x,shot.ty-q.y)<70){state.shells.splice(j,1);hit=true;state.interceptions++;state.score+=80;burst(q.x,q.y,'#fba279');}}
          if(!hit){state.misses++;burst(shot.tx,shot.ty,'#baded4',6);}state.shots.splice(i,1);}}
      for(let i=state.shells.length-1;i>=0;i--){const q=state.shells[i];q.t+=dt;const a=Math.max(0,Math.min(1,q.t/q.duration));q.x=q.sx+(q.tx-q.sx)*a;q.y=q.sy+(q.ty-q.sy)*a;if(a>=1){state.shells.splice(i,1);impact(q);if(state.mode!=='playing')return;}}
      if(state.kills===state.cfg.ships){state.score+=state.hp*150+Math.ceil(state.time)*10;finish(true);return;}
    }
    for(let i=state.fx.length-1;i>=0;i--){const f=state.fx[i];f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;if(f.life<=0)state.fx.splice(i,1);}hudWait-=dt;if(hudWait<=0){sync();hudWait=.1;}dirty=true;
  }
  function move(x,y,amount=1){if(!active())return;if(state.phase==='build'){state.cursor.x=Math.max(0,Math.min(9,state.cursor.x+x*amount));state.cursor.y=Math.max(0,Math.min(11,state.cursor.y+y*amount));}else{state.aim.x=Math.max(20,Math.min(980,state.aim.x+x*amount));state.aim.y=Math.max(25,Math.min(575,state.aim.y+y*amount));}dirty=true;}
  function sync(){const build=state.phase==='build',sealed=build&&enclosure().sealed;$('level').textContent=state.level+' / 7';const gaps=build?perimeter.filter(([x,y])=>!state.walls.has(index(x,y))).length:0;$('phase').textContent=build?(sealed?'SEALED':gaps+' GAPS'):state.kills+' / '+state.cfg.ships+' SUNK';$('clock').textContent=Math.max(0,Math.ceil(state.time))+'s';$('clock').classList.toggle('danger',state.time<10);$('health').textContent=state.hp+' / '+state.cfg.hp;$('health').classList.toggle('danger',state.hp<=2);$('score').textContent=state.score;$('place').hidden=!build;$('rotate').hidden=!build;$('launch').hidden=!build;$('launch').disabled=!sealed;$('mend').hidden=build;$('mend').textContent='MEND '+state.mends+' · E';$('mend').disabled=state.mends<=0;$('order').textContent=build?(sealed?'Fort sealed. Extra enclosed land earns points.':'Seal the keep. Pieces can overlap intact walls.'):'Aim ahead of moving ships. Intercept red shells.';$('pause').textContent=state.mode==='paused'?'Resume':'Pause';}
  function draw(){ctx.clearRect(0,0,1000,600);ctx.drawImage(art.background,0,0);if(state.phase==='build'){const e=enclosure();ctx.fillStyle=e.sealed?'#fff1ba25':'#e18b6530';for(let y=3;y<=8;y++)for(let x=2;x<=6;x++)if(!state.walls.has(index(x,y)))ctx.fillRect(x*C,y*C,C,C);}
    if(fortDirty){fortCtx.clearRect(0,0,1000,600);for(const id of state.walls)art.stone(fortCtx,id%cols,Math.floor(id/cols));art.keep(fortCtx,state.hp);fortDirty=false;}ctx.drawImage(fort,0,0);
    for(const [x,y]of cannons)art.cannon(ctx,x,y,Math.atan2(state.aim.y-y,state.aim.x-x),state.cooldown<=0);
    if(state.phase==='build'){ctx.fillStyle='#a6533970';perimeter.forEach(([x,y])=>{if(!state.walls.has(index(x,y))){ctx.fillRect(x*C+4,y*C+4,42,42);ctx.strokeStyle='#edbd86';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.strokeRect(x*C+5,y*C+5,40,40);ctx.setLineDash([]);}});const ok=valid();for(const [x,y]of cells()){if(x>=0&&x<20&&y>=0&&y<12){art.stone(ctx,x,y,true);ctx.strokeStyle=ok?'#fff6a5':'#bc513e';ctx.lineWidth=3;ctx.strokeRect(x*C+2,y*C+2,45,42);}}}
    for(const s of state.ships){art.ship(ctx,s,state.elapsed);if(s.fire<.85){ctx.strokeStyle='#ffbd78';ctx.lineWidth=3;ctx.beginPath();ctx.arc(s.x,s.y,62,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-s.fire/.85));ctx.stroke();ctx.fillStyle='#ffe0ad';ctx.font='bold 17px system-ui';ctx.fillText('!',s.x-52,s.y+8);}}
    for(const q of state.shells){if(q.t<0)continue;ctx.strokeStyle='#f6a07480';ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(q.x,q.y);ctx.lineTo(q.tx,q.ty);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#fff4c5';ctx.strokeRect(q.tx-11,q.ty-11,22,22);ctx.fillStyle='#f6774e';ctx.beginPath();ctx.arc(q.x,q.y-Math.sin(Math.min(1,q.t/q.duration)*Math.PI)*24,8,0,Math.PI*2);ctx.fill();}
    for(const q of state.shots){ctx.fillStyle='#fff3c5';ctx.beginPath();ctx.arc(q.x,q.y-Math.sin(Math.min(1,q.t/q.duration)*Math.PI)*30,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#183a3b';ctx.lineWidth=2;ctx.stroke();}
    if(state.phase==='siege'){ctx.strokeStyle='#fff0b2';ctx.lineWidth=2;ctx.beginPath();ctx.arc(state.aim.x,state.aim.y,18,0,Math.PI*2);ctx.moveTo(state.aim.x-28,state.aim.y);ctx.lineTo(state.aim.x+28,state.aim.y);ctx.moveTo(state.aim.x,state.aim.y-28);ctx.lineTo(state.aim.x,state.aim.y+28);ctx.stroke();}
    const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;for(const f of state.fx){if(reduced)continue;ctx.globalAlpha=Math.max(0,f.life/f.max);ctx.fillStyle=f.color;ctx.fillRect(f.x,f.y,5,5);}ctx.globalAlpha=1;
    if(state.mode==='paused'){ctx.fillStyle='#123e45aa';ctx.fillRect(0,0,1000,600);ctx.fillStyle='#fff1cb';ctx.font='bold 46px Georgia';ctx.textAlign='center';ctx.fillText('Command paused',500,300);ctx.textAlign='left';}dirty=false;
  }
  function animate(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(!manual&&active()){acc=Math.min(acc+dt,.1);while(acc>=1/60){tick(1/60);acc-=1/60;}}else acc=0;if(dirty)draw();requestAnimationFrame(animate);}
  function pause(){if(state.mode==='playing'){state.mode='paused';resetInput();}else if(state.mode==='paused')state.mode='playing';sync();dirty=true;}
  function help(){if(state.mode==='intro')return;previousMode=state.mode;state.mode='help';resetInput();$('instruction-modal').classList.add('is-visible');$('instruction-close').textContent='RETURN TO COMMAND';$('instruction-close').focus();dirty=true;}
  function closeInstructions(){unlockAudio();$('instruction-modal').classList.remove('is-visible');try{sessionStorage.setItem('harbor-bastion-instructions-v1','seen');}catch(_){}state.mode=state.mode==='help'?previousMode:'playing';canvas.focus({preventScroll:true});sync();dirty=true;}
  function restart(){const gated=state.mode==='intro'||state.mode==='help';begin(1,false);if(gated){state.mode='intro';$('instruction-modal').classList.add('is-visible');$('instruction-close').textContent='TAKE COMMAND';}sync();}
  function locate(e){const r=canvas.getBoundingClientRect();const x=(e.clientX-r.left)/r.width*1000,y=(e.clientY-r.top)/r.height*600;if(state.phase==='build'){state.cursor={x:Math.max(0,Math.min(9,Math.floor(x/C))),y:Math.max(0,Math.min(11,Math.floor(y/C)))};}else state.aim={x:Math.max(20,Math.min(980,x)),y:Math.max(25,Math.min(575,y))};dirty=true;}
  canvas.addEventListener('pointerdown',e=>{e.preventDefault();if(!active())return;unlockAudio();canvas.focus({preventScroll:true});canvas.setPointerCapture(e.pointerId);locate(e);if(state.phase==='build'){if(e.pointerType==='mouse')place();}else{pointerFire=true;fire();}});
  canvas.addEventListener('pointermove',e=>{if(active()&&(e.pointerType==='mouse'||canvas.hasPointerCapture(e.pointerId)))locate(e);});
  for(const type of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(type,()=>{pointerFire=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
  window.addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;const modal=document.querySelector('.modal.is-visible');if(modal){if(k==='Tab'){const buttons=[...modal.querySelectorAll('button:not([hidden])')];if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0].focus();}}if(k==='Escape'&&state.mode==='help')closeInstructions();return;}if(e.target.closest('button')&&(k===' '||k==='Enter'))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','w','a','s','d','x','e','r','p','m'].includes(k))e.preventDefault();if(k==='r'){restart();return;}if(k==='p'){pause();return;}if(k==='m'){sound();return;}if(!active())return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','w','a','s','d'].includes(k)){if(!held.has(k)){const x=k==='ArrowRight'||k==='d'?1:k==='ArrowLeft'||k==='a'?-1:0,y=k==='ArrowDown'||k==='s'?1:k==='ArrowUp'||k==='w'?-1:0;move(x,y,state.phase==='build'?1:15);keyWait=.18;}held.add(k);}if(k===' '){if(state.phase==='build'){if(!e.repeat)place();}else{keyFire=true;fire();}}if(k==='x'&&!e.repeat)rotate();if(k==='e'&&!e.repeat)mend();});
  function fitBacking(){const scale=document.body.classList.contains('touch-device')?1:2;canvas.width=1000*scale;canvas.height=600*scale;ctx.setTransform(scale,0,0,scale,0,0);dirty=true;}
  window.addEventListener('keyup',e=>{held.delete(e.key.length===1?e.key.toLowerCase():e.key);if(e.key===' ')keyFire=false;});window.addEventListener('blur',()=>{resetInput();if(state.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){resetInput();if(state.mode==='playing')pause();}});window.addEventListener('vibecade:reset-input',resetInput);window.addEventListener('vibecade:restart',e=>{e.preventDefault();restart();});window.addEventListener('resize',()=>{resetInput();fitBacking();});
  function sound(){state.muted=!state.muted;unlockAudio();$('sound').textContent=state.muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(!state.muted));}
  $('sound').onclick=sound;$('pause').onclick=pause;$('restart-button').onclick=restart;$('help-button').onclick=help;$('instruction-close').onclick=closeInstructions;$('place').onclick=place;$('rotate').onclick=rotate;$('launch').onclick=launch;$('mend').onclick=mend;$('next').onclick=()=>begin(state.level+1);$('retry').onclick=()=>{state.score=savedScore;begin(state.level);};$('again').onclick=restart;
  begin(Number(params.get('coast'))||1,false);let seen=false;try{seen=sessionStorage.getItem('harbor-bastion-instructions-v1')==='seen';}catch(_){}if(!seen){state.mode='intro';$('instruction-close').focus();}else $('instruction-modal').classList.remove('is-visible');sync();
  if(test)window.__harborTest={state,profiles,begin,tick,place,rotate,launch,fire,mend,damage,impact,enemyFire,enclosure,shape,draw,finish,nextCannon(){return cannons[cannonIndex%3];},inputs(){return {pointerFire,keyFire,held:[...held]};},manual(value){manual=value;},setCursor(x,y){state.cursor={x,y};dirty=true;},aim(x,y){state.aim={x,y};},render(){fortDirty=true;sync();draw();}};
  fitBacking();
  requestAnimationFrame(animate);
})();
