// A completed-campaign fixture isolates the escape; movement uses only real keys.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'campaign-fixture.json'),'utf8'));fixture.checkpoint={room:29,x:140};fixture.opened=fixture.opened.filter(k=>k!=='2-17');fixture.collected=fixture.collected.filter(k=>!k.startsWith('tank-')||['tank-2','tank-9'].includes(k));const b=await chromium.launch({headless:true,channel:'msedge'}),context=await b.newContext();await context.addInitScript(s=>{localStorage.setItem('hollow-signal-v1',JSON.stringify(s));sessionStorage.setItem('hollow-signal-instructions','seen');},fixture);const page=await context.newPage();try{
 await page.goto('http://127.0.0.1:4173/hollow-signal/?test');await page.addScriptTag({path:path.join(__dirname,'pilot.js')});await page.evaluate(()=>runHollowRoute(0));const report=await page.evaluate(()=>{
  __hollow.manual(true);const pressed=new Set(),key=(c,on)=>{if(pressed.has(c)===on)return;dispatchEvent(new KeyboardEvent(on?'keydown':'keyup',{code:c,bubbles:true}));if(on)pressed.add(c);else pressed.delete(c);},legs=[];key('Digit3',true);key('Digit3',false);
  function walk(x,goalFloor=__hollow.world().floor,max=4200){let frames=0;while(frames<max){const s=__hollow.snapshot(),p=s.p,r=__hollow.world();if(s.mode!=='play')break;const next=hollowNavigate(r,p,x,goalFloor,true),goal=next?next.x+next.w*.5:x;const support=r.platforms.find(a=>!a.ground&&!a.ceiling&&Math.abs(a.y-p.y-p.h)<5&&p.x+p.w>a.x&&p.x<a.x+a.w),drop=next&&next.y>p.y+p.h+40;const movementGoal=drop&&support?(x<p.x?support.x-50:support.x+support.w+50):goal,dir=p.x<movementGoal?1:-1;if(Math.abs(p.x-x)<16&&p.ground&&Math.abs(p.y+p.h-goalFloor)<35)break;const gap=r.hazards.some(h=>h.pit&&(dir>0?h.x>p.x-5&&h.x-p.x<65:h.x+h.w<p.x+5&&p.x-h.x-h.w<65));const spike=r.hazards.some(h=>h.type==='spikes'&&Math.abs(h.x-p.x)<80);key('ArrowRight',dir>0);key('ArrowLeft',dir<0);key('Space',p.ground&&(gap||spike||next&&p.x+170>next.x&&p.x<next.x+next.w+120&&next.y<p.y+p.h-20)||pressed.has('Space')&&p.vy<-20);key('KeyX',frames%60<42);__hollow.step(3,false);frames+=3;}
   for(const c of ['ArrowRight','ArrowLeft','Space','KeyX'])key(c,false);__hollow.step(1,false);return frames/60;
  }
  const consoleObject=__hollow.world().objects.find(o=>o.type==='console');walk(consoleObject.x,consoleObject.y+consoleObject.h);key('KeyE',true);key('KeyE',false);document.querySelector('[data-choice="restore"]').click();if(__hollow.snapshot().mode!=='play')throw new Error('Choice did not resume play');let start=__hollow.snapshot().t,iterations=0;
  while(iterations++<15){const s=__hollow.snapshot(),r=__hollow.world();if(s.mode!=='play')break;if(s.room===0){const ship=r.objects.find(o=>o.type==='ship');walk(ship.x+35);key('KeyE',true);key('KeyE',false);break;}
   const next=__hollow.routeTo(0)[1],e=r.portals.find(p=>p.to===next);if(!e)break;const seconds=walk(e.x+10,e.y+e.h);
   // Shoot any unopened phase seal encountered on the new shortcut.
   if(e.req==='phase'&&!__hollow.snapshot().opened.includes(e.id)){key('ArrowRight',__hollow.snapshot().p.x<e.x+26);key('ArrowLeft',__hollow.snapshot().p.x>=e.x+26);__hollow.step(1,false);key('ArrowRight',false);key('ArrowLeft',false);key('KeyX',true);key('KeyX',false);__hollow.step(30,false);}
   key('KeyE',true);key('KeyE',false);legs.push({from:r.id,to:next,arrived:__hollow.snapshot().room,seconds});
  }
  const s=__hollow.snapshot();__hollow.step(0);return {legs,result:s.mode,complete:s.complete,seconds:s.t-start,remainingIntegrity:s.p.hp,deaths:s.deaths,shortcutOpened:s.opened.includes('2-17')};
 });
 report.deaths=await page.evaluate(()=>__hollow.snapshot().deaths)-fixture.deaths;
 console.log(JSON.stringify(report,null,2));fs.writeFileSync(path.join(__dirname,'escape.json'),JSON.stringify(report,null,2));assert.equal(report.result,'ending');assert(report.complete);assert(report.seconds<720);assert.equal(report.deaths,0);assert(report.shortcutOpened);assert(report.legs.every(l=>l.arrived===l.to));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
