(() => {
 'use strict';
 const W=960,H=540,STEP=1/60,STORE='hollow-signal-v1',world=HollowWorld,canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
 const scale=matchMedia('(max-width:900px)').matches?1:2;canvas.width=W*scale;canvas.height=H*scale;
 const art=window.createHollowArt(ctx,scale),reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
 let mode='instructions',room,p,cam={x:0,y:0},t=0,roomTime=0,manual=false,initialized=false,keys=new Set(),held={fire:false,jump:false},joy=0,joyY=0,prevJump=false,jumpBuffer=0,coyote=0,charge=0,fireHeld=false,pending=null,cooldown=0,weapon=0;
 let powers=new Set(),collected=new Set(),visited=new Set(),opened=new Set(),cleared=new Set(),anchors=new Set(),records=new Set(),sectors=new Set(),checkpoint={room:0,x:150},deaths=0,choice='',escape=0,complete=false,seenOpening=false,elapsed=0,bombChain=0;
 let bullets=[],mines=[],particles=[],drops=[],boss=null,notice='',noticeTime=0,shake=0,flash=0,lastSafe={x:150,y:478},transitionLock=0,saveClock=0,audio=null,muted=false,musicClock=0,bombAutoClock=0;
 const weapons=[{name:'PULSE',color:'#a2eee4',cost:0,damage:4},{name:'SEEKER',color:'#ffc690',cost:6,damage:9},{name:'PHASE',color:'#cfb3ff',cost:3,damage:7},{name:'FROST',color:'#a9dfff',cost:5,damage:6}];
 function maxHP(){return 100+[...collected].filter(x=>x.startsWith('tank-')).length*25+Math.min(4,cleared.size)*10;}
 function ownsWeapon(i){return i===0||powers.has(['','seeker','phase','frost'][i]);}
 function data(){return {v:2,powers:[...powers],collected:[...collected],visited:[...visited],opened:[...opened],cleared:[...cleared],anchors:[...anchors],records:[...records],sectors:[...sectors],checkpoint,deaths,choice,escape,complete,seenOpening,elapsed,weapon};}
 function save(){try{localStorage.setItem(STORE,JSON.stringify(data()));}catch{}}
 function load(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(!s||![1,2].includes(s.v))return;for(const name of ['powers','collected','visited','opened','cleared','anchors','records']){const a=Array.isArray(s[name])?s[name]:[];if(name==='powers')powers=new Set(a.filter(k=>world.powers[k]));else if(name==='collected')collected=new Set(a);else if(name==='visited')visited=new Set(a.filter(n=>world.rooms[n]));else if(name==='opened')opened=new Set(a);else if(name==='cleared')cleared=new Set(a.filter(n=>n>=0&&n<5));else if(name==='anchors')anchors=new Set(a.filter(n=>world.hubs.includes(n)));else records=new Set(a.filter(n=>HollowStory.records[n]));}sectors=new Set(Array.isArray(s.sectors)?s.sectors:[]);checkpoint=world.rooms[s.checkpoint?.room]?s.checkpoint:{room:0,x:150};deaths=s.deaths||0;choice=['restore','sever'].includes(s.choice)?s.choice:'';escape=clamp((s.escape||0)*(s.v===1?4:1),0,720);complete=!!s.complete;seenOpening=!!s.seenOpening;elapsed=s.elapsed||0;weapon=ownsWeapon(s.weapon)?s.weapon:0;}catch{}}
 function audioStart(){if(!audio){const A=window.AudioContext||window.webkitAudioContext;if(A)audio=new A();}audio?.resume();}
 function sound(f=440,d=.09,type='triangle',volume=.035){if(!audio||muted)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,f*.65),audio.currentTime+d);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
 function announce(text,time=3){notice=text;noticeTime=time;}
 function burst(x,y,c,n=14){for(let i=0;i<n&&particles.length<180;i++){const a=i*2.4;particles.push({x,y,vx:Math.cos(a)*(30+i*6),vy:Math.sin(a)*(30+i*5),life:.45+i%4*.1,c,size:2+i%3});}}
 function clearInput(){keys.clear();Object.keys(held).forEach(k=>held[k]=false);joy=joyY=0;if(p)p.aim=false;charge=0;fireHeld=false;pending=null;prevJump=false;jumpBuffer=0;document.querySelectorAll('.pressed').forEach(el=>el.classList.remove('pressed'));}
 function resetInput(){clearInput();dispatchEvent(new Event('vibecade:reset-input'));}
 addEventListener('vibecade:reset-input',clearInput);
 function hideModals(){document.querySelectorAll('.modal').forEach(el=>el.classList.remove('is-visible'));}
 function story(s){resetInput();mode='story';document.querySelector('.signal-portrait').dataset.kind=s.speaker.includes('LIO')?'voice':'tech';document.getElementById('story-speaker').textContent=s.speaker;document.getElementById('story-title').textContent=s.title;const copy=document.getElementById('story-copy');copy.replaceChildren(...s.text.map(text=>{const el=document.createElement('p');el.textContent=text;return el;}));document.getElementById('story-modal').classList.add('is-visible');document.getElementById('story-close').focus();}
 function spawn(x=150,y=room.floor-46){p={x,y,w:28,h:46,vx:0,vy:0,dir:1,hp:maxHP(),energy:100,inv:1.4,ground:false,airJump:false,fold:false,aim:false,lock:0,bombLaunch:0};lastSafe={x,y};cooldown=0;charge=0;fireHeld=false;pending=null;jumpBuffer=0;prevJump=false;coyote=0;}
 function enter(id,from=null,respawn=false){
  resetInput();room=world.build(id);visited.add(id);roomTime=0;boss=null;bullets=[];mines=[];drops=[];particles=[];transitionLock=.45;bombChain=0;bombAutoClock=0;
  for(const z of room.zones){z.open=sectors.has(z.id);if(z.open)for(const e of room.enemies)if(e.zone===z.id)e.dead=true;}
  let x=checkpoint.room===id&&respawn?clamp(checkpoint.x,60,room.w-100):140,y=checkpoint.room===id&&respawn&&Number.isFinite(checkpoint.y)?checkpoint.y:room.floor-46;
  if(from!==null){const exit=room.portals.find(a=>a.to===from);if(exit){x=exit.x+12;y=exit.y+exit.h-46;}}
  if(!p||respawn)spawn(x,y);else{p.x=x;p.y=y;p.vx=p.vy=0;p.ground=false;p.inv=Math.max(p.inv,.8);p.airJump=false;p.fold=false;p.h=46;lastSafe={x,y};}
  cam.x=clamp(p.x-W*.42,0,room.w-W);cam.y=clamp(p.y-H*.56,0,room.h-H+55);announce(world.biomes[room.region].name+' / '+room.name.toUpperCase(),2.7);save();
 }
 function boot(){initialized=true;mode='play';enter(checkpoint.room,null,true);if(!seenOpening){seenOpening=true;save();story(HollowStory.opening);}canvas.focus({preventScroll:true});}
 function help(){if(!initialized)return;resetInput();mode='instructions';document.getElementById('instruction-close').textContent='RETURN TO THE EXPEDITION →';document.getElementById('instruction-modal').classList.add('is-visible');}
 function restart(){if(!initialized)return;hideModals();resetInput();mode='play';if(choice&&!complete&&escape<=0)escape=720;enter(checkpoint.room,null,true);announce('SIGNAL RETURN / DISCOVERIES RETAINED',2.5);}
 function damage(n,dir=0){if(p.inv>0||mode!=='play')return;p.hp-=n;p.inv=1.15;p.vx=dir*210;p.vy=-210;p.lock=.2;shake=reduced?0:6;flash=.14;burst(p.x+14,p.y+20,'#ffc4a0',12);sound(90,.2,'sawtooth');if(p.hp<=0){deaths++;restart();announce('SIGNAL RECOVERED / DISCOVERIES RETAINED',3);save();}}
 function canOpen(e){if(opened.has(e.id)||!e.req)return true;if(e.req==='final')return cleared.has(4);if(e.req==='fold')return powers.has('fold')&&p.fold;if(e.req==='jump')return powers.has('jump');if(e.req==='heat')return powers.has('heat');return false;}
 function unlock(e){if(!opened.has(e.id)){opened.add(e.id);burst(e.x+26,e.y+e.h*.5,world.biomes[room.region].accent,22);announce('SEAL RELEASED / '+world.rooms[e.to].name.toUpperCase(),1.7);sound(570,.18);save();}}
 function fold(){if(!powers.has('fold')){announce('SPINDLE SHELL NOT YET RECOVERED');return;}const h=p.fold?46:24,candidate={x:p.x,y:p.y+p.h-h,w:p.w,h};if(!p.fold||!room.platforms.some(a=>!a.oneway&&hit(candidate,a))){p.y=candidate.y;p.h=h;p.fold=!p.fold;charge=0;fireHeld=false;pending=null;sound(310,.09);}else announce('LOW CLEARANCE / ROLL OUT BEFORE UNFOLDING',1.5);}
 function cycle(){for(let n=1;n<5;n++){const i=(weapon+n)%4;if(ownsWeapon(i)){weapon=i;charge=0;announce(weapons[i].name+' SELECTED',1.2);sound(700,.05);return;}}}
 function acquire(key){if(powers.has(key))return;powers.add(key);collected.add(key);if(key==='phase')weapon=2;if(key==='seeker')weapon=1;if(key==='frost')weapon=3;p.hp=maxHP();p.energy=100;save();sound(800,.25);const v=world.powers[key];story({speaker:'SUIT / RECOVERED TECHNOLOGY',title:v.name,text:[v.copy]});}
 let routeMemo={key:'',path:[]};
 function routeTo(id){if(!room)return[];const key=room.id+'|'+id+'|'+powers.size+'|'+cleared.size;if(key===routeMemo.key)return routeMemo.path;const queue=[[room.id]],seen=new Set([room.id]);let route=[];while(queue.length){const path=queue.shift(),last=path[path.length-1];if(last===id){route=path;break;}for(const e of world.edges){if(e.a!==last&&e.b!==last)continue;if(e.req==='final'&&!cleared.has(4)||e.req&&e.req!=='final'&&!powers.has(e.req))continue;const next=e.a===last?e.b:e.a;if(!seen.has(next)){seen.add(next);queue.push([...path,next]);}}}routeMemo={key,path:route};return route;}
 function objective(){if(complete)return {id:0,text:'Explore Nacre. Recover every witness record and suit cache.'};if(choice){const route=routeTo(0);return{id:0,text:room.id===0?'ESCAPE / Board your ship and launch.':'SURFACE ROUTE / NEXT: '+(world.rooms[route[1]]?.name||'Surface Beacon')+'. Atlas marks the return path.'};}for(const [key,id,text] of [['lens',3,'Find the Resonance Lens in the eastern Tideglass Vault.'],['fold',4,'Use a charged shot on the Crypt seal. Recover the Shellkeeper’s core.'],['bomb',8,'Roll into the Pulse Nursery in the Underworks.'],['jump',10,'Mine the amber seals. Face the Root Matron beneath the canopy.'],['phase',16,'Ascend to the Archives. Find the Ray Reliquary beyond Memory Well.'],['heat',22,'Follow the Engine’s Cooling Spine to the Furnace Crown.']])if(!powers.has(key))return{id,text};if(!cleared.has(4))return{id:28,text:'Descend through Thermal Sump. Silence the Custodian at the Living Heart.'};return{id:29,text:'Visit the western Severance Console. Hear Lio, then choose.'};}
 function context(){if(!p||mode!=='play')return null;let found=null,dist=110;
  for(const a of [...room.objects,...room.portals.map(e=>({...e,type:'portal'}))]){if(a.type==='tank'||(a.type==='power'&&powers.has(a.power))||(a.type==='record'&&records.has(a.record)))continue;const d=Math.hypot(a.x+a.w/2-p.x-14,(a.y+a.h*.65)-(p.y+p.h*.65));if(d<dist){dist=d;found=a;}}return found;
 }
 function interact(){const a=context();if(!a){cycle();return;}
  if(a.type==='portal'){
   if(boss&&boss.hp>0){announce('GUARDIAN FIELD / DEFEAT THE DEFENDER FIRST',1.8);return;}
   if(!canOpen(a)){const hint={lens:'CHARGE A PULSE AT THIS CYAN SEAL',fold:'FOLD INTO SPINDLE TO ENTER',bomb:'FOLD, THEN FIRE A PULSE MINE HERE',jump:'WING COIL REQUIRED / SECOND JUMP',phase:'SHOOT THIS SEAL WITH THE PHASE BEAM',heat:'THERMAL MANTLE REQUIRED',final:'THE CUSTODIAN STILL CONTROLS THIS CIRCUIT'};announce(hint[a.req],2.5);sound(130,.09);return;}
   const from=room.id;enter(a.to,from);return;
  }
  if(a.type==='power'){acquire(a.power);return;}
  if(a.type==='record'){records.add(a.record);collected.add(a.id);save();sound(650,.12);story(HollowStory.records[a.record]);return;}
  if(a.type==='sign'){announce(a.text,4);return;}
  if(a.type==='relay'){checkpoint={room:room.id,x:a.x+45,y:p.y+p.h-46};p.energy=100;save();announce('LOCAL RELAY / CHECKPOINT RECORDED / SECTORS STAY CLEAR',2.8);sound(580,.15);return;}
  if(a.type==='pod'){anchors.add(room.id);checkpoint={room:room.id,x:a.x+5,y:room.floor-46};p.hp=maxHP();p.energy=100;save();announce('SANCTUARY LINKED / HEALED & SAVED / ATLAS TO TRAVEL',2.8);sound(740,.2);return;}
  if(a.type==='console'){if(!cleared.has(4)){announce('THE CUSTODIAN HOLDS THIS CIRCUIT');return;}if(complete){announce('YOUR CHOICE IS PRESERVED IN THE WITNESS ARCHIVE');return;}resetInput();mode='choice';document.getElementById('choice-modal').classList.add('is-visible');return;}
  if(a.type==='ship'){if(choice&&!complete)finish();else announce('SHIP ON STANDBY / FOLLOW THE SIGNAL BELOW',2);}
 }
 function beginFire(){if(mode!=='play'||fireHeld)return;fireHeld=true;charge=0;pending=null;}
 function endFire(cancel=false){if(!fireHeld)return;pending=cancel?null:charge;fireHeld=false;charge=0;}
 function fire(full=false){if(cooldown>0)return;if(p.fold){if(!powers.has('bomb')){announce('PULSE MINE NOT YET RECOVERED',1.3);return;}if(mines.length<4)mines.push({x:p.x+14,y:p.y+p.h-5,timer:.6,r:110});cooldown=.3;bombAutoClock=.65;sound(240,.08);return;}
  if(p.energy<weapons[weapon].cost){weapon=0;announce('ENERGY LOW / PULSE SELECTED',1);}
  const w=weapons[weapon],aim=p.aim,axis=Math.abs(p.vx)>35,dx=aim?(axis?p.dir*.707:0):p.dir,dy=aim?(axis?-.707:-1):0,speed=weapon===1?400:weapon===2?860:710;
  p.energy-=w.cost;bullets.push({x:p.x+14+dx*24,y:p.y+20+dy*20,vx:dx*speed,vy:dy*speed,w:full?26:12,h:full?22:9,life:2,owner:'player',weapon,damage:w.damage*(full?[4,2.5,3.5,3.5][weapon]:1),full,color:w.color,hits:[]});cooldown=full?.25:.18;sound(full?140:weapon===3?670:460,full?.2:.055,'triangle');burst(p.x+14+dx*28,p.y+20+dy*20,w.color,full?10:3);if(full)shake=reduced?0:2;
 }
 function enemyShot(x,y,vx,vy,size=12){if(bullets.length>180)return;bullets.push({x,y,vx,vy,w:size,h:size,life:5,owner:'enemy',damage:8+room.region*2,color:world.biomes[room.region].accent});}
 function aimShot(x,y,speed,spread=0){const a=Math.atan2(p.y+p.h*.5-y,p.x+14-x);for(let n=-spread;n<=spread;n++){const angle=a+n*.23;enemyShot(x,y,Math.cos(angle)*speed,Math.sin(angle)*speed);}}
 function makeBoss(){const i=room.boss;boss={index:i,x:room.w-290,y:room.floor-108,w:i===4?142:110,h:108,hp:[150,210,290,380,700][i],max:[150,210,290,380,700][i],phase:'wait',timer:1.15,cycle:0,pattern:0,vx:0,vy:0,inv:0,shotClock:.6,elapsed:0,mark:p.x,enraged:false};checkpoint={room:room.id,x:room.arena.x+85,y:room.floor-46};p.hp=maxHP();p.energy=100;room.enemies=[];bullets=bullets.filter(b=>b.owner==='player');announce(world.bossNames[i]+' / READ THE TELL, STRIKE THE RECOVERY',3);save();}
 function moveBoss(x,y,dt,speed){const dx=x-boss.x,dy=y-boss.y,len=Math.hypot(dx,dy);if(len<=speed*dt){boss.x=x;boss.y=y;}else{boss.x+=dx/len*speed*dt;boss.y+=dy/len*speed*dt;}}
 function bossWin(){const i=boss.index;cleared.add(i);burst(boss.x+55,boss.y+55,world.biomes[room.region].accent,42);boss.hp=0;bullets=bullets.filter(b=>b.owner==='player');p.hp=maxHP();p.energy=100;sound(110,.6,'sine');const key=['fold','jump','phase','heat'][i];if(key){powers.add(key);collected.add(key);if(key==='phase')weapon=2;const scene=HollowStory[key],tech=world.powers[key];story({...scene,text:[...scene.text,tech.name+' — '+tech.copy]});}else story(HollowStory.final);save();}
 function updateBoss(dt){if(room.boss===undefined||cleared.has(room.boss))return;if(!boss){if(p.x>room.arena.x+180)makeBoss();return;}const b=boss,i=b.index,floor=room.floor-b.h,left=room.arena.x,right=room.w,width=room.arena.w;b.inv=Math.max(0,b.inv-dt);b.timer-=dt;
  if(b.hp<b.max*.4&&!b.enraged){b.enraged=true;announce(world.bossNames[i]+' / QUARANTINE OVERDRIVE',1.8);sound(100,.2,'sawtooth');}
  const fast=b.enraged?1.18:1;
  if(b.phase==='wait'){if(b.timer<=0){b.phase='tell';b.timer=b.enraged?.65:.85;b.pattern=(b.cycle+i)%4;b.mark=clamp(p.x,left+160,right-160);b.attackName=['GROUND SWEEP','MARKED VAULT','ORBITAL VOLLEY','FALLING SIGNAL'][b.pattern];announce(b.attackName+' / '+(['JUMP OR PASS BEHIND','MOVE AWAY FROM THE MARK','FOLLOW THE GAP','LEAVE THE LIT COLUMNS'][b.pattern]),2);}}
  else if(b.phase==='tell'){if(b.timer<=0){b.phase='attack';b.duration=(b.pattern===0?(i===3?3.5:2.1):2.8)/fast;b.timer=b.duration;b.elapsed=0;b.originX=b.x;b.originY=b.y;b.destination=b.x>left+width*.5?left+160:right-250;b.shotClock=.48;b.sent=false;b.cycle++;}}
  else if(b.phase==='attack'){b.elapsed+=dt;const u=clamp(b.elapsed/b.duration,0,1),oldX=b.x,oldY=b.y;
   if(b.pattern===0){moveBoss(i===3&&u>.5?b.originX:b.destination,floor,dt,(i===3?620:300+i*55)*fast);if(i>=2&&!b.sent&&u>.35){b.sent=true;for(const dir of [-1,1])enemyShot(b.x+55,room.floor-17,dir*265,0,15);}}
   else if(b.pattern===1){moveBoss(b.originX+(b.mark-b.originX)*u,floor-Math.sin(u*Math.PI)*(175+i*10),dt,510*fast);}
   else if(b.pattern===2){const a=(b.originX>left+width*.5?0:Math.PI)+u*Math.PI*2;moveBoss(left+width*.5+Math.cos(a)*(width*.34),floor-145+Math.sin(a)*120,dt,(380+i*40)*fast);}
   else{moveBoss(b.destination,floor-180,dt,350*fast);if(!b.sent&&u>.22){b.sent=true;for(let n=-1;n<=1+(i>=3?1:0);n++)enemyShot(clamp(b.mark+n*115,left+120,right-100),room.floor-390,0,300+i*20,15);}}
   b.vx=(b.x-oldX)/dt;b.vy=(b.y-oldY)/dt;b.shotClock-=dt;
   if(b.shotClock<=0){b.shotClock=(i<2?1.05:i===4?.65:.85)/fast;if(b.pattern===2||b.pattern===1)aimShot(b.x+55,b.y+48,220+i*18,i>=2?1:0);if(i===1&&b.pattern===1)for(const dir of [-1,1])enemyShot(b.x+55,room.floor-15,dir*220,0,13);if(i===4&&b.pattern===3)aimShot(b.x+70,b.y+55,285,1);}
   if(u>=1){b.phase='recover';b.timer=b.enraged?.9:1.3;b.vx=b.vy=0;}
  }else if(b.phase==='recover'){moveBoss(b.x,floor,dt,320);if(b.timer<=0){b.phase='wait';b.timer=.6;}}
  b.x=clamp(b.x,left+130,right-180);b.y=clamp(b.y,room.floor-420,floor);
  if(hit(p,{x:b.x+14,y:b.y+14,w:b.w-28,h:b.h-14}))damage(10+i*2,p.x<b.x?-1:1);
 }
 function simulate(dt){if(mode!=='play')return;t+=dt;roomTime+=dt;elapsed+=dt;saveClock+=dt;noticeTime=Math.max(0,noticeTime-dt);shake=Math.max(0,shake-dt*25);flash=Math.max(0,flash-dt);transitionLock=Math.max(0,transitionLock-dt);cooldown=Math.max(0,cooldown-dt);p.inv=Math.max(0,p.inv-dt);p.lock=Math.max(0,p.lock-dt);p.energy=Math.min(100,p.energy+dt*10);
  bombAutoClock=Math.max(0,bombAutoClock-dt);if(escape>0){escape-=dt;if(escape<=0){escape=720;deaths++;checkpoint={room:29,x:6800,y:world.rooms[29].h-76-146};restart();announce('SURFACE WINDOW RESET / TRY THE OPENED RETURN ROUTE',4);return;}if(saveClock>8){saveClock=0;save();}}
  musicClock+=dt;if(musicClock>.52){musicClock=0;const notes=[82.41,123.47,164.81,110,98,146.83,196,123.47];sound(notes[(Math.floor(t/.52)+room.region)%8],.4,'sine',.012);}
  // Joystick vertical input requests a form, rather than toggling every frame.
  if(powers.has('fold')&&(joyY>.4&&!p.fold||joyY<-.4&&p.fold)){const wasFolded=p.fold;fold();if(p.fold!==wasFolded&&held.fire)beginFire();}
  const axis=keys.has('ArrowLeft')||keys.has('KeyA')?-1:keys.has('ArrowRight')||keys.has('KeyD')?1:joy,jump=held.jump||keys.has('Space')||keys.has('KeyZ');p.aim=joyY<-.35||keys.has('ArrowUp')||keys.has('KeyW');
  if(jump&&!prevJump)jumpBuffer=.13;else jumpBuffer=Math.max(0,jumpBuffer-dt);if(p.ground)coyote=.1;else coyote=Math.max(0,coyote-dt);
  if(jumpBuffer>0&&(coyote>0||powers.has('jump')&&!p.airJump&&!p.fold)){const second=coyote<=0;p.vy=p.fold?-430:-630;p.ground=false;coyote=0;jumpBuffer=0;if(second)p.airJump=true;burst(p.x+14,p.y+p.h,second?'#cfb8ff':'#acd6d3',second?13:5);sound(second?600:320,.08);}
  if(!jump&&prevJump&&p.vy<-230)p.vy=-230;prevJump=jump;
  if(p.lock<=0){p.vx+=(axis*(p.fold?310:250)-p.vx)*Math.min(1,dt*(p.ground?21:11));if(Math.abs(axis)>.13)p.dir=axis>0?1:-1;}p.vy=Math.min(780,p.vy+1350*dt);
  const oldRoom=room.id;for(const a of room.platforms)if(a.moving){const old=a.y;a.y=a.base+Math.sin(t*1.4+a.phase)*45;if(p.ground&&p.x+p.w>a.x&&p.x<a.x+a.w&&Math.abs(p.y+p.h-old)<3)p.y+=a.y-old;}
  const solids=[...room.platforms,...room.zones.filter(z=>!z.open)];
  p.x+=p.vx*dt;for(const a of solids){if(a.oneway||!hit(p,a))continue;if(p.vx>0)p.x=a.x-p.w;else if(p.vx<0)p.x=a.x+a.w;p.vx=0;}p.x=clamp(p.x,5,room.w-p.w-5);
  const bottom=p.y+p.h;p.y+=p.vy*dt;p.ground=false;const frozen=room.enemies.filter(e=>!e.dead&&e.frozen>0).map(e=>({x:e.x,y:e.y,w:e.w,h:e.h,oneway:true}));
  for(const a of [...solids,...frozen]){if(!hit(p,a))continue;if(p.vy>=0&&bottom<=a.y+9){p.y=a.y-p.h;p.vy=0;p.ground=true;p.airJump=false;}else if(!a.oneway&&p.vy<0){p.y=a.y+a.h;p.vy=0;}}
  if(p.ground)bombChain=0;p.bombLaunch=Math.max(0,(p.bombLaunch||0)-dt);
  if(p.ground&&!room.hazards.some(h=>hit({x:p.x,y:p.y+p.h-12,w:p.w,h:14},h)))lastSafe={x:p.x,y:p.y};
  if(p.y>room.h+100){p.inv=0;damage(12);if(room.id!==oldRoom)return;p.x=lastSafe.x;p.y=lastSafe.y;p.vx=p.vy=0;}
  for(const h of room.hazards)if(!h.pit&&hit(p,h)&&!(h.type==='heat'&&powers.has('heat')))damage(h.type==='heat'?14:10,-p.dir);
  if(pending!==null&&cooldown<=0){fire(pending>=.65&&powers.has('lens'));pending=null;}
  if(fireHeld){if(p.fold&&powers.has('bomb')){charge=0;if(bombAutoClock<=0)fire(false);}else{const old=charge;charge=Math.min(1.2,charge+dt);if(powers.has('lens')&&old<.65&&charge>=.65)sound(820,.09);}}
  for(const o of room.objects)if(o.type==='tank'&&!collected.has(o.id)&&hit(p,o)){collected.add(o.id);p.hp=maxHP();save();announce('SUIT RESERVE / MAX INTEGRITY +25',2.6);burst(o.x,o.y,'#ffe1ad',20);sound(780,.22);}
  for(const e of room.enemies){if(e.dead)continue;e.frozen=Math.max(0,e.frozen-dt);e.hint=Math.max(0,(e.hint||0)-dt);e.exposed=Math.max(0,(e.exposed||0)-dt);if(e.frozen>0||Math.abs(e.x-p.x)>1250)continue;e.timer-=dt;
   if(e.type==='crawler'){const nx=e.x+e.dir*(45+room.region*7)*dt;if(room.hazards.some(h=>h.pit&&nx+e.w>h.x&&nx<h.x+h.w))e.dir*=-1;else e.x=nx;if(Math.abs(e.x-e.home)>90)e.dir*=-1;}
   if(e.type==='moth'){e.x=e.home+Math.sin(t*1.05+e.phase)*100;e.y=e.groundY-165+Math.sin(t*2+e.phase)*65;}
   if(e.type==='leaper'){e.vy+=1350*dt;e.y+=e.vy*dt;e.x=clamp(e.x+e.vx*dt,e.home-100,e.home+100);if(e.y>=e.groundY-e.h){e.y=e.groundY-e.h;e.vy=0;e.vx=0;if(e.timer<=0){e.vy=-480;e.vx=p.x<e.x?-120:120;e.timer=2.5;e.exposed=1.1;}}}
   if(e.timer<=0&&Math.abs(e.x-p.x)<750){e.timer=3.1-room.region*.2;e.exposed=1.1;if(e.type!=='leaper')aimShot(e.x+e.w*.5,e.y+15,175+room.region*20,e.armor==='phase'&&room.region>=3?1:0);}
   if(hit(p,{x:e.x+6,y:e.y+6,w:e.w-12,h:e.h-6}))damage(6+room.region*2,p.x<e.x?-1:1);
  }
  updateBoss(dt);if(room.id!==oldRoom||mode!=='play')return;
  for(const m of mines){m.timer-=dt;if(m.timer<=0){burst(m.x,m.y,'#ffd39b',26);sound(100,.18,'sawtooth');shake=reduced?0:3;const dx=p.x+14-m.x,dy=p.y+p.h-m.y;if(p.fold&&Math.abs(dx)<62&&dy<32&&dy>-235){p.vy=-760;p.ground=false;coyote=0;jumpBuffer=0;p.bombLaunch=.25;bombChain++;burst(p.x+14,p.y+p.h,'#b6fff0',15);sound(480,.13);if(bombChain===2)announce('BLAST CHAIN / KEEP OVER YOUR MINES',1.8);}for(const e of room.enemies)if(!e.dead&&Math.hypot(e.x+e.w*.5-m.x,e.y+e.h*.5-m.y)<m.r+12)hurtEnemy(e,{damage:42,weapon:'mine',full:true,color:'#ffd39b'});if(boss&&boss.hp>0&&Math.hypot(boss.x+55-m.x,boss.y+60-m.y)<m.r+20&&boss.inv<=0){boss.hp-=14;boss.inv=.18;if(boss.hp<=0)bossWin();}for(const gate of room.portals)if(gate.req==='bomb'&&Math.hypot(gate.x+26-m.x,gate.y+gate.h*.6-m.y)<m.r)unlock(gate);}}
  mines=mines.filter(m=>m.timer>0);
  for(const b of bullets){b.life-=dt;if(b.owner==='player'&&b.weapon===1){const targets=[...room.enemies.filter(e=>!e.dead),...(boss&&boss.hp>0?[boss]:[])];let target=targets.sort((a,c)=>Math.hypot(a.x-b.x,a.y-b.y)-Math.hypot(c.x-b.x,c.y-b.y))[0];if(target){const angle=Math.atan2(target.y+target.h*.5-b.y,target.x+target.w*.5-b.x);b.vx+=(Math.cos(angle)*430-b.vx)*dt*3;b.vy+=(Math.sin(angle)*430-b.vy)*dt*3;}}
   const origin={x:b.x,y:b.y,w:b.w,h:b.h};b.x+=b.vx*dt;b.y+=b.vy*dt;
   if(b.owner==='enemy'){if(hit(p,b)){damage(b.damage,b.vx>0?1:-1);b.life=0;}}
   else{
    for(const gate of room.portals)if((hit(b,gate)||hit(origin,gate))&&((gate.req==='lens'&&b.full)||(gate.req==='phase'&&b.weapon===2))){unlock(gate);b.life=0;}
    for(const e of room.enemies){if(e.dead||b.hits.includes(e.id)||!hit(b,e))continue;hurtEnemy(e,b);b.hits.push(e.id);if(b.weapon!==2)b.life=0;}
    if(boss&&boss.hp>0&&boss.inv<=0&&!b.hits.includes('boss')&&hit(b,boss)){const weak=[0,0,1,3,2][boss.index];boss.hp-=b.damage*(b.weapon===weak?1.25:1);boss.inv=.15;b.hits.push('boss');burst(b.x,b.y,b.color,8);if(b.weapon!==2)b.life=0;if(boss.hp<=0)bossWin();}
   }
   if(room.platforms.some(a=>!a.oneway&&hit(b,a)))b.life=0;
  }
  bullets=bullets.filter(b=>b.life>0&&b.x>-200&&b.x<room.w+200&&b.y>-100&&b.y<room.h+100);
  for(const d of drops){d.life-=dt;d.vy+=700*dt;d.y=Math.min(room.floor-d.h,d.y+d.vy*dt);if(hit(p,d)){p.hp=Math.min(maxHP(),p.hp+12);p.energy=Math.min(100,p.energy+18);d.life=0;sound(740,.05);}}drops=drops.filter(d=>d.life>0);
  cam.x+=(clamp(p.x-W*.43,0,room.w-W)-cam.x)*Math.min(1,dt*8);cam.y+=(clamp(p.y-H*.58,0,room.h-H+55)-cam.y)*Math.min(1,dt*8);
  const action=context();document.getElementById('touch-use').textContent=action?({portal:canOpen(action)?'ENTER':'SEALED',pod:'SAVE',relay:'CHECKPOINT',sign:'HINT',record:'READ',power:'CLAIM',console:'CHOOSE',ship:choice?'LAUNCH':'SHIP'}[action.type]):'WEAPON';
 }
 function hurtEnemy(e,b){let mult=1;const armor=e.armor||'plain',mine=b.weapon==='mine';if(armor==='phase'&&b.weapon!==2)mult=0;else if(armor==='crust')mult=mine?1.3:0;else if(armor==='carapace'&&!mine&&b.weapon!==1&&b.weapon!==3&&!b.full&&!e.exposed)mult=.15;else if(armor==='carapace'&&b.full)mult=1.4;if(armor==='phase'&&b.weapon===2)mult=1.5;if(mult<.2&&!e.hint){e.hint=3;announce(({phase:'PHASE ARMOR / SWITCH TO THE PHASE BEAM',crust:'MINERAL CRUST / FOLD AND PLACE MINES',carapace:'CARAPACE / CHARGE, MINE, OR STRIKE THE OPEN VENT'})[armor],2.5);}e.hp-=b.damage*mult;if(b.weapon===3&&mult>0)e.frozen=2.6;burst(e.x+e.w*.5,e.y+e.h*.5,mult<.2?'#9facbf':b.color,mult<.2?3:6);if(e.hp<=0)kill(e);}
 function kill(e){if(e.dead)return;e.dead=true;burst(e.x+e.w*.5,e.y+e.h*.5,world.biomes[room.region].accent,18);drops.push({x:e.x+6,y:e.y,w:22,h:22,vy:-140,life:14});sound(125,.12);const z=room.zones.find(z=>z.id===e.zone);if(z&&!z.open&&z.guards.every(id=>room.enemies.find(e=>e.id===id)?.dead)){z.open=true;sectors.add(z.id);announce(z.title+' / SECTOR RELEASED / RELAY AHEAD',2.7);sound(650,.2);save();}}
 function effects(dt){for(const a of particles){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=100*dt;}particles=particles.filter(a=>a.life>0);}
 function atlas(){if(!initialized)return;resetInput();mode='atlas';document.getElementById('atlas-modal').classList.add('is-visible');renderAtlas();}
 function renderAtlas(){
  const svg=document.getElementById('world-map'),NS='http://www.w3.org/2000/svg';svg.replaceChildren();const add=(tag,attrs,text)=>{const el=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);if(text)el.textContent=text;svg.append(el);return el;},coords=r=>({x:25+r.grid[0]*90,y:32+r.grid[1]*82}),goal=objective(),route=routeTo(goal.id);const known=new Set(visited);for(const e of world.edges)if(visited.has(e.a)||visited.has(e.b)){known.add(e.a);known.add(e.b);}for(const id of route)known.add(id);known.add(goal.id);
  for(let i=0;i<route.length-1;i++){const a=coords(world.rooms[route[i]]),b=coords(world.rooms[route[i+1]]);add('line',{x1:a.x+38,y1:a.y+26,x2:b.x+38,y2:b.y+26,stroke:'#d4db9c55','stroke-width':9});}
  for(const e of world.edges){if(!known.has(e.a)||!known.has(e.b))continue;const a=coords(world.rooms[e.a]),b=coords(world.rooms[e.b]),open=!e.req||opened.has(e.id)||(['fold','jump','heat'].includes(e.req)&&powers.has(e.req))||(e.req==='final'&&cleared.has(4));add('line',{x1:a.x+38,y1:a.y+26,x2:b.x+38,y2:b.y+26,stroke:open?'#60818e':'#b17d66','stroke-width':e.shortcut?2:3,'stroke-dasharray':e.shortcut?'5 5':open?'0':'3 4'});if(e.req&&!open)add('text',{x:(a.x+b.x)/2+38,y:(a.y+b.y)/2+22,fill:'#ffdc9b','font-size':13,'text-anchor':'middle'},({lens:'C',fold:'S',bomb:'B',jump:'W',phase:'P',heat:'T',final:'◆'})[e.req]);}
  for(const id of known){const r=world.rooms[id],c=coords(r),seen=visited.has(id),col=world.biomes[r.region].accent;add('rect',{x:c.x,y:c.y,width:78,height:53,rx:9,fill:seen?world.biomes[r.region].stone:'#122633',stroke:id===room.id?'#fff0c6':seen?col:'#48616c','stroke-width':id===room.id?3:1});const words=(seen?r.name:'UNEXPLORED').split(' ');add('text',{x:c.x+39,y:c.y+23,fill:seen?'#eff7f3':'#8bafb7','font-size':10,'text-anchor':'middle'},words[0]);add('text',{x:c.x+39,y:c.y+37,fill:seen?'#eff7f3':'#8bafb7','font-size':9,'text-anchor':'middle'},words.slice(1).join(' '));if(r.hub)add('text',{x:c.x+8,y:c.y+15,fill:col,'font-size':13},'◇');if(id===goal.id)add('text',{x:c.x+64,y:c.y+15,fill:'#ffe1a2','font-size':13},'★');if(id===room.id)add('circle',{cx:c.x+39,cy:c.y+7,r:3,fill:'#fff4cb'});}
  document.getElementById('atlas-objective').textContent=goal.text+'  •  '+visited.size+'/30 chambers · '+records.size+'/8 witnesses';
  const travels=document.getElementById('travel-list');travels.replaceChildren();for(const id of anchors){const b=document.createElement('button');b.textContent='◇ '+world.rooms[id].name;b.disabled=!!escape||!!(boss&&boss.hp>0);b.title=escape?'Network disabled during escape':boss&&boss.hp>0?'Guardian field blocks travel':'Travel to linked sanctuary';b.onclick=()=>{hideModals();mode='play';checkpoint={room:id,x:160};enter(id,null,true);};travels.append(b);}
  const inv=document.getElementById('inventory');inv.replaceChildren(...[...powers].map(key=>{const el=document.createElement('span');el.textContent=world.powers[key].name;return el;}));document.getElementById('journal-count').textContent=`Witness journal — ${records.size}/8 recovered`;
  const j=document.getElementById('journal');j.replaceChildren();for(const id of [...records].sort()){const s=HollowStory.records[id],el=document.createElement('p');const b=document.createElement('b');b.textContent=s.title;el.append(b,document.createElement('br'),s.text[0]);j.append(el);}if(!records.size)j.textContent='Read witness terminals to preserve the colony’s account.';
 }
 function finish(){complete=true;escape=0;save();resetInput();mode='ending';const restore=choice==='restore';document.getElementById('ending-tag').textContent=restore?'ENDING / THE ANSWERING HOME':'ENDING / THE WITNESS SHIP';document.getElementById('ending-title').textContent=restore?'The light answers.':'You carry their names.';const texts=restore?['Your ship clears the ice as the surface beacons bloom. Below, the Chorus steadies. Lio’s voice reaches the receiver without the old distortion.','“I am still here, Ari. Come back when you can.” You set a return frequency, and this time you know someone will answer.']:['The quarantine channel goes quiet. The beacons launch the colony’s last account into the dark. Nacre will no longer draw another ship into the Custodian’s trap.','You carry the voices you recovered beyond Pelagos. At the end of Lio’s last record is a laugh you remember from home. You keep it.'];texts.push(`Witnesses preserved: ${records.size}/8. Chambers explored: ${visited.size}/30. Suit reserves: ${maxHP()}. Signal recoveries: ${deaths}.`);document.getElementById('ending-copy').replaceChildren(...texts.map(v=>{const el=document.createElement('p');el.textContent=v;return el;}));document.getElementById('ending-modal').classList.add('is-visible');}
 function draw(){ctx.setTransform(scale,0,0,scale,0,0);ctx.imageSmoothingEnabled=true;ctx.lineJoin='round';if(!room){art.title(t);return;}const view={room,p,powers,weapon:weapons[weapon],cam,t,charge,boss,escape,reduced,opened,cleared,canOpen};const visible=a=>a.x+a.w>cam.x-120&&a.x<cam.x+W+120&&a.y+a.h>cam.y-150&&a.y<cam.y+H+150;ctx.save();if(shake&&!reduced)ctx.translate(Math.sin(t*51)*shake*.45,Math.cos(t*43)*shake*.25);art.background(view);ctx.save();ctx.translate(-cam.x,-cam.y);art.terrain(view);for(const e of room.portals)if(visible(e))art.portal(e,view);for(const o of room.objects)if(visible(o)&&!(o.type==='tank'&&collected.has(o.id))&&!(o.type==='power'&&powers.has(o.power)))art.object(o,view,records.has(o.record));for(const e of room.enemies)if(!e.dead&&visible(e))art.enemy(e,view);if(boss&&boss.hp>0)art.boss(boss,view);for(const m of mines)art.mine(m,view);for(const d of drops)if(visible(d))art.drop(d,view);for(const b of bullets)if(visible(b))art.bullet(b,view);if(p.inv<=0||Math.floor(t*14)%2===0)art.hero(p,view);for(const a of particles)art.particle(a);art.warnings(view);ctx.restore();ctx.restore();art.hud({p,max:maxHP(),weapon:weapons[weapon],room,visited,records,notice,noticeTime,escape,goal:objective(),context:context(),boss,t,powers,charge,mobile:document.body.classList.contains('touch-device')});if(flash>0){ctx.fillStyle='#ffc7a322';ctx.fillRect(0,56,W,H-56);}}
 document.getElementById('instruction-close').onclick=()=>{audioStart();try{sessionStorage.setItem('hollow-signal-instructions','seen');}catch{}hideModals();if(!initialized)boot();else{mode='play';canvas.focus();}};
 document.getElementById('story-close').onclick=()=>{hideModals();mode='play';canvas.focus();};document.getElementById('help-button').onclick=help;document.getElementById('map-button').onclick=atlas;document.getElementById('atlas-close').onclick=()=>{hideModals();mode='play';canvas.focus();};function toggleSound(){muted=!muted;for(const id of ['sound-button','atlas-sound'])document.getElementById(id).textContent=muted?'SOUND OFF':'SOUND ON';audioStart();}document.getElementById('sound-button').onclick=toggleSound;document.getElementById('atlas-sound').onclick=toggleSound;
 let confirmNew=false;document.getElementById('new-game').onclick=()=>{if(!confirmNew){confirmNew=true;document.getElementById('new-game').textContent='CONFIRM: ERASE EXPEDITION & BEGIN AGAIN';return;}powers.clear();collected.clear();visited.clear();opened.clear();cleared.clear();anchors.clear();records.clear();sectors.clear();checkpoint={room:0,x:150};deaths=0;choice='';escape=0;complete=false;seenOpening=false;elapsed=0;weapon=0;p=null;save();confirmNew=false;hideModals();audioStart();boot();};
 document.querySelectorAll('[data-choice]').forEach(el=>el.onclick=()=>{choice=el.dataset.choice;escape=720;checkpoint={room:29,x:6800,y:room.floor-146};save();hideModals();mode='play';announce((choice==='restore'?'CHORUS RESTORED':'LINK SEVERED')+' / 12 MINUTES TO THE SURFACE BEACON',4);sound(100,.4);});
 document.getElementById('ending-explore').onclick=()=>{hideModals();mode='play';checkpoint={room:0,x:150};enter(0,null,true);};
 addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','Tab'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Escape'){if(mode==='play')help();else if(mode==='atlas')document.getElementById('atlas-close').click();return;}if(mode!=='play')return;keys.add(e.code);if(['KeyX','KeyJ'].includes(e.code))beginFire();if(['ArrowDown','KeyS'].includes(e.code))fold();if(e.code==='KeyE')interact();if(e.code==='KeyQ')cycle();if(e.code==='Tab')atlas();if(e.code==='KeyR')restart();if(e.code==='KeyM')document.getElementById('sound-button').click();if(/^Digit[1-4]$/.test(e.code)){const i=+e.code.slice(5)-1;if(ownsWeapon(i)){weapon=i;charge=0;}}});
 addEventListener('keyup',e=>{keys.delete(e.code);if(['KeyX','KeyJ'].includes(e.code)&&!keys.has('KeyX')&&!keys.has('KeyJ')&&!held.fire)endFire();});addEventListener('blur',()=>{resetInput();if(mode==='play')help();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='play')help();});addEventListener('vibecade:restart',e=>{e.preventDefault();restart();});
 document.querySelectorAll('[data-action]').forEach(button=>{const action=button.dataset.action;button.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='play')return;audioStart();try{button.setPointerCapture(e.pointerId);}catch{}button.classList.add('pressed');if(action==='fold')fold();else if(action==='map')atlas();else if(action==='use')interact();else{held[action]=true;if(action==='fire')beginFire();}});for(const kind of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(kind,e=>{e.preventDefault();held[action]=false;if(action==='fire'&&!keys.has('KeyX')&&!keys.has('KeyJ'))endFire(kind!=='pointerup');button.classList.remove('pressed');});});
 function joystick(){window.VibeCadeJoystick(document.querySelector('[data-joystick]'),{mode:'analog',profile:'precision',onChange:(x,y)=>{joy=x;joyY=y;}});}if(window.VibeCadeJoystick)joystick();else addEventListener('vibecade-controls-ready',joystick,{once:true});
 load();try{if(sessionStorage.getItem('hollow-signal-instructions')==='seen'){hideModals();boot();}}catch{}
 if(new URLSearchParams(location.search).has('test'))window.__hollow={manual:v=>manual=v,start:()=>{hideModals();seenOpening=true;boot();},snapshot:()=>({mode,t,elapsed,room:room?.id,p:p?{...p}:null,boss:boss?{...boss}:null,powers:[...powers],collected:[...collected],visited:[...visited],opened:[...opened],cleared:[...cleared],anchors:[...anchors],records:[...records],checkpoint:{...checkpoint},deaths,choice,escape,complete,weapon,charge,held:{...held},joy,bullets:bullets.length,maxHP:maxHP(),goal:objective()}),step:(n,render=true)=>{for(let i=0;i<n;i++){simulate(STEP);if(mode==='play')effects(STEP);}if(render)draw();},enter:id=>enter(id,null,true),warp:(x,y=room.floor-p.h)=>{p.x=x;p.y=y;p.vx=p.vy=0;cam.x=clamp(x-W*.4,0,room.w-W);cam.y=clamp(y-H*.6,0,room.h-H+55);},setPlayer:v=>Object.assign(p,v),setBoss:v=>boss&&Object.assign(boss,v),world:()=>room,routeTo,graph:()=>world.edges,rooms:()=>world.rooms,bullets:()=>bullets,grant:key=>powers.add(key),acquire,select:i=>weapon=i,shoot:fire,interact,damage,save,data,atlas,finish};
 if(window.__hollow){const previous=__hollow.snapshot;__hollow.snapshot=()=>({...previous(),joyY,sectors:[...sectors],roomTime,bombChain,mines:mines.map(m=>({...m}))});__hollow.clearSectors=()=>{for(const z of room.zones){z.open=true;sectors.add(z.id);}for(const e of room.enemies)if(e.zone)e.dead=true;};}
 let last=performance.now(),acc=0;function frame(now){const dt=Math.min(.06,(now-last)/1000);last=now;if(!manual&&mode==='play'){acc+=dt;for(let n=0;acc>=STEP&&n<4;n++){simulate(STEP);effects(STEP);acc-=STEP;}draw();}else{acc=0;}requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);
})();
