// Live rAF measurements and visual review. Placement hooks isolate art scenes;
// traversal, guardian balance and the escape have separate input-driven checks.
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),errors=[],failed=[],arcadeExternalResources=[],timings=[];
const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failed.push(r.url()+': '+r.status());});page.on('requestfailed',r=>{const message=r.url()+': '+r.failure().errorText;if(r.url().startsWith('https://fonts.googleapis.com/'))arcadeExternalResources.push(message);else failed.push(message);});
async function measure(label){await page.waitForTimeout(300);const result=await page.evaluate(()=>new Promise(resolve=>{const samples=[];let last=performance.now();function sample(t){samples.push(t-last);last=t;if(samples.length<120)requestAnimationFrame(sample);else{samples.shift();samples.sort((a,b)=>a-b);resolve({median:samples[Math.floor(samples.length*.5)],p95:samples[Math.floor(samples.length*.95)],frames:samples.length});}}requestAnimationFrame(sample);}));assert(result.p95<60,`${label}: ${result.p95}ms p95`);timings.push({label,...result});}
try{
 await page.goto('http://127.0.0.1:4173/');const card=page.locator('a.card[href="hollow-signal/"]');assert.equal(await card.count(),1);assert.equal(await card.locator('.card-title').innerText(),'Hollow Signal');await card.click();assert.equal(await page.title(),'Hollow Signal — VibeCade');await page.locator('#instruction-close').click();await page.screenshot({path:path.join(__dirname,'story-desktop.png')});await page.locator('#story-close').click();
 await page.keyboard.down('ArrowRight');await page.waitForTimeout(650);await page.keyboard.down('Space');await page.waitForTimeout(130);await page.keyboard.up('Space');await page.keyboard.press('x');await page.waitForTimeout(250);await page.keyboard.up('ArrowRight');await page.keyboard.press('m');assert.equal(await page.locator('#sound-button').innerText(),'SOUND OFF');await page.keyboard.press('m');assert.equal(await page.locator('#sound-button').innerText(),'SOUND ON');await measure('opening, real-time keyboard play');
 await page.goto('http://127.0.0.1:4173/hollow-signal/?test');await page.evaluate(()=>{__hollow.start();__hollow.manual(true);__hollow.grant('lens');__hollow.enter(7);__hollow.warp(6900);__hollow.step(50);});await page.keyboard.down('x');await page.evaluate(()=>{__hollow.step(43);__hollow.setPlayer({inv:0});__hollow.step(0);});await page.screenshot({path:path.join(__dirname,'gameplay-desktop.png')});await page.keyboard.up('x');
 for(let i=0;i<5;i++){const boss=await page.evaluate(i=>{__hollow.enter([4,10,16,22,28][i]);__hollow.warp(__hollow.world().arena.x+300);__hollow.step(1);__hollow.setBoss({phase:'wait',cycle:(2-i+4)%4,timer:0});__hollow.setPlayer({inv:999});__hollow.step(130);__hollow.setPlayer({inv:0});__hollow.step(0);return __hollow.snapshot().boss;},i);assert(Number.isFinite(boss.x)&&Number.isFinite(boss.y));await page.screenshot({path:path.join(__dirname,`guardian-${i+1}.png`)});}
 await page.evaluate(()=>{__hollow.setPlayer({inv:999});__hollow.manual(false);});await measure('Custodian, projectiles and living Heart art');
 await page.evaluate(()=>{__hollow.manual(true);__hollow.enter(19);__hollow.warp(500,380);__hollow.step(1);__hollow.manual(false);});await measure('Engine vertical chamber and moving lift');
 await context.close();const mobile=await browser.newContext({viewport:{width:740,height:390},isMobile:true,hasTouch:true});const q=await mobile.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto('http://127.0.0.1:4173/hollow-signal/?test');await q.evaluate(()=>{document.documentElement.requestFullscreen=()=>Promise.reject(new Error('test refusal'));__hollow.start();__hollow.enter(28);__hollow.warp(__hollow.world().arena.x+300);__hollow.step(1);__hollow.setPlayer({inv:999});});await q.waitForTimeout(250);const result=await q.evaluate(()=>new Promise(resolve=>{const samples=[];let last=performance.now();function sample(t){samples.push(t-last);last=t;if(samples.length<120)requestAnimationFrame(sample);else{samples.shift();samples.sort((a,b)=>a-b);resolve({median:samples[59],p95:samples[113],frames:samples.length});}}requestAnimationFrame(sample);}));assert(result.p95<60);timings.push({label:'740×390 mobile profile, Custodian',...result});await mobile.close();
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);fs.writeFileSync(path.join(__dirname,'live-check.json'),JSON.stringify({timings,errors,failed,arcadeExternalResources,arcadeLink:true},null,2));console.log(JSON.stringify({timings,errors,failed,arcadeExternalResources,arcadeLink:true},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
