const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto('http://127.0.0.1:4173/hollow-signal/?test');await page.evaluate(()=>{__hollow.manual(true);__hollow.start();});
 const geometry=await page.evaluate(()=>__hollow.rooms().map(r=>{const w=HollowWorld.build(r.id);return{id:r.id,w:r.w,h:r.h,fields:w.zones.length,guards:w.enemies.filter(e=>e.zone).length,bounds:w.platforms.every(a=>a.x>=0&&a.x+a.w<=r.w+1)&&w.portals.every(a=>a.x>=0&&a.x+a.w<=r.w&&a.y>=30),mainExitDistance:Math.max(...w.portals.map(p=>p.x))-120};}));assert(geometry.every(r=>r.bounds));assert(geometry.every(r=>r.w>=6000&&r.fields>=1));
 const mechanics=await page.evaluate(()=>{
  const key=(code,on)=>dispatchEvent(new KeyboardEvent(on?'keydown':'keyup',{code,bubbles:true}));for(const k of ['lens','fold','bomb','phase','frost','jump'])__hollow.grant(k);
  function target(room,armor){__hollow.enter(room);const e=__hollow.world().enemies.find(e=>e.armor===armor);for(const a of __hollow.world().enemies)if(a!==e)a.dead=true;e.type='sentry';e.y=__hollow.world().floor-e.h;e.timer=99;e.exposed=0;__hollow.warp(e.x-95,__hollow.world().floor-46);__hollow.setPlayer({dir:1,inv:99});return e;}
  function shot(e,weapon,full){__hollow.select(weapon);__hollow.shoot(full);__hollow.step(20,false);return e.hp;}
  let e=target(1,'carapace'),hp=e.hp;shot(e,0,false);const resisted=hp-e.hp;e.exposed=1;hp=e.hp;shot(e,0,false);const vent=hp-e.hp;e.exposed=0;hp=e.hp;shot(e,0,true);const charged=hp-e.hp;
  e=target(8,'crust');hp=e.hp;shot(e,0,true);const crustPulse=hp-e.hp;__hollow.warp(e.x-40);key('KeyS',true);key('KeyS',false);key('KeyX',true);key('KeyX',false);__hollow.step(50,false);const mined=e.dead;
  e=target(18,'phase');hp=e.hp;shot(e,0,true);const phasePulse=hp-e.hp;hp=e.hp;shot(e,2,true);const phaseBeam=hp-e.hp;
  __hollow.enter(9);__hollow.clearSectors();__hollow.warp(4350);__hollow.step(5,false);key('KeyS',true);key('KeyS',false);key('KeyX',true);let maxHeight=0,maxChain=0;for(let n=0;n<250;n++){__hollow.step(1,false);const s=__hollow.snapshot();maxHeight=Math.max(maxHeight,__hollow.world().floor-s.p.y-s.p.h);maxChain=Math.max(maxChain,s.bombChain);}key('KeyX',false);__hollow.setPlayer({inv:0});__hollow.step(0);const ball={maxHeight,maxChain,fold:__hollow.snapshot().p.fold};
  __hollow.enter(9);__hollow.clearSectors();__hollow.warp(4350);key('KeyS',true);key('KeyS',false);key('KeyX',true);key('KeyX',false);__hollow.step(2,false);key('KeyS',true);key('KeyS',false);__hollow.step(45,false);const standing={fold:__hollow.snapshot().p.fold,vy:__hollow.snapshot().p.vy,chain:__hollow.snapshot().bombChain};
  return{resisted,vent,charged,crustPulse,mined,phasePulse,phaseBeam,ball,standing};
 });console.log("Mechanics:",JSON.stringify(mechanics));assert(mechanics.resisted<1);assert(mechanics.vent===4);assert(mechanics.charged>20);assert.equal(mechanics.crustPulse,0);assert(mechanics.mined);assert.equal(mechanics.phasePulse,0);assert(mechanics.phaseBeam>30);assert(mechanics.ball.maxChain>=4);assert(mechanics.ball.maxHeight>650);assert.equal(mechanics.standing.chain,0);
 // Sector clearance is produced by real shots, then survives reload and death.
 const persistence=await page.evaluate(()=>{__hollow.enter(0);const z=__hollow.world().zones[0];for(const id of z.guards){const e=__hollow.world().enemies.find(e=>e.id===id);e.type='sentry';e.timer=999;e.y=__hollow.world().floor-e.h;__hollow.warp(e.x-95,__hollow.world().floor-46);__hollow.setPlayer({dir:1,inv:99});__hollow.select(0);for(let shots=0;!e.dead&&shots<12;shots++){__hollow.shoot(true);__hollow.step(20,false);}}const relay=__hollow.world().objects.find(o=>o.id==='relay-0-0');__hollow.warp(relay.x,__hollow.world().floor-46);__hollow.interact();__hollow.save();return{zone:z.id,checkpoint:__hollow.snapshot().checkpoint,sectors:__hollow.snapshot().sectors};});assert(persistence.sectors.includes(persistence.zone));await page.reload();await page.evaluate(()=>{__hollow.start();__hollow.manual(true);});assert((await page.evaluate(()=>__hollow.snapshot())).sectors.includes(persistence.zone));assert(await page.evaluate(()=>__hollow.world().zones[0].open));
 // A folded relay save must return a standing body on top of the floor.
 const foldedCheckpoint=await page.evaluate(()=>{const r=__hollow.world(),o=r.objects.find(o=>o.id==='relay-0-0');__hollow.warp(o.x,r.floor-46);dispatchEvent(new KeyboardEvent('keydown',{code:'KeyS',bubbles:true}));dispatchEvent(new KeyboardEvent('keyup',{code:'KeyS',bubbles:true}));__hollow.interact();__hollow.save();return{fold:__hollow.snapshot().p.fold,y:__hollow.snapshot().checkpoint.y,expected:r.floor-46};});assert(foldedCheckpoint.fold);assert.equal(foldedCheckpoint.y,foldedCheckpoint.expected);await page.reload();await page.evaluate(()=>{__hollow.start();__hollow.manual(true);__hollow.step(90,false);});const resumed=await page.evaluate(()=>__hollow.snapshot());assert(!resumed.p.fold);assert(resumed.p.ground);assert(Math.abs(resumed.p.y-foldedCheckpoint.expected)<1);
 await page.evaluate(()=>{__hollow.setPlayer({inv:0});__hollow.damage(999);});assert((await page.evaluate(()=>__hollow.snapshot())).sectors.includes(persistence.zone));
 const old={v:1,powers:['lens','fold','bomb'],collected:['lens','fold','bomb','tank-2'],visited:[0,1,2,3,4,5,6,7,8],opened:['1-4'],cleared:[0],anchors:[0,6],records:[0,1],checkpoint:{room:6,x:160},choice:'restore',escape:120,seenOpening:true};await page.evaluate(old=>localStorage.setItem('hollow-signal-v1',JSON.stringify(old)),old);await page.reload();await page.evaluate(()=>{__hollow.start();__hollow.manual(true);});const migrated=await page.evaluate(()=>__hollow.snapshot());assert(migrated.powers.includes('bomb'));assert(migrated.records.includes(1));assert(migrated.cleared.includes(0));assert(migrated.escape>479&&migrated.escape<=480);assert.equal(migrated.room,6);
 await page.evaluate(()=>{__hollow.enter(1);__hollow.warp(2300);__hollow.step(1);__hollow.setPlayer({inv:0});__hollow.step(0);});await page.screenshot({path:path.join(__dirname,'redesign-desktop.png')});
 assert.deepEqual(errors,[]);const result={geometry,mechanics,persistence,foldedCheckpoint,migration:{powers:migrated.powers,records:migrated.records,guardian:migrated.cleared,escape:migrated.escape},errors};fs.writeFileSync(path.join(__dirname,'redesign-check.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
