window.HollowStory={
 opening:{speaker:'LIO / DISTRESS ARCHIVE',title:'You kept the frequency.',text:['“Ari. If you can hear me, do not trust the quarantine beacons. Follow the light under the water.”','Twelve years ago, Nacre went silent. This morning your missing sister’s voice came through a receiver you had nearly thrown away. Your ship finds an empty landing field. Below it, something is still breathing.']},
 fold:{speaker:'LIO / FRAGMENT 01',title:'Something small enough to listen.',text:['“The Shellkeeper thinks you are an infection. I taught the little suit to fold so it could reach the places the patrols cannot.”','The machine’s core fits your armor. For a moment, its signal sounds like Lio laughing. The drainways lead into roots—not rot, but carefully tended growth.']},
 jump:{speaker:'RESIDENT SERA / RECOVERED LINK',title:'It fed us when the lights failed.',text:['“We called it the Chorus. When the reactor broke, it brought oxygen through the roots. The quarantine system called it contamination.”','The Wing coil was built for tending its upper branches. Beyond the Underworks lies the archive where the colony’s last voices were recorded.']},
 phase:{speaker:'LIO / FRAGMENT 07',title:'I stayed because they were still here.',text:['“I could not carry them out in a shuttle. The Chorus could hold their memories until someone found a way. So I stayed.”','The Custodian has spent twelve years erasing what it calls corrupted residents. Your sister’s signal is not a trapped recording. It is a plea from someone still choosing to keep her promise.']},
 heat:{speaker:'LIO / LIVE SIGNAL',title:'The repair I never finished.',text:['“The engine is too hot for my shell. Yours can make the descent now. I need you at the Heart.”','Her voice is clearer. So is the cost: restore the Chorus and Lio remains its caretaker; sever it and its voices fall silent, but the quarantine link can no longer threaten another expedition. She asks you to see the Heart before deciding.']},
 final:{speaker:'THE CUSTODIAN / OFFLINE',title:'No one here was corrupted.',text:['The last defensive shell falls away. Under the machinery, thousands of small lights answer Lio’s voice.','The severance console is in the western chamber. Its two circuits wait for a human choice. The facility is unstable. Whatever you decide, you will have to reach the surface.']},
 records:[
  {speaker:'PORT ENGINEER NIMA',title:'Witness 01 / the empty berths',text:['The evacuation lists say everyone left. I counted the shuttles. There were not enough seats. Lio went back down the lift while the administrators were still arguing.']},
  {speaker:'BOTANIST SERA',title:'Witness 02 / a borrowed breath',text:['The roots grew into the oxygen pumps before they ever touched a person. We were frightened until we realized the pressure was rising. Something below was helping us breathe.']},
  {speaker:'TECHNICIAN OS',title:'Witness 03 / what the mines were for',text:['A pulse mine does not burn the roots. It separates their mineral joints. That was Lio’s rule: open a path, leave the living tissue intact. We were guests here.']},
  {speaker:'ARCHIVIST REN',title:'Witness 04 / voices in glass',text:['Memory is a pattern. The Chorus can hold the pattern, but it cannot choose what a person becomes. We kept journals so we would remember that consent still mattered.']},
  {speaker:'LIO VENN',title:'Witness 05 / the choice I made',text:['Ari, I joined the link willingly. Please do not imagine that I have spent all these years waiting to be taken away. I have missed you. Both things can be true.']},
  {speaker:'REACTOR KEEPER HAL',title:'Witness 06 / the false quarantine',text:['The Custodian is following an order issued before anyone understood the Chorus. Its erasure routine removes residents faster than we can repair the archive. It calls that progress.']},
  {speaker:'THE CHORUS',title:'Witness 07 / an unfamiliar word',text:['We learned your word for home from Lio. It is not the place that contains you. It is the place that answers when you speak. We would like to keep answering.']},
  {speaker:'LIO / FINAL PERSONAL RECORD',title:'Witness 08 / after the signal',text:['Whatever happens, take the witness records with you. Let someone know we were here. If you leave me with them, visit. If the voices stop, remember more than the way we ended.']}
 ]
};
