const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const url='http://127.0.0.1:4173/hollow-signal/?test';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>__hollow.snapshot()),step=n=>page.evaluate(n=>__hollow.step(n),n),enter=id=>page.evaluate(id=>{__hollow.enter(id);__hollow.step(6);},id),warp=(x,y)=>page.evaluate(([x,y])=>y===undefined?__hollow.warp(x):__hollow.warp(x,y),[x,y]);
const dismiss=async()=>{if((await state()).mode==='story')await page.locator('#story-close').click();};
async function relic(id){const rooms=await page.evaluate(()=>__hollow.rooms());const target=rooms.find(r=>r.relic===id);await enter(target.id);const a=await page.evaluate(id=>__hollow.world().objects.find(o=>o.power===id),id);await warp(a.x,a.y-8);await page.keyboard.press('e');assert((await state()).powers.includes(id));await dismiss();}
async function guardian(id){await enter([4,10,16,22,28][id]);await page.evaluate(()=>__hollow.warp(__hollow.world().arena.x+350));await step(1);assert((await state()).boss);await page.evaluate(()=>{const s=__hollow.snapshot();__hollow.setBoss({hp:1,inv:0,phase:'wait',timer:99});__hollow.warp(s.boss.x-100,s.boss.y+36);__hollow.setPlayer({dir:1});__hollow.select(0);__hollow.shoot(true);});await step(18);assert((await state()).cleared.includes(id));assert.equal((await state()).mode,'story');await dismiss();}
try{
 await page.goto(url);await page.evaluate(()=>__hollow.manual(true));const before=await state();await page.waitForTimeout(250);assert.equal((await state()).t,before.t);assert.equal((await state()).mode,'instructions');await page.locator('#instruction-close').click();assert.equal((await state()).mode,'story');await step(90);assert.equal((await state()).t,0);await dismiss();await step(6);await page.keyboard.press('e');assert((await state()).anchors.includes(0));
 await page.keyboard.down('ArrowRight');await step(65);await page.keyboard.up('ArrowRight');assert((await state()).p.x>380);const y=(await state()).p.y;await page.keyboard.down('Space');await step(12);assert((await state()).p.y<y-85);await page.keyboard.up('Space');await step(60);assert((await state()).p.ground);await page.keyboard.down('ArrowUp');await page.keyboard.press('x');await step(1);assert(await page.evaluate(()=>__hollow.bullets().some(b=>b.owner==='player'&&b.vy<0)));await page.keyboard.up('ArrowUp');
 await page.keyboard.down('x');await step(45);await page.locator('#help-button').click();const paused=(await state()).t;await step(80);assert.equal((await state()).t,paused);await page.locator('#instruction-close').click();assert.equal((await state()).charge,0);await page.keyboard.up('x');await page.keyboard.press('r');assert.equal((await state()).room,0);checks.push('Instructions and story gate simulation; sanctuary saves; keyboard movement, jump, upward fire, help cancellation and restart passed.');
 await enter(1);const gate=await page.evaluate(()=>__hollow.world().portals.find(e=>e.to===4));await warp(gate.x);await page.keyboard.press('e');assert.equal((await state()).room,1);assert(!(await state()).opened.includes(gate.id));
 await relic('lens');await enter(1);await warp(gate.x-60);await page.evaluate(()=>__hollow.setPlayer({dir:1}));await page.keyboard.down('x');await step(45);assert.equal(await page.evaluate(()=>__hollow.bullets().filter(b=>b.owner==='player').length),0);await page.keyboard.up('x');await step(30);assert((await state()).opened.includes(gate.id));await warp(gate.x+10);await page.keyboard.press('e');assert.equal((await state()).room,4);checks.push('Lens discovery, charge without firing, release blast, persistent resonance seal and connected transition passed.');
 await guardian(0);assert((await state()).powers.includes('fold'));await enter(5);const tunnel=await page.evaluate(()=>__hollow.world().platforms.find(a=>a.tunnel));await warp(tunnel.x-60);await page.keyboard.down('ArrowRight');await step(35);assert((await state()).p.x<=tunnel.x-27);await page.keyboard.press('ArrowDown');assert((await state()).p.fold);await step(150);await page.keyboard.up('ArrowRight');assert((await state()).p.x>tunnel.x+tunnel.w);await page.keyboard.press('s');assert.equal((await state()).p.h,46);checks.push('Guardian projectile defeat releases Spindle; physical low tunnel blocks standing and admits rolling form.');
 await relic('bomb');await enter(7);const amber=await page.evaluate(()=>__hollow.world().portals.find(e=>e.to===10));await warp(amber.x-45);await page.keyboard.press('s');await page.keyboard.press('x');await step(42);assert((await state()).opened.includes(amber.id));await guardian(1);assert((await state()).powers.includes('jump'));await enter(12);await page.keyboard.down('Space');await step(20);await page.keyboard.up('Space');await step(1);const vy=(await state()).p.vy;await page.keyboard.down('Space');await step(1);assert((await state()).p.vy<vy-100);assert((await state()).p.airJump);await page.keyboard.up('Space');checks.push('Folded mine breaks amber gate; Matron releases Wing; second jump changes aerial trajectory.');
 await relic('seeker');await relic('frost');await enter(13);const enemy=await page.evaluate(()=>__hollow.world().enemies.find(e=>e.type!=='moth'));await warp(enemy.x-85,enemy.y-8);await page.evaluate(()=>{__hollow.setPlayer({dir:1});__hollow.select(3);__hollow.shoot(false);});await step(9);assert(await page.evaluate(id=>__hollow.world().enemies.find(e=>e.id===id).frozen>1,enemy.id));checks.push('Both optional weapons are recoverable; Frost freezes a surviving enemy.');
 await guardian(2);await enter(16);const phase=await page.evaluate(()=>__hollow.world().portals.find(e=>e.to===18));await warp(phase.x-90);await page.evaluate(()=>{__hollow.select(2);__hollow.setPlayer({dir:1});__hollow.shoot(false);});await step(20);assert((await state()).opened.includes(phase.id));await enter(18);const closeSeal=await page.evaluate(()=>__hollow.world().portals.find(e=>e.to===19));await warp(closeSeal.x+10);await page.evaluate(()=>{__hollow.setPlayer({dir:1});__hollow.select(2);__hollow.shoot(false);});await step(1);assert((await state()).opened.includes(closeSeal.id));
 await enter(17);const shortcut=await page.evaluate(()=>__hollow.world().portals.find(e=>e.shortcut));await warp(shortcut.x-90);await page.evaluate(()=>{__hollow.select(2);__hollow.setPlayer({dir:1});__hollow.shoot(false);});await step(20);assert((await state()).opened.includes(shortcut.id));await warp(shortcut.x);await page.keyboard.press('e');assert.equal((await state()).room,2);checks.push('Phase beam opens the Engine and the Echo Chamber shortcut back to the original ruins.');
 await guardian(3);assert((await state()).powers.includes('heat'));await enter(23);const heat=await page.evaluate(()=>__hollow.world().hazards.find(h=>h.type==='heat'));await warp(heat.x+20);await page.evaluate(()=>__hollow.setPlayer({inv:0}));const health=(await state()).p.hp;await step(60);assert.equal((await state()).p.hp,health);checks.push('Furnace guardian releases Thermal; hot basin is harmless with the mantle.');
 // Every room renders, all links stay inside the graph, and collectibles persist.
 for(let id=0;id<30;id++){await enter(id);const r=await page.evaluate(()=>__hollow.world());await page.evaluate(()=>__hollow.clearSectors());assert(r.portals.length>0);assert(r.platforms.every(a=>a.x>=0&&a.x+a.w<=r.w+1));if(r.witness!==undefined){const a=r.objects.find(o=>o.type==='record');await warp(a.x,a.y-8);await page.keyboard.press('e');await dismiss();}if(r.tank){const a=r.objects.find(o=>o.type==='tank');await warp(a.x,a.y);await step(1);}if(r.hub){const a=r.objects.find(o=>o.type==='pod');await warp(a.x+5);await page.keyboard.press('e');}if([1,7,14,21,26].includes(id)){await page.evaluate(()=>__hollow.setPlayer({inv:0}));await step(1);await page.screenshot({path:path.join(__dirname,`region-${r.region+1}.png`)});}}
 assert.equal((await state()).visited.length,30);assert.equal((await state()).records.length,8);assert.equal((await state()).anchors.length,5);const graph=await page.evaluate(()=>__hollow.graph());assert(graph.every(e=>e.a>=0&&e.a<30&&e.b>=0&&e.b<30));checks.push('All 30 connected rooms, five sanctuaries, eight witnesses, suit reserves and five biome renders passed.');
 await page.keyboard.press('Tab');assert.equal((await state()).mode,'atlas');assert.equal(await page.locator('#travel-list button').count(),5);const mapT=(await state()).t;await step(80);assert.equal((await state()).t,mapT);await page.screenshot({path:path.join(__dirname,'atlas-desktop.png')});await page.locator('#travel-list button').first().click();assert.equal((await state()).room,0);assert.equal((await state()).mode,'play');
 await page.evaluate(()=>__hollow.save());await page.reload();await page.evaluate(()=>__hollow.manual(true));assert.equal((await state()).powers.length,8);assert.equal((await state()).records.length,8);assert.equal((await state()).visited.length,30);checks.push('Atlas pauses, sanctuary travel works, and discoveries/journal survive reload.');
 await guardian(4);await enter(29);const consoleObject=await page.evaluate(()=>__hollow.world().objects.find(o=>o.type==='console'));await warp(consoleObject.x,consoleObject.y+35);await page.keyboard.press('e');assert.equal((await state()).mode,'choice');const beforeChoice=await page.evaluate(()=>__hollow.data());fs.writeFileSync(path.join(__dirname,'campaign-fixture.json'),JSON.stringify(beforeChoice,null,2));await page.locator('[data-choice="restore"]').click();assert((await state()).escape>179);await page.keyboard.press('Tab');assert(await page.locator('#travel-list button').evaluateAll(bs=>bs.every(b=>b.disabled)));await page.locator('#atlas-close').click();await step(120);assert((await state()).escape<719);await enter(0);const ship=await page.evaluate(()=>__hollow.world().objects.find(o=>o.type==='ship'));await warp(ship.x+35);await page.keyboard.press('e');assert.equal((await state()).mode,'ending');assert((await state()).complete);assert((await page.locator('#ending-title').innerText()).includes('light'));await page.screenshot({path:path.join(__dirname,'ending-restore.png')});await page.locator('#ending-explore').click();assert.equal((await state()).mode,'play');
 const other=await browser.newContext({viewport:{width:1440,height:900}});await other.addInitScript(s=>{localStorage.setItem('hollow-signal-v1',JSON.stringify(s));sessionStorage.setItem('hollow-signal-instructions','seen');},beforeChoice);const q=await other.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(url);await q.evaluate(()=>{__hollow.manual(true);__hollow.enter(29);const a=__hollow.world().objects.find(o=>o.type==='console');__hollow.warp(a.x,a.y+35);__hollow.interact();});await q.locator('[data-choice="sever"]').click();await q.evaluate(()=>{__hollow.enter(0);__hollow.warp(335);__hollow.interact();});assert.equal(await q.evaluate(()=>__hollow.snapshot().mode),'ending');assert((await q.locator('#ending-title').innerText()).includes('names'));await other.close();checks.push('Final guardian, both informed choices, timed escape, disabled escape travel, launch and post-ending exploration passed.');
 const hp=(await state()).maxHP;await page.evaluate(()=>{__hollow.setPlayer({inv:0,hp:1});__hollow.damage(50);});assert.equal((await state()).p.hp,hp);assert.equal((await state()).powers.length,8);await page.locator('#help-button').click();await page.locator('#new-game').click();assert.equal((await state()).powers.length,8);await page.locator('#instruction-close').click();checks.push('Death retains progression; New Expedition requires a second confirming click.');
 for(const [width,height] of [[667,375],[740,390],[844,390],[390,844]]){
  const mobile=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true});await mobile.addInitScript(()=>{Element.prototype.requestFullscreen=()=>Promise.reject(new Error('Fullscreen refused in test'));});const q=await mobile.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(url);await q.evaluate(()=>__hollow.manual(true));assert.equal(await q.locator('#touch-controls').isVisible(),false);await q.locator('#instruction-close').click();await q.waitForTimeout(1700);await q.locator('#story-close').click();await q.evaluate(()=>__hollow.step(6));const c=await q.locator('canvas').boundingBox(),j=await q.locator('[data-joystick]').boundingBox(),actions=await q.locator('.control-cluster').boundingBox();if(width>height){assert(j.x+j.width<=c.x+1);assert(actions.x>=c.x+c.width-1);}else assert(actions.y>=c.y+c.height);assert(actions.y+actions.height<=height-1);
  await q.mouse.move(j.x+63,j.y+63);await q.mouse.down();await q.mouse.move(j.x+107,j.y+63);assert((await q.evaluate(()=>__hollow.snapshot())).joy>.7);await q.evaluate(()=>__hollow.step(25));await q.mouse.move(j.x+63,j.y+63);assert(Math.abs((await q.evaluate(()=>__hollow.snapshot())).joy)<.05);await q.mouse.up();assert.equal((await q.evaluate(()=>__hollow.snapshot())).joy,0);
  const jump=q.locator('[data-action="jump"]');await jump.dispatchEvent('pointerdown',{pointerId:1,pointerType:'touch',bubbles:true});await q.evaluate(()=>__hollow.step(8));assert((await q.evaluate(()=>__hollow.snapshot())).p.vy<0);await jump.dispatchEvent('pointercancel',{pointerId:1,bubbles:true});assert.equal((await q.evaluate(()=>__hollow.snapshot())).held.jump,false);await q.evaluate(()=>{__hollow.step(70);__hollow.grant('lens');__hollow.grant('fold');__hollow.grant('bomb');});
  const fire=q.locator('[data-action="fire"]');await fire.dispatchEvent('pointerdown',{pointerId:2,pointerType:'touch',bubbles:true});await q.evaluate(()=>__hollow.step(45));assert.equal(await q.evaluate(()=>__hollow.bullets().filter(b=>b.owner==='player').length),0);await fire.dispatchEvent('pointerup',{pointerId:2,bubbles:true});await q.evaluate(()=>__hollow.step(1));assert(await q.evaluate(()=>__hollow.bullets().some(b=>b.full)));await q.mouse.move(j.x+63,j.y+63);await q.mouse.down();await q.mouse.move(j.x+63,j.y+107);await q.evaluate(()=>__hollow.step(2));assert((await q.evaluate(()=>__hollow.snapshot())).p.fold);await q.mouse.up();await q.locator('[data-action="map"]').dispatchEvent('pointerdown',{pointerId:4,pointerType:'touch',bubbles:true});assert.equal(await q.evaluate(()=>__hollow.snapshot().mode),'atlas');await q.locator('#atlas-sound').click();assert.equal(await q.locator('#atlas-sound').innerText(),'SOUND OFF');await q.locator('#atlas-close').click();await q.evaluate(()=>__hollow.step(1));await q.screenshot({path:path.join(__dirname,`mobile-${width}.png`)});
  await fire.dispatchEvent('pointerdown',{pointerId:5,pointerType:'touch',bubbles:true});await q.evaluate(()=>__hollow.step(45));await fire.dispatchEvent('lostpointercapture',{pointerId:5,bubbles:true});assert.equal((await q.evaluate(()=>__hollow.snapshot())).charge,0);assert.equal((await q.evaluate(()=>__hollow.snapshot())).held.fire,false);await q.locator('.vibecade-mobile-restart').click();assert.equal((await q.evaluate(()=>__hollow.snapshot())).room,0);await q.evaluate(()=>dispatchEvent(new Event('blur')));assert.equal((await q.evaluate(()=>__hollow.snapshot())).mode,'instructions');await mobile.close();checks.push(`${width}×${height}: reachable instructions, fullscreen refusal, clear rails/portrait, joystick neutral/release, jump cancel, charge/release, joystick Fold, atlas, lost capture, restart and blur passed.`);
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({checks,errors},null,2));console.log(checks.join('\n'));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
