(() => {
  'use strict';
  const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),art=window.ClockworkArt;
  const dirs=[[0,-1],[1,0],[0,1],[-1,0]],keys=new Set();let joy=[0,0],audio,dirty=true,last=0,manual=false;
  const configs=[
    {name:'The apprentice bench',count:2,step:.95,chase:.20,fast:0,armor:0,crates:18,range:2,kick:false,fuse:2.2,limit:110,hearts:5,shields:2},
    {name:'The chain-reaction aisle',count:3,step:.82,chase:.23,fast:0,armor:0,crates:20,range:3,kick:false,fuse:2.2,limit:110,hearts:5,shields:2},
    {name:'Boots on the floor',count:4,step:.73,chase:.28,fast:0,armor:0,crates:22,range:3,kick:true,fuse:2.2,limit:110,hearts:5,shields:2},
    {name:'Express assembly',count:5,step:.66,chase:.34,fast:1,armor:0,crates:23,range:3,kick:true,fuse:2.2,limit:105,hearts:5,shields:2},
    {name:'The armored collection',count:6,step:.59,chase:.40,fast:1,armor:2,crates:24,range:3,kick:true,fuse:2.2,limit:100,hearts:5,shields:2},
    {name:'Master clockmaker',count:8,step:.40,chase:.62,fast:3,armor:3,crates:24,range:3,kick:true,fuse:1.85,limit:85,hearts:4,shields:1},
    {name:'The perfect mechanism',count:9,step:.38,chase:.75,fast:3,armor:4,crates:24,range:3,kick:true,fuse:1.6,limit:72,hearts:3,shields:0}
  ];
  const state={mode:'intro',room:1,score:0,time:0,muted:false,grid:[],bombs:[],fire:[],enemies:[],gears:[],particles:[]};let seed=1;
  const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
  function say(text){$('status').textContent=text;dirty=true}
  function tone(freq,duration=.08,type='sine'){if(state.muted||!audio||state.mode==='intro'||state.mode==='help')return;try{const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch(_){}}
  function unlockAudio(){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume().catch(()=>{})}catch(_){}}
  function release(){keys.clear();joy=[0,0];document.querySelectorAll('.pressed').forEach(b=>b.classList.remove('pressed'));window.dispatchEvent(new Event('vibecade:reset-input'))}
  function hud(){const values={room:`${state.room} / 7`,robots:state.enemies.length,hearts:'♥'.repeat(Math.max(0,state.hearts)),clock:Math.max(0,Math.ceil(state.cfg.limit-state.time)),score:state.score,shields:state.shields};for(const [k,v]of Object.entries(values))if($(k).textContent!==String(v))$(k).textContent=v;$('shield').disabled=!state.shields;$('shield').style.opacity=state.shields?'1':'.5';$('pause').textContent=state.mode==='paused'?'Resume':'Pause'}
  function begin(n){release();state.room=n;state.cfg=configs[n-1];seed=731+n*127;state.time=0;state.hits=[];state.hearts=state.cfg.hearts;state.shields=state.cfg.shields;state.bombs=[];state.fire=[];state.gears=[];state.particles=[];state.mode='playing';state.player={x:1,y:1,drawX:1,drawY:1,move:0,inv:2,shield:0,face:1};state.grid=Array.from({length:9},(_,y)=>Array.from({length:13},(_,x)=>x===0||y===0||x===12||y===8||(x%2===0&&y%2===0)?1:0));
    const free=[];for(let y=1;y<8;y++)for(let x=1;x<12;x++)if(state.grid[y][x]===0&&(x+y>4)&&!(x===11&&y===7))free.push([x,y]);
    // Every room retains two open outer routes; crates create optional shortcuts.
    const spots=free.filter(([x,y])=>x!==1&&y!==1&&x!==11&&y!==7);for(let i=spots.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[spots[i],spots[j]]=[spots[j],spots[i]]}for(const [x,y]of spots.slice(0,state.cfg.crates))state.grid[y][x]=2;
    const starts=[[11,1],[11,7],[1,7],[9,3],[7,5],[5,7],[7,1],[11,5],[5,3]];state.enemies=starts.slice(0,state.cfg.count).map(([x,y],i)=>{state.grid[y][x]=0;for(const[dX,dY]of dirs)if(state.grid[y+dY]?.[x+dX]===2)state.grid[y+dY][x+dX]=0;return{x,y,drawX:x,drawY:y,move:.7+i*.16,dir:i%4,stun:0,hit:0,hp:i<state.cfg.armor?2:1,fast:i>=state.cfg.armor&&i<state.cfg.armor+state.cfg.fast}});
    $('result-modal').classList.remove('is-visible');say(`${state.cfg.name} · ${n===1?'Place a charge, then turn a corner.':n===2?'Longer blast crosses. Charges chain together.':n===3?'Walk into a charge to kick it away.':n===4?'Gold express robots move faster.':n===5?'Purple armor needs two blasts.':n===6?'Short fuses. One shield. Plan every retreat.':'Fast patrols. No shields. Make each charge count.'}`);hud();dirty=true;
  }
  function reset(){const gated=$('instruction-modal').classList.contains('is-visible');state.score=0;begin(1);state.beforeHelp='playing';if(gated)state.mode=state.seen?'help':'intro';hud()}
  const bombAt=(x,y)=>state.bombs.find(b=>b.x===x&&b.y===y);
  const passable=(x,y)=>state.grid[y]?.[x]===0&&!bombAt(x,y);
  function footprint(b){const out=[[b.x,b.y]];for(const[dx,dy]of dirs)for(let r=1;r<=b.range;r++){const x=b.x+dx*r,y=b.y+dy*r,v=state.grid[y]?.[x];if(v===undefined||v===1)break;out.push([x,y]);if(v===2)break}return out}
  function plant(){if(state.mode!=='playing')return;const p=state.player;if(bombAt(p.x,p.y)||state.bombs.length>=2){say('Both charges are winding. Let one burst first.');return}state.bombs.push({x:p.x,y:p.y,fuse:state.cfg.fuse,range:state.cfg.range,roll:0,dx:0,dy:0});tone(520);say('Charge set — get around a corner.');dirty=true}
  function shield(){if(state.mode!=='playing'||!state.shields||state.player.shield>0)return;state.shields--;state.player.shield=3;state.player.inv=Math.max(state.player.inv,3);say('Shield on · three seconds to recover.');tone(800,.2);hud()}
  function burst(x,y,color){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const max=document.body.classList.contains('touch-device')?7:14;for(let i=0;i<max&&state.particles.length<100;i++)state.particles.push({x:art.OX+x*64+32,y:art.OY+y*64+32,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.7,size:3+Math.random()*4,color})}
  function explode(b){if(!state.bombs.includes(b))return;state.bombs.splice(state.bombs.indexOf(b),1);const cells=footprint(b),chains=[];for(const[x,y]of cells){if(state.grid[y][x]===2){state.grid[y][x]=0;state.score+=20;burst(x,y,'#d5aa78');if((x*3+y+state.room)%4===0)state.gears.push({x,y})}state.fire.push({x,y,life:.48});const chain=bombAt(x,y);if(chain)chains.push(chain)}tone(115,.17,'triangle');for(const chain of chains)explode(chain)}
  function damage(source="test"){const p=state.player;if(p.inv>0)return;state.hearts--;state.hits.push({source,time:+state.time.toFixed(2),x:p.x,y:p.y});p.inv=2.5;for(const e of state.enemies)if(Math.abs(e.x-p.x)+Math.abs(e.y-p.y)<=1)e.stun=Math.max(e.stun,1.5);burst(p.x,p.y,'#e66f71');tone(155,.2,'sawtooth');say('Heart lost · nearby robots stunned. 2.5 seconds of cover.');if(state.hearts<=0)finish(false);hud()}
  function finish(won){if(state.mode!=='playing')return;state.mode=won?'clear':'over';release();$('result-title').textContent=won?(state.room===7?'Perfectly wound!':'Workshop cleared'):'The spring ran out';$('result-text').textContent=won?`${state.cfg.name}. ${state.hearts} hearts left. Score ${state.score}. ${state.room===7?'All seven rooms restored.':'Hearts and shields refill in the next room.'}`:`Room ${state.room} · score ${state.score}. Use pillars for cover and save shields for a trapped retreat.`;$('next').hidden=!won||state.room===7;$('again').hidden=won&&state.room<7;$('result-modal').classList.add('is-visible');(won&&state.room<7?$('next'):$('again')).focus();dirty=true}
  function movement(dx,dy){if(state.mode!=='playing'||(!dx&&!dy))return;const p=state.player;if(p.move>0)return;const x=p.x+dx,y=p.y+dy,b=bombAt(x,y);p.face=dirs.findIndex(v=>v[0]===dx&&v[1]===dy);if(b&&state.cfg.kick&&passable(x+dx,y+dy)){b.x+=dx;b.y+=dy;b.dx=dx;b.dy=dy;b.roll=.12;say('Charge kicked — keep clear of its lane.');tone(360)}if(passable(x,y)){p.x=x;p.y=y;p.move=.135;dirty=true}}
  function direction(){if(joy[0]||joy[1])return joy;for(const k of [...keys].reverse()){if(k==='arrowup'||k==='w')return[0,-1];if(k==='arrowdown'||k==='s')return[0,1];if(k==='arrowleft'||k==='a')return[-1,0];if(k==='arrowright'||k==='d')return[1,0]}return[0,0]}
  function tick(dt){if(state.mode!=='playing'||document.hidden)return;dt=Math.min(.05,dt);state.time+=dt;const p=state.player;p.move=Math.max(0,p.move-dt);p.inv=Math.max(0,p.inv-dt);p.shield=Math.max(0,p.shield-dt);movement(...direction());p.drawX+=(p.x-p.drawX)*Math.min(1,dt*25);p.drawY+=(p.y-p.drawY)*Math.min(1,dt*25);
    for(const b of [...state.bombs]){b.fuse-=dt;if(b.dx||b.dy){b.roll-=dt;if(b.roll<=0){if(passable(b.x+b.dx,b.y+b.dy)&&!(p.x===b.x+b.dx&&p.y===b.y+b.dy)){b.x+=b.dx;b.y+=b.dy;b.roll=.12}else{b.dx=0;b.dy=0}}}if(b.fuse<=0)explode(b)}
    for(const f of state.fire)f.life-=dt;state.fire=state.fire.filter(f=>f.life>0);
    if(state.fire.some(f=>f.x===p.x&&f.y===p.y))damage("blast");if(state.mode!=='playing')return;
    for(const e of [...state.enemies]){e.hit=Math.max(0,e.hit-dt);e.stun=Math.max(0,e.stun-dt);if(e.hit<=0&&state.fire.some(f=>f.x===e.x&&f.y===e.y)){e.hp--;e.hit=.65;e.stun=1;burst(e.x,e.y,e.hp?'#cbb2e0':'#a8d6cb');if(e.hp<=0){state.enemies.splice(state.enemies.indexOf(e),1);state.score+=100+state.room*25;say(`${state.enemies.length} robots remain. ${state.enemies.length?'Use open lanes to trap them.':'The EXIT is open!'}`);tone(680,.12);continue}}
      e.move-=dt;if(e.move<=0&&e.stun<=0){const candidates=dirs.map(([dx,dy],d)=>({x:e.x+dx,y:e.y+dy,d})).filter(v=>passable(v.x,v.y)&&!state.enemies.some(other=>other!==e&&other.x===v.x&&other.y===v.y)&&!state.fire.some(f=>f.x===v.x&&f.y===v.y));if(candidates.length){const ahead=candidates.find(v=>v.d===e.dir);let choice=ahead&&random()<.65?ahead:candidates[Math.floor(random()*candidates.length)];if(random()<state.cfg.chase){candidates.sort((a,b)=>(Math.abs(a.x-p.x)+Math.abs(a.y-p.y))-(Math.abs(b.x-p.x)+Math.abs(b.y-p.y)));choice=candidates[0]}e.x=choice.x;e.y=choice.y;e.dir=choice.d}e.move=state.cfg.step*(e.fast?.7:1)}e.drawX+=(e.x-e.drawX)*Math.min(1,dt*12);e.drawY+=(e.y-e.drawY)*Math.min(1,dt*12);if(e.x===p.x&&e.y===p.y&&e.stun<=0)damage("robot");if(state.mode!=='playing')return}
    state.gears=state.gears.filter(g=>{if(g.x===p.x&&g.y===p.y){state.score+=75;tone(900);burst(g.x,g.y,'#edc36e');return false}return true});for(const q of state.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=120*dt}state.particles=state.particles.filter(q=>q.life>0);
    if(!state.enemies.length&&p.x===11&&p.y===7){state.score+=Math.ceil(state.cfg.limit-state.time)*10+state.hearts*100;finish(true)}else if(state.time>=state.cfg.limit){state.hearts=0;finish(false)}hud();dirty=true;
  }
  function help(){if(state.mode==='clear'||state.mode==='over')return;state.beforeHelp=state.mode;state.mode=state.seen?'help':'intro';release();$('instruction-modal').classList.add('is-visible');$('instruction-close').textContent=state.seen?'BACK TO THE WORKSHOP':'WIND UP THE WORKSHOP';$('instruction-close').focus();dirty=true}
  function start(){unlockAudio();state.seen=true;try{sessionStorage.setItem('clockwork-blast-instructions-v1','seen')}catch(_){}$('instruction-modal').classList.remove('is-visible');state.mode=state.beforeHelp==='paused'?'paused':'playing';release();canvas.focus({preventScroll:true});hud();dirty=true}
  function pause(){if(!['playing','paused'].includes(state.mode))return;state.mode=state.mode==='playing'?'paused':'playing';release();hud();dirty=true}
  function mute(){state.muted=!state.muted;$('sound').textContent=state.muted?'Sound off':'Sound on';$('touch-sound').textContent=state.muted?'SOUND OFF':'SOUND';if(!state.muted)unlockAudio()}
  document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(e.target.closest?.('button')&&[' ','enter'].includes(k))return;if(['arrowup','arrowdown','arrowleft','arrowright',' ','w','a','s','d','x','p','r','m'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='r')reset();else if(k==='m')mute();else if(k==='p')pause();else if(k===' '){unlockAudio();plant()}else if(k==='x'){unlockAudio();shield()}else{keys.add(k);movement(...direction())}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
  $('instruction-close').onclick=start;$('help-button').onclick=help;$('pause').onclick=pause;$('reset').onclick=reset;$('sound').onclick=mute;$('touch-sound').onclick=mute;$('next').onclick=()=>begin(state.room+1);$('again').onclick=reset;
  function action(id,fn){const b=$(id);let pointer=null;b.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();pointer=e.pointerId;try{b.setPointerCapture(pointer)}catch(_){}b.classList.add('pressed');unlockAudio();fn()});const off=()=>{pointer=null;b.classList.remove('pressed')};for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,off);b.addEventListener('click',e=>{if(e.detail===0)fn()});window.addEventListener('blur',off)}action('charge',plant);action('shield',shield);
  window.addEventListener('vibecade:restart',e=>{e.preventDefault();reset()});window.addEventListener('blur',()=>{release();if(state.mode==='playing')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){release();if(state.mode==='playing')pause()}});
  window.VibeCadeJoystick(document.querySelector('[data-joystick]'),{mode:'cardinal',onChange:(x,y)=>{joy=[x,y];movement(x,y)}});
  function resize(){const scale=document.body.classList.contains('touch-device')?1:Math.min(2,devicePixelRatio||1);canvas.width=960*scale;canvas.height=672*scale;ctx.setTransform(scale,0,0,scale,0,0);dirty=true}window.addEventListener('resize',resize);
  const params=new URLSearchParams(location.search);let level=Math.max(1,Math.min(7,Number(params.get('room'))||1));begin(level);try{state.seen=sessionStorage.getItem('clockwork-blast-instructions-v1')==='seen'}catch(_){}if(state.seen){$('instruction-modal').classList.remove('is-visible')}else{state.mode='intro';$('instruction-close').focus()}resize();
  function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;if(!manual)tick(dt);if(dirty){art.draw(ctx,state);dirty=false}requestAnimationFrame(frame)}requestAnimationFrame(frame);
  if(params.has('test'))window.__clockTest={state,configs,begin,tick,plant,shield,movement,footprint,damage,finish,draw:()=>{art.draw(ctx,state);dirty=false},manual:value=>{manual=value},setInput:(dx,dy)=>{joy=[dx,dy]}};
})();
