(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d');
const profiles=[
 {name:'THE WARM-UP',speed:310,ai:175,error:95,width:165,goal:3,angle:.28},
 {name:'THE STEADY HAND',speed:335,ai:215,error:75,width:165,goal:5,angle:.35},
 {name:'THE ANGLE ARTIST',speed:350,ai:230,error:65,width:165,goal:5,angle:.65},
 {name:'THE COUNTERPUNCHER',speed:385,ai:275,error:48,width:165,goal:5,angle:.72},
 {name:'THE CLUB CHAMPION',speed:530,ai:395,error:18,width:125,goal:5,angle:.85}
];
const params=new URLSearchParams(location.search), testing=params.has('test');
const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;let level=Math.max(1,Math.min(5,Number(params.get('court'))||1)),phase='instructions',resume='serve',score=0,points=0,against=0,player=500,opponent=500,velocity=0,target=null,ball={x:500,y:570,vx:0,vy:0},rally=0,elapsed=0,aim=500,aiClock=0,flash=0,muted=false,audio,seed=42,keys=new Set(),trail=[];
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;},p=()=>profiles[level-1];
function tone(f){if(muted||phase==='instructions')return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.13);}catch{}}
function clearInput(){keys.clear();target=null;velocity=0;}function hud(){ $('level').textContent=level+' / 5';$('points').textContent=points;$('against').textContent=against;$('score').textContent=score;$('opponent').textContent=String(level).padStart(2,'0')+' / '+p().name;$('serve').disabled=phase!=='serve';$('serve').textContent=phase==='play'?'RALLY IN PLAY':'SERVE BALL';$('pause').textContent=phase==='paused'?'Resume':'Pause';$('drag').setAttribute('aria-valuenow',Math.round(player));$('thumb').style.left=(player/10)+'%';}
function prepare(){clearInput();ball={x:player,y:563,vx:0,vy:0};rally=0;trail=[];phase='serve';$('callout').textContent='FIRST TO '+p().goal+' · YOUR SERVE';hud();draw();}
function match(n){document.getElementById("result").classList.remove("is-visible");level=n;points=against=0;opponent=player=500;elapsed=0;prepare();}
function reset(){score=0;$('result').classList.remove('is-visible');match(1);if($('instruction-modal').classList.contains('is-visible')){resume='serve';phase='instructions';}hud();draw();}
function serve(){if(phase!=='serve')return;phase='play';ball.x=player;ball.vx=(rand()-.5)*120;ball.vy=-p().speed;aiClock=0;$('callout').textContent='';tone(540);hud();}
function point(won){if(phase!=='play')return;flash=.28;if(won){points++;score+=100+rally*15;tone(760);}else{against++;tone(170);}if(points>=p().goal||against>=p().goal){phase='result';$('result-title').textContent=won?(level===5?'Club champion!':'Court conquered!'):'Rematch?';$('result-text').textContent=points+' – '+against+' · '+score+' points. '+(won?'Wide placement wins rallies.':'Try striking off-center to pull the club paddle wide.');$('next').hidden=!won||level===5;$('result').classList.add('is-visible');$('again').textContent=won?'PLAY AGAIN':'RETRY COURT';(won&&level<5?$('next'):$('again')).focus();}else {prepare();document.getElementById("callout").textContent=(won?"YOUR POINT":"CLUB POINT")+" · SERVE WHEN READY";}hud();}
function help(){if(phase==='result')return;resume=phase==='instructions'?resume:phase;phase='instructions';clearInput();$('instruction-modal').classList.add('is-visible');$('instruction-close').textContent='LET’S PLAY';$('instruction-close').focus();}
function closeHelp(){try{sessionStorage.setItem('rally-club-instructions-v1','seen');}catch{}$('instruction-modal').classList.remove('is-visible');phase=resume;clearInput();hud();canvas.focus();}
function pause(){if(phase==='instructions'||phase==='result')return;if(phase==='paused')phase=resume;else{resume=phase;phase='paused';}clearInput();$('callout').textContent=phase==='paused'?'MATCH PAUSED':phase==='serve'?'YOUR SERVE':'';hud();}
function step(dt){if(phase!=='play'&&phase!=='serve')return;elapsed+=dt;flash=Math.max(0,flash-dt);const old=player;let dir=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);player=clamp(player+(target===null?dir*700*dt:clamp(target-player,-900*dt,900*dt)),45+p().width/2,955-p().width/2);velocity=(player-old)/dt;if(phase==='serve'){ball.x=player;return;}
 aiClock-=dt;if(aiClock<=0){aiClock=.18;let t=Math.max(0,(ball.y-83)/Math.max(1,-ball.vy));let predicted=ball.x+ball.vx*t;while(predicted<50||predicted>950)predicted=predicted<50?100-predicted:1900-predicted;aim=ball.vy<0?predicted+(rand()-.5)*p().error*2:500;}
 opponent=clamp(opponent+clamp(aim-opponent,-p().ai*dt,p().ai*dt),115,885);
 if(!reduced){trail.push({x:ball.x,y:ball.y});if(trail.length>10)trail.shift();}ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;
 if(ball.x<49){ball.x=49;ball.vx=Math.abs(ball.vx);tone(310);}if(ball.x>951){ball.x=951;ball.vx=-Math.abs(ball.vx);tone(310);}
 if(ball.vy>0&&ball.y>=562&&ball.y-ball.vy*dt<562&&Math.abs(ball.x-player)<p().width/2+9){ball.y=561;rally++;score+=5;let a=clamp((ball.x-player)/(p().width/2)*.98+velocity*.00032,-1.12,1.12);let speed=Math.min(p().speed+25*rally,p().speed*1.65);ball.vx=Math.sin(a)*speed;ball.vy=-Math.cos(a)*speed;tone(600);hud();}
 if(ball.vy<0&&ball.y<=88&&ball.y-ball.vy*dt>88&&Math.abs(ball.x-opponent)<79){ball.y=89;let a=level>=4?(player>500?-1:1)*(level===5?.65+rand()*.4:.4+rand()*.35):(rand()-.5)*2*p().angle;let speed=Math.min(p().speed+25*rally,p().speed*1.65);ball.vx=Math.sin(a)*speed;ball.vy=Math.cos(a)*speed;tone(440);}
 if(ball.y>645)point(false);else if(ball.y<5)point(true);
}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(x,y,w,h);}function text(s,x,y,size,c,align='center'){ctx.fillStyle=c;ctx.font=`bold ${size}px Arial`;ctx.textAlign=align;ctx.fillText(s,x,y);}
function draw(){rect(0,0,1000,650,'#d47856');for(let x=0;x<1000;x+=90)rect(x,0,2,650,'#c56b4c');rect(31,24,938,606,'#9a583e');rect(40,18,920,605,'#285b50');rect(48,26,904,589,'#377563');ctx.strokeStyle='#e9edcf';ctx.lineWidth=4;ctx.strokeRect(59,37,882,566);rect(498,39,3,562,'#bed5ba');rect(59,320,882,2,'#f2ecd4');for(let x=54;x<950;x+=13)rect(x,310,1,23,'#f2ecd4');rect(45,306,8,29,'#eee4c6');rect(948,306,8,29,'#eee4c6');text('RALLY / CLUB',500,226,50,'#61917c');text('1978   •   MEMBERS & GUESTS',500,259,13,'#a0b69a');text('CLUB',85,65,13,'#e5e7cc','left');text('YOU',85,595,13,'#e5e7cc','left');
 rect(opponent-70,66,140,17,'#163c35');rect(opponent-70,61,140,17,'#edb86f');rect(opponent-40,61,80,3,'#fff0bf');rect(player-p().width/2,574,p().width,18,'#183e35');rect(player-p().width/2,568,p().width,18,'#ec745c');rect(player-p().width/2+8,568,p().width-16,4,'#ffc2a3');rect(player-p().width*.26,574,2,9,'#ffd0ab');rect(player+p().width*.26,574,2,9,'#ffd0ab');
 if(!reduced){trail.forEach((v,i)=>{ctx.fillStyle='rgba(255,246,218,'+(i/35)+')';ctx.beginPath();ctx.arc(v.x,v.y,2+i*.35,0,Math.PI*2);ctx.fill();});}ctx.fillStyle='#173e3555';ctx.beginPath();ctx.ellipse(ball.x+5,ball.y+10,10,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff6da';ctx.beginPath();ctx.arc(ball.x,ball.y,9,0,Math.PI*2);ctx.fill();text(rally>1?rally+' SHOT RALLY':'',500,410,18,'#d5e1c3');if(flash>0){ctx.strokeStyle='#fff3c6';ctx.lineWidth=5;ctx.strokeRect(44,22,912,597);}}
$('instruction-close').onclick=closeHelp;$('help-button').onclick=help;$('pause').onclick=pause;$('reset').onclick=reset;$('serve').onclick=serve;$('sound').onclick=()=>{muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('sound').setAttribute('aria-pressed',String(muted));};$('next').onclick=()=>{$('result').classList.remove('is-visible');match(level+1);};$('again').onclick=()=>{const retry=against>=p().goal;$('result').classList.remove('is-visible');if(retry)match(level);else reset();};
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','a','d','r','m','p'].includes(e.key))e.preventDefault();if(e.repeat&&['r','m','p',' '].includes(e.key))return;keys.add(e.key);if(e.key===' ')serve();if(e.key==='r')reset();if(e.key==='m')$('sound').click();if(e.key==='p')pause();});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{clearInput();if(phase==='play')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(phase==='play')pause();}});window.addEventListener('vibecade:reset-input',clearInput);window.addEventListener('vibecade:restart',e=>{e.preventDefault();reset();});
let pointer=null;const drag=$('drag');function position(e){const r=drag.getBoundingClientRect();target=clamp((e.clientX-r.left)/r.width*1000,80,920);}drag.addEventListener('pointerdown',e=>{if(phase!=='play'&&phase!=='serve')return;e.preventDefault();pointer=e.pointerId;drag.setPointerCapture(pointer);position(e);});drag.addEventListener('pointermove',e=>{if(e.pointerId===pointer){e.preventDefault();position(e);}});for(const name of ['pointerup','pointercancel','lostpointercapture'])drag.addEventListener(name,()=>{pointer=null;target=null;});drag.addEventListener('contextmenu',e=>e.preventDefault());
match(level);resume='serve';phase='instructions';try{if(sessionStorage.getItem('rally-club-instructions-v1')){phase='serve';$('instruction-modal').classList.remove('is-visible');}}catch{}if(phase==='instructions')$('instruction-close').focus();hud();draw();let last=performance.now();function frame(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(phase==='play'||phase==='serve'){for(let t=0;t<dt;t+=.008)step(Math.min(.008,dt-t));draw();$('thumb').style.left=player/10+'%';}requestAnimationFrame(frame);}requestAnimationFrame(frame);
if(testing)window.rallyTest={state:()=>({level,phase,score,points,against,player,opponent,ball:{...ball},rally,elapsed,profiles,muted}),jump:n=>{match(n);},step:dt=>{for(let t=0;t<dt;t+=.008)step(Math.min(.008,dt-t));draw();},target:x=>{target=x;},serve,point,ball:b=>{Object.assign(ball,b);},draw};
})();






