const {chromium}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),out=process.env.SHOT_DIR||path.join(__dirname,'qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let f=path.resolve(root,'.'+new URL(req.url,'http://localhost').pathname);if(f!==root&&!f.startsWith(root+path.sep))return res.writeHead(403).end();try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',{'.html':'text/html','.js':'text/javascript','.css':'text/css'}[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true}),report={errors:[],curve:[],layouts:[]};try{const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.goto(base+'/rally-club/?test');const state=()=>page.evaluate(()=>rallyTest.state());await page.waitForTimeout(200);assert.equal((await state()).elapsed,0);await page.locator('#instruction-close').click();await page.keyboard.down('ArrowRight');await page.waitForTimeout(150);await page.keyboard.up('ArrowRight');assert.ok((await state()).player>550);await page.keyboard.press(' ');assert.equal((await state()).phase,'play');await page.locator('#help-button').click();const frozen=(await state()).elapsed;await page.waitForTimeout(150);assert.equal((await state()).elapsed,frozen);await page.locator('#instruction-close').click();await page.keyboard.press('p');assert.equal((await state()).phase,'paused');await page.keyboard.press('r');assert.equal((await state()).level,1);await page.keyboard.press('m');assert.equal((await state()).muted,true);
await page.keyboard.down('q');assert.equal((await state()).brush,-1);await page.keyboard.up('q');assert.equal((await state()).brush,0);await page.keyboard.down('e');assert.equal((await state()).brush,1);await page.keyboard.up('e');
report.spin=await page.evaluate(()=>{
 const cases=[];
 for(const brush of [-1,0,1]){rallyTest.jump(4);rallyTest.serve();rallyTest.brush(brush);rallyTest.ball({x:500,y:558,vx:0,vy:385,spin:.8});rallyTest.step(.02);const after=rallyTest.state();for(let t=0;t<2&&rallyTest.state().phase==='play'&&rallyTest.state().ball.vy<0;t+=.008)rallyTest.step(.008);cases.push({brush,residual:after.ball.spin,vx:after.ball.vx,score:after.score,result:rallyTest.state().against,phase:rallyTest.state().phase});}
 rallyTest.jump(3);rallyTest.serve();rallyTest.ball({x:940,y:300,vx:200,vy:-100,spin:0});rallyTest.step(.1);const out=rallyTest.state();
 if(out.against!==1||out.phase!=='serve')throw Error('Side out must penalize striker, not bounce');
 rallyTest.jump(3);rallyTest.serve();rallyTest.ball({x:500,y:300,vx:0,vy:-100,spin:.8});rallyTest.step(.4);const curve=rallyTest.state().ball;
 if(Math.abs(curve.x-516)>1||Math.abs(curve.vx-80)>1)throw Error('Spin must curve continuously');
 rallyTest.jump(3);rallyTest.serve();rallyTest.ball({x:500,y:89,vx:0,vy:-310,spin:0});rallyTest.step(.02);if(rallyTest.state().lastHitter!=='club')throw Error('Club must return before fault test');rallyTest.ball({x:940,y:200,vx:200,vy:100,spin:0});rallyTest.step(.1);if(rallyTest.state().points!==1)throw Error('Club side-out must award player');
 rallyTest.jump(4);rallyTest.serve();rallyTest.brush(1);rallyTest.ball({x:500,y:558,vx:0,vy:385,spin:-.8});rallyTest.step(.02);if(rallyTest.state().ball.spin!==0)throw Error('Left-spin cancellation failed');
 return {cases,curve};});
assert.equal(report.spin.cases[0].residual,0);assert.equal(report.spin.cases[0].score,30);assert.equal(report.spin.cases[1].residual,.8);assert.equal(report.spin.cases[2].residual,1.6);assert.equal(report.spin.cases[2].result,1);
report.curve=await page.evaluate(()=>{let result=[];for(let n=1;n<=5;n++){rallyTest.jump(n);if(n===4){rallyTest.serve();rallyTest.point(false);rallyTest.serve();rallyTest.point(false);}let seconds=0;for(let i=0;i<30000;i++){let s=rallyTest.state();if(s.phase==='result')break;if(s.phase==='serve')rallyTest.serve();s=rallyTest.state();let b=s.ball,t=Math.max(0,(562-b.y)/Math.max(1,b.vy)),x=b.x+b.vx*t+.5*b.spin*250*t*t;rallyTest.brush(b.vy>0?-Math.sign(b.spin):0);let offset=(s.opponent<500?-1:1)*s.profiles[n-1].width*.43;rallyTest.target(b.vy>0?x+offset:500);rallyTest.step(.016);seconds+=.016;}const s=rallyTest.state();result.push({level:n,points:s.points,against:s.against,phase:s.phase,seconds:Math.round(seconds)});}return result;});
report.uncountered=await page.evaluate(()=>{const results=[];for(let n=1;n<=5;n++){rallyTest.jump(n);let clock=0;for(let i=0;i<35000;i++){let s=rallyTest.state();if(s.phase==='result')break;if(s.phase==='serve')rallyTest.serve();if(clock<=0){s=rallyTest.state();let b=s.ball,t=Math.max(0,(562-b.y)/Math.max(1,b.vy)),x=b.x+b.vx*t+.5*b.spin*250*t*t;rallyTest.brush(0);rallyTest.target(b.vy>0?x+(s.opponent<500?-1:1)*s.profiles[n-1].width*.43:500);clock=.016;}rallyTest.step(.016);clock-=.016;}let s=rallyTest.state();results.push({level:n,points:s.points,against:s.against});}return results;});console.log('Uncountered',report.uncountered);console.log(JSON.stringify(report.curve));for(const r of report.curve){assert.equal(r.phase,'result');assert.equal(r.points,r.level===1?3:5);}assert.equal(report.curve[3].points,5);assert.equal(report.curve[3].against,2);
await page.keyboard.press('r');await page.evaluate(()=>{rallyTest.jump(1);rallyTest.serve();rallyTest.ball({x:500,y:558,vx:0,vy:310});rallyTest.step(.04);if(rallyTest.state().ball.vy>=0)throw Error('Player return failed');rallyTest.ball({x:50,y:640,vx:0,vy:310});rallyTest.step(.04);if(rallyTest.state().against!==1)throw Error('Miss scoring failed');rallyTest.jump(4);rallyTest.serve();for(let i=0;i<1000;i++){let s=rallyTest.state();if(s.rally>=2&&s.ball.vy>0&&s.ball.y>390&&s.ball.y<430)break;let b=s.ball,t=Math.max(0,(562-b.y)/Math.max(1,b.vy)),x=b.x+b.vx*t+.5*b.spin*250*t*t;rallyTest.brush(b.vy>0?-Math.sign(b.spin):0);rallyTest.target(b.vy>0?x+(s.opponent<500?-70:70):500);rallyTest.step(.016);}rallyTest.draw();});await page.screenshot({path:path.join(out,'rally-club-spin-gameplay.png')});
await page.evaluate(()=>{rallyTest.jump(4);rallyTest.serve();for(let i=0;i<5;i++){rallyTest.point(true);if(i<4)rallyTest.serve();}});await page.locator('#next').click();assert.equal((await state()).level,5);await page.evaluate(()=>{rallyTest.serve();for(let i=0;i<5;i++){rallyTest.point(false);if(i<4)rallyTest.serve();}});await page.locator('#again').click();assert.equal((await state()).level,5);assert.equal((await state()).points,0);
for(const [width,height] of [[667,375],[740,390],[844,390],[390,844]]){const context=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true});const mobile=await context.newPage();mobile.on('pageerror',e=>report.errors.push(e.message));await mobile.addInitScript(()=>{Element.prototype.requestFullscreen=()=>Promise.reject(new Error('test refusal'));});await mobile.goto(base+'/rally-club/?test');await mobile.locator('#instruction-close').click();await mobile.waitForTimeout(400);const r=await mobile.locator('#drag').boundingBox();const cdp=await context.newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:r.x+r.width*.8,y:r.y+20}]});await mobile.waitForTimeout(200);await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:r.x+r.width*.2,y:r.y+20}]});await mobile.waitForTimeout(700);assert.ok((await mobile.evaluate(()=>rallyTest.state())).player<450);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.locator('#spin-left').tap();assert.equal((await mobile.evaluate(()=>rallyTest.state())).brush,-1);await mobile.locator('#spin-right').tap();assert.equal((await mobile.evaluate(()=>rallyTest.state())).brush,1);await mobile.locator('#spin-flat').tap();assert.equal((await mobile.evaluate(()=>rallyTest.state())).brush,0);await mobile.locator('#serve').click();assert.equal((await mobile.evaluate(()=>rallyTest.state())).phase,'play');await mobile.locator('.vibecade-mobile-restart').click();assert.equal((await mobile.evaluate(()=>rallyTest.state())).phase,'serve');const canvas=await mobile.locator('canvas').boundingBox(),drag=await mobile.locator('#drag').boundingBox();assert.ok(canvas.y+canvas.height<=drag.y+1);const spin=await mobile.locator('#spin-controls').boundingBox();assert.ok(spin.x+spin.width<=canvas.x+1||spin.y>=canvas.y+canvas.height-1);assert.ok(spin.y+spin.height<=height);assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));report.layouts.push({width,height,canvas,drag});await mobile.screenshot({path:path.join(out,`mobile-${width}.png`)});await mobile.reload();await mobile.locator('.vibecade-mobile-play').click();await mobile.waitForTimeout(400);assert.equal((await mobile.evaluate(()=>rallyTest.state())).phase,'serve');await context.close();}
await page.keyboard.press('r');assert.equal((await state()).score,0);const frames=await page.evaluate(()=>new Promise(resolve=>{let a=[],last=performance.now();function f(t){a.push(t-last);last=t;if(a.length<100)requestAnimationFrame(f);else resolve(a.slice(1).sort((x,y)=>x-y));}requestAnimationFrame(f);}));report.frameP95=frames[Math.floor(frames.length*.95)];assert.equal(report.errors.length,0);page.removeAllListeners('console');await page.route('https://fonts.googleapis.com/**',route=>route.abort());await page.goto(base+'/',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('a.card[href="rally-club/"]').count(),1);await page.locator('a.card[href="rally-club/"]').click();assert.match(await page.title(),/Rally Club/);assert.equal(report.errors.length,0);fs.writeFileSync(path.join(out,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;server.close();});
