const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),errors=[],checks=[];try{
 const p=await browser.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4173/iron-meridian/?test');
 const state=()=>p.evaluate(()=>__iron.snapshot()),step=n=>p.evaluate(n=>__iron.step(n),n),start=()=>p.evaluate(()=>{__iron.manual(true);__iron.grant(5);__iron.start(0);__iron.step(6);}),shots=()=>p.evaluate(()=>__iron.bullets().filter(b=>b.owner==='player'));
 await start();await p.keyboard.down('ArrowUp');await step(8);assert.equal((await state()).player.y,400);assert((await state()).player.aim);await p.keyboard.press('x');await p.keyboard.up('ArrowUp');await step(1);let b=(await shots())[0];assert.equal(b.vx,0);assert.equal(b.vy,-650);assert(b.h>b.w);checks.push('Up aims without jumping; a between-frame tap retains its release direction.');
 await start();await p.keyboard.down('w');await p.keyboard.down('Space');await step(8);assert((await state()).player.y<400);assert((await state()).player.aim);await p.keyboard.press('x');await step(1);assert.equal((await shots())[0].vx,0);await p.keyboard.up('Space');await p.keyboard.up('w');checks.push('Space jumps while W aims and fires overhead in the air.');
 for(const key of ['ArrowLeft','ArrowRight']){await start();await p.keyboard.down('ArrowUp');await p.keyboard.down(key);await p.keyboard.press('x');await step(1);b=(await shots())[0];assert(b.vy<0);assert(Math.sign(b.vx)===(key==='ArrowLeft'?-1:1));assert(Math.abs(Math.hypot(b.vx,b.vy)-650)<.01);await p.keyboard.up(key);await p.keyboard.up('ArrowUp');}checks.push('Both diagonal directions preserve projectile speed.');
 await start();await p.evaluate(()=>__iron.setPlayer({dir:-1}));await p.keyboard.down('ArrowRight');await p.keyboard.press('x');await step(1);assert((await shots())[0].vx>0);await p.keyboard.up('ArrowRight');checks.push('Normal horizontal fire follows a turn made immediately before release.');
 for(let weapon=0;weapon<6;weapon++){await start();await p.keyboard.press(String(weapon+1));await p.keyboard.down('ArrowUp');await p.keyboard.down('x');await step(48);assert.equal((await shots()).length,0);await p.keyboard.up('x');await step(1);const a=await shots();assert.equal(a.length,weapon===3?3:1);assert(a.every(b=>b.charged&&b.vy<0));if(weapon===3)assert.deepEqual(a.map(b=>b.vx).sort((a,b)=>a-b),[-190,0,190]);else assert.equal(a[0].vx,0);await p.keyboard.up('ArrowUp');}checks.push('All six charged weapons fire upward; Thorn spreads across the aim direction.');
 await start();await p.evaluate(()=>{const p=__iron.snapshot().player,e=__iron.enemies().find(e=>e.type==='drone');for(const a of __iron.enemies())if(a!==e)a.dead=true;e.x=e.home=p.x+3;e.y=280;e.groundY=445;e.phase=0;e.stun=2;e.hp=4;e.armor=false;});await p.keyboard.down('ArrowUp');await p.keyboard.down('x');await step(42);await p.keyboard.up('x');await step(15);assert(await p.evaluate(()=>__iron.enemies().find(e=>e.type==='drone').dead));await p.keyboard.up('ArrowUp');checks.push('An actual upward charge destroys an overhead drone through normal projectile collision.');
 await start();await p.keyboard.down('ArrowUp');await p.keyboard.down('x');await step(45);await p.evaluate(()=>{__iron.setPlayer({inv:0});__iron.step(0);});await p.screenshot({path:path.join(__dirname,'aim-desktop.png')});await p.keyboard.up('x');await step(9);await p.screenshot({path:path.join(__dirname,'aim-shot.png')});await p.keyboard.up('ArrowUp');
 await start();await p.keyboard.down('ArrowUp');await p.keyboard.down('x');await step(42);await p.keyboard.press('Escape');assert.equal((await state()).player.aim,false);await p.locator('#instruction-close').click();await step(1);assert.equal((await shots()).length,0);await p.keyboard.up('x');await p.keyboard.up('ArrowUp');checks.push('Help clears aim and cancels a held charge safely.');
 for(const [width,height] of [[667,375],[740,390],[844,390],[390,844]]){
  const c=await browser.newContext({viewport:{width,height},hasTouch:true,isMobile:true});await c.addInitScript(()=>{Element.prototype.requestFullscreen=()=>Promise.reject(new Error('Test refusal'));});const m=await c.newPage();m.on('pageerror',e=>errors.push(e.message));await m.goto('http://127.0.0.1:4173/iron-meridian/?test');await m.locator('#instruction-close').click();await m.waitForTimeout(1700);await m.locator('.sector').first().click();await m.evaluate(()=>{__iron.manual(true);__iron.step(6);});
  const joy=m.locator('[data-joystick]'),j=await joy.boundingBox(),canvas=await m.locator('canvas').boundingBox(),actions=await m.locator('.control-cluster').boundingBox();if(width>height){assert(j.x+j.width<=canvas.x+1);assert(actions.x>=canvas.x+canvas.width-1);}else assert(actions.y>=canvas.y+canvas.height);assert(actions.y+actions.height<=height);
  const center={x:j.x+j.width/2,y:j.y+j.height/2};await m.mouse.move(center.x,center.y);await m.mouse.down();await m.mouse.move(center.x,center.y-45);await m.evaluate(()=>__iron.step(2));let s=await m.evaluate(()=>__iron.snapshot());assert(s.joyY<-.8);assert(s.player.aim);assert.equal(s.player.y,400);
  const fire=m.locator('[data-action="fire"]');await fire.dispatchEvent('pointerdown',{pointerId:9,pointerType:'touch',bubbles:true});await m.evaluate(()=>__iron.step(45));await fire.dispatchEvent('pointerup',{pointerId:9,pointerType:'touch',bubbles:true});await m.evaluate(()=>__iron.step(1));assert(await m.evaluate(()=>__iron.bullets().some(b=>b.owner==='player'&&b.charged&&b.vx===0&&b.vy<0)));
  await m.mouse.move(center.x+34,center.y-34);await m.evaluate(()=>__iron.step(1));s=await m.evaluate(()=>__iron.snapshot());assert(s.player.aimX>0&&s.player.aimY<0);await m.mouse.move(center.x,center.y+45);await m.evaluate(()=>__iron.step(3));assert((await m.evaluate(()=>__iron.snapshot())).player.crouch);await m.mouse.move(center.x,center.y);await m.evaluate(()=>__iron.step(1));assert.equal((await m.evaluate(()=>__iron.snapshot())).player.aim,false);await m.mouse.up();
  await joy.dispatchEvent('pointerdown',{pointerId:16,pointerType:'touch',clientX:center.x,clientY:center.y-45,bubbles:true});await joy.dispatchEvent('pointercancel',{pointerId:16,bubbles:true});assert.equal((await m.evaluate(()=>__iron.snapshot())).joyY,0);
  await m.locator('.vibecade-mobile-options').click();await m.locator('.vibecade-control-toggle').click();await m.locator('.vibecade-options-close').click();const up=m.locator('[data-direction="up"]'),right=m.locator('[data-direction="right"]');await up.dispatchEvent('pointerdown',{pointerId:17,pointerType:'touch',bubbles:true});await right.dispatchEvent('pointerdown',{pointerId:18,pointerType:'touch',bubbles:true});await m.evaluate(()=>__iron.step(1));s=await m.evaluate(()=>__iron.snapshot());assert(s.player.aimX>0&&s.player.aimY<0);await m.locator('.vibecade-direction-pad').dispatchEvent('pointerup',{pointerId:18,bubbles:true});await m.evaluate(()=>__iron.step(1));assert.equal((await m.evaluate(()=>__iron.snapshot())).player.aimX,0);
  await fire.dispatchEvent('pointerdown',{pointerId:19,pointerType:'touch',bubbles:true});await m.evaluate(()=>__iron.step(45));const priorShots=await m.evaluate(()=>__iron.bullets().filter(b=>b.owner==='player').length);await m.locator('.vibecade-mobile-options').click();s=await m.evaluate(()=>__iron.snapshot());assert.equal(s.held.fire,false);assert.equal(s.joyY,0);assert.equal(s.player.aim,false);await m.locator('.vibecade-options-close').click();await m.evaluate(()=>__iron.step(1));assert(await m.evaluate(()=>__iron.bullets().filter(b=>b.owner==='player').length)<=priorShots);await fire.dispatchEvent('pointercancel',{pointerId:19,bubbles:true});
  await up.dispatchEvent('pointerdown',{pointerId:20,pointerType:'touch',bubbles:true});await m.evaluate(()=>{__iron.step(2);__iron.setPlayer({inv:0});__iron.step(0);});await m.screenshot({path:path.join(__dirname,`aim-mobile-${width}.png`)});await m.evaluate(()=>dispatchEvent(new Event('blur')));assert.equal((await m.evaluate(()=>__iron.snapshot())).joyY,0);await c.close();checks.push(width+'px touch: upward charge, diagonal aim, down crouch, neutral/cancel, simultaneous direction buttons, Options cancellation, blur and clear control rails.');
 }
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'aim-check.json'),JSON.stringify({checks,errors},null,2));console.log(checks.join('\n'));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
