const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));try{await p.goto('http://127.0.0.1:4173/iron-meridian/?test');
 const result=await p.evaluate(()=>{__iron.manual(true);__iron.grant(4);const geometry=[];for(let id=0;id<5;id++){__iron.start(id);const w=__iron.world();geometry.push({stage:id+1,length:w.length,fields:w.encounters.length,midpoints:w.encounters.filter(z=>z.midpoint).length,caches:w.caches.length,safeTunnels:w.platforms.filter(a=>a.tunnel).every(a=>!w.hazards.some(h=>!h.pit&&h.x<a.x+a.w&&h.x+h.w>a.x)),bounds:w.platforms.every(a=>a.x>=0&&a.x+a.w<=w.length),safeCheckpoint:!w.hazards.some(a=>w.cp>=a.x-70&&w.cp<a.x+a.w+70),wallsClear:w.platforms.filter(a=>a.wall).every(a=>!w.hazards.some(h=>h.pit&&a.x+a.w>h.x-100&&a.x<h.x+h.w+100))});}
  __iron.start(1);let e=__iron.enemies().find(e=>e.armor);for(const a of __iron.enemies())if(a!==e)a.dead=true;e.type='turret';e.y=444-e.h;e.timer=999;e.exposed=0;e.hp=100;__iron.warp(e.x-90);__iron.setPlayer({inv:999,dir:1});function shoot(weapon,full){__iron.select(weapon);const before=e.hp;__iron.shoot(full);__iron.step(30,false);return before-e.hp;}
  const pellet=shoot(0,false),closedCharge=shoot(0,true);e.exposed=2;const ventCharge=shoot(0,true);e.exposed=0;const matched=shoot(1,true);
  __iron.start(2);for(const group of [0,2]){for(const a of __iron.enemies().filter(a=>a.group===group)){a.type='turret';a.y=444-a.h;a.timer=999;__iron.warp(a.x-90);__iron.setPlayer({inv:999,dir:1});__iron.select(2);for(let n=0;!a.dead&&n<12;n++){__iron.shoot(true);__iron.step(30,false);}}}
  const cleared=__iron.snapshot().encounters,world=__iron.world();__iron.warp(world.cp+15);__iron.setPlayer({hp:10,inv:999});__iron.step(1,false);const mid=__iron.snapshot();
  const cache=world.caches[0];__iron.warp(cache.x,cache.y);__iron.step(1,false);__iron.warp(world.arena+90);__iron.setPlayer({hp:7});__iron.select(2);__iron.shoot(true);const before=__iron.snapshot();__iron.step(1,false);const entry=__iron.snapshot();__iron.setPlayer({hp:1,inv:0});__iron.damage(99);const retry=__iron.snapshot();__iron.warp(world.cp+5);__iron.setPlayer({hp:8});__iron.step(1,false);const revisit=__iron.snapshot();
  // Charged Frost intercepts incoming projectiles in actual collision processing.
  __iron.start(4);__iron.warp(150);__iron.select(4);__iron.shoot(true);const ice=__iron.bullets().find(a=>a.owner==='player');__iron.bullets().push({x:ice.x+20,y:ice.y+4,w:12,h:12,vx:-100,vy:0,life:2,damage:3,owner:'enemy',color:'#ffd2a3'});__iron.step(2,false);const frostDeflect=!__iron.bullets().some(a=>a.owner==='enemy');
  __iron.start(4);const field=__iron.world().encounters[3],floor=__iron.world().platforms.find(a=>a.ground&&a.x<field.x&&a.x+a.w>field.x);floor.conveyor=80;__iron.warp(field.x-26);__iron.setPlayer({ground:true,inv:999});__iron.step(180,false);const beltBlocked=__iron.snapshot().player.x+26<=field.x+.01;
  const motion=[];for(let stage=1;stage<5;stage++){__iron.start(stage);__iron.warp(__iron.world().arena+90);__iron.step(1,false);__iron.setPlayer({inv:999});__iron.setBoss({seed:17,hp:__iron.snapshot().boss.max*.3,phase:'wait',timer:0});const patterns=new Set(),tells=new Set();let minX=Infinity,maxX=0,minY=Infinity,maxY=0,delta=0,last=__iron.snapshot().boss,chained=false;for(let n=0;n<5400;n++){__iron.step(1,false);const b=__iron.snapshot().boss;if(b.phase==='attack')patterns.add(b.pattern);if(b.phase==='tell')tells.add(b.attackName);minX=Math.min(minX,b.x);maxX=Math.max(maxX,b.x);minY=Math.min(minY,b.y);maxY=Math.max(maxY,b.y);delta=Math.max(delta,Math.hypot(last.x-b.x,last.y-b.y));chained=chained||b.chained;last=b;}motion.push({stage:stage+1,patterns:patterns.size,tells:tells.size,width:maxX-minX,height:maxY-minY,maxStep:delta,chained:!!chained});}
  return{geometry,motion,armor:{pellet,closedCharge,ventCharge,matched},cleared,mid:{hp:mid.player.hp,checkpoint:mid.checkpoint},entry:{hp:entry.player.hp,checkpoint:entry.checkpoint,energyDifference:entry.energy-before.energy},retry:{x:retry.player.x,hp:retry.player.hp,checkpoint:retry.checkpoint,fields:retry.encounters,cacheIds:retry.collectedCaches},revisitHP:revisit.player.hp,frostDeflect,beltBlocked};
 });assert(result.geometry.every(r=>r.length>=12000&&r.fields===4&&r.midpoints===1&&r.caches===2&&r.bounds&&r.safeTunnels&&r.safeCheckpoint&&r.wallsClear));assert(result.motion.every(r=>r.patterns===5&&r.tells===5&&r.width>600&&r.height>180&&r.maxStep<15));assert(result.motion[3].chained);assert(result.armor.pellet<.2);assert(result.armor.closedCharge<2);assert.equal(result.armor.ventCharge,7);assert.equal(result.armor.matched,12);assert(result.cleared.includes(0)&&result.cleared.includes(2));assert.equal(result.mid.hp,28);assert.equal(result.entry.hp,7);assert.equal(result.entry.checkpoint,result.mid.checkpoint);assert(result.entry.energyDifference<.1);assert.equal(result.retry.x,result.mid.checkpoint);assert(result.retry.fields.includes(2));assert(result.retry.cacheIds.includes('armor'));assert.equal(result.revisitHP,8);assert(result.frostDeflect);assert(result.beltBlocked);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'redesign-check.json'),JSON.stringify({...result,errors},null,2));console.log(JSON.stringify(result,null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
