const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const base='http://127.0.0.1:4173';
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'});const errors=[],report=[];const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
const state=()=>page.evaluate(()=>__iron.snapshot()),step=n=>page.evaluate(n=>__iron.step(n),n),start=i=>page.evaluate(i=>{__iron.manual(true);__iron.start(i);},i),warp=x=>page.evaluate(x=>__iron.warp(x),x);
try{
await page.goto(base+'/iron-meridian/?test');await page.waitForTimeout(300);const before=await state();await page.waitForTimeout(300);assert.equal((await state()).t,before.t);assert.equal((await state()).mode,'instructions');await page.locator('#instruction-close').click();assert.equal((await state()).mode,'map');assert.equal(await page.locator('.sector:disabled').count(),1);report.push('First-load instructions gate simulation; final sector gated by four cores.');
await page.locator('.sector').first().click();await page.evaluate(()=>__iron.manual(true));await step(6);const origin=(await state()).player.x;await page.keyboard.down('ArrowRight');await step(60);await page.keyboard.up('ArrowRight');assert((await state()).player.x>origin+200);await page.keyboard.down('Space');await step(10);assert((await state()).player.y<350);await page.keyboard.up('Space');await step(50);assert((await state()).player.ground);await page.keyboard.down('Shift');await step(9);await page.keyboard.up('Shift');assert((await state()).player.vx>600);await step(40);
await warp(90);await page.evaluate(()=>__iron.setPlayer({inv:999}));await page.keyboard.down('x');await step(48);assert.equal(await page.evaluate(()=>__iron.bullets().filter(b=>b.owner==='player').length),0);await page.keyboard.up('x');await step(1);assert(await page.evaluate(()=>__iron.bullets().some(b=>b.charged)));report.push('Keyboard movement, variable jump, dash, exclusive hold-to-charge and release blast verified.');
await page.locator('#help-button').click();const paused=(await state()).t;await step(60);assert.equal((await state()).t,paused);await page.locator('#instruction-close').click();assert.equal((await state()).mode,'play');await page.keyboard.press('m');assert.equal(await page.locator('#sound-button').innerText(),'SOUND OFF');await page.keyboard.press('m');report.push('Help pauses and resumes; keyboard sound toggle works.');
for(let i=0;i<5;i++){
 await start(i);await step(10);const world=await page.evaluate(()=>__iron.world());assert(world.platforms.length>=10);const wall=world.platforms.find(a=>a.wall);await page.evaluate(w=>__iron.warp(w.x-26,w.y+30),wall);await page.keyboard.down('ArrowRight');await step(3);assert.equal((await state()).player.wall,1);await page.keyboard.down('Space');await step(2);assert((await state()).player.vy<0);assert.equal((await state()).player.dir,-1);await page.keyboard.up('Space');await page.keyboard.up('ArrowRight');await page.evaluate(()=>__iron.clearEncounters());await warp(world.cp+15);await page.evaluate(()=>__iron.setPlayer({hp:10}));await step(1);assert.equal((await state()).player.hp,28);assert.equal((await state()).checkpoint,world.cp);
 // Each pit is traversable with jump / air dash; no core is required.
 for(const gap of world.hazards.filter(h=>h.pit)){await warp(gap.x-40);await page.evaluate(()=>__iron.setPlayer({inv:999}));await step(2);await page.keyboard.down('ArrowRight');await step(8);await page.keyboard.down('Space');await step(20);await page.keyboard.down('Shift');await step(12);await page.keyboard.up('Shift');await step(16);await page.keyboard.up('Space');await page.keyboard.up('ArrowRight');assert((await state()).player.x>gap.x+gap.w,`Stage ${i+1} gap ${gap.x} reachable`);assert((await state()).player.y<540);}
 await warp(world.arena+90);await step(1);assert((await state()).bossActive);assert.equal((await state()).player.hp,28);await page.evaluate(()=>__iron.setPlayer({inv:999}));const attacks=new Set();for(let n=0;n<800;n+=20){await step(20);attacks.add((await state()).boss.phase);}assert(attacks.has('tell')&&attacks.has('attack')&&attacks.has('recover'));assert((await state()).boss.x>=world.arena+34);
 await page.evaluate(()=>{__iron.setPlayer({inv:0});__iron.step(0);});await page.screenshot({path:path.join(__dirname,`sector-${i+1}.png`)});
 // Kill by real player-projectile collision, then verify transfer and persistence.
 await page.evaluate(()=>{const s=__iron.snapshot();__iron.warp(s.boss.x-100,400);__iron.setPlayer({dir:1,inv:999});__iron.setBoss({hp:1,inv:0,phase:'wait',timer:99,vx:0,y:344});__iron.select(0);__iron.shoot(true);});await step(20);assert.equal((await state()).mode,'clear');assert((await state()).cleared.includes(i));await page.waitForTimeout(1700);assert.equal((await state()).mode,'result');await page.locator('#result-button').click();assert.equal((await state()).mode,'map');report.push(`Sector ${i+1}: gaps, checkpoint, boss attack/recovery cycle, projectile defeat, reward, mission-control transition passed.`);
}
await start(4);await page.evaluate(()=>__iron.select(4));const energy=(await state()).energy;await page.evaluate(()=>__iron.shoot());assert((await state()).energy<energy);await step(90);assert((await state()).energy>energy-10);await page.keyboard.press('q');assert.equal((await state()).weapon,5);await page.keyboard.press('3');assert.equal((await state()).weapon,2);
await page.evaluate(()=>{__iron.setPlayer({hp:1,inv:0});__iron.damage(9);});assert.equal((await state()).lives,2);assert.equal((await state()).player.hp,28);for(let i=0;i<2;i++)await page.evaluate(()=>{__iron.setPlayer({hp:1,inv:0});__iron.damage(9);});assert.equal((await state()).mode,'result');await page.locator('#result-button').click();assert.equal((await state()).lives,3);assert.equal((await state()).mode,'play');await page.keyboard.press('r');assert.equal((await state()).checkpoint,90);assert.equal((await state()).stage,4);report.push('Energy consumption/regeneration, acquired weapon selection, three-attempt game over, unlimited continue and sector restart passed.');
await page.reload();assert.equal((await state()).cleared.length,5);report.push('All acquired cores persist across reload.');
// Capture live opening play after a real keyboard sequence.
await start(0);await page.keyboard.down('ArrowRight');await step(55);await page.keyboard.down('x');await step(12);await page.keyboard.down('Space');await step(13);await page.keyboard.up('ArrowRight');await page.keyboard.up('x');await page.keyboard.up('Space');await step(1);await page.screenshot({path:path.join(__dirname,'gameplay-desktop.png')});
await page.goto(base+'/');assert.equal(await page.locator('a[href="iron-meridian/"]').count(),1);await page.locator('a[href="iron-meridian/"]').click();assert(page.url().includes('/iron-meridian/'));report.push('Arcade registration resolves.');
for(const width of [667,740,844]){
 const mobile=await browser.newContext({viewport:{width,height:width===667?375:390},hasTouch:true,isMobile:true});await mobile.addInitScript(()=>{Element.prototype.requestFullscreen=()=>Promise.reject(new Error('Unavailable in test'));});const p=await mobile.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/iron-meridian/?test');assert.equal(await p.locator('#touch-controls').isVisible(),false);await p.locator('#instruction-close').click();await p.waitForTimeout(1700);await p.locator('.sector').first().click();await p.evaluate(()=>__iron.manual(true));await p.evaluate(()=>__iron.step(4));
 const c=await p.locator('canvas').boundingBox(),j=await p.locator('[data-joystick]').boundingBox(),actions=await p.locator('.control-cluster').boundingBox();assert(j.x+j.width<=c.x+1,`${width}: left rail clear`);assert(actions.x>=c.x+c.width-1,`${width}: right rail clear`);assert(actions.y+actions.height<= (width===667?375:390));
 await p.mouse.move(j.x+63,j.y+63);await p.mouse.down();await p.mouse.move(j.x+108,j.y+63);assert((await p.evaluate(()=>__iron.snapshot())).joy>.8);await p.evaluate(()=>__iron.step(30));assert((await p.evaluate(()=>__iron.snapshot())).player.x>170);await p.mouse.move(j.x+20,j.y+63);assert((await p.evaluate(()=>__iron.snapshot())).joy<-.8);await p.mouse.move(j.x+63,j.y+63);assert(Math.abs((await p.evaluate(()=>__iron.snapshot())).joy)<.05);await p.mouse.up();assert.equal((await p.evaluate(()=>__iron.snapshot())).joy,0);
 const jump=p.locator('[data-action="jump"]');await jump.dispatchEvent('pointerdown',{pointerId:5,pointerType:'touch',bubbles:true});await p.evaluate(()=>__iron.step(8));assert((await p.evaluate(()=>__iron.snapshot())).player.y<400);await jump.dispatchEvent('pointercancel',{pointerId:5,pointerType:'touch',bubbles:true});assert.equal((await p.evaluate(()=>__iron.snapshot())).held.jump,false);
 await p.locator('.vibecade-mobile-options').click();await p.locator('.vibecade-control-toggle').click();await p.locator('.vibecade-options-close').click();await p.locator('[data-direction="right"]').dispatchEvent('pointerdown',{pointerId:8,pointerType:'touch',bubbles:true});assert.equal((await p.evaluate(()=>__iron.snapshot())).joy,1);await p.locator('.vibecade-direction-pad').dispatchEvent('pointerup',{pointerId:8,bubbles:true});assert.equal((await p.evaluate(()=>__iron.snapshot())).joy,0);
 const fire=p.locator('[data-action="fire"]');await fire.dispatchEvent('pointerdown',{pointerId:9,pointerType:'touch',bubbles:true});await p.evaluate(()=>__iron.step(45));assert((await p.evaluate(()=>__iron.snapshot())).held.fire);await fire.dispatchEvent('lostpointercapture',{pointerId:9,bubbles:true});assert.equal((await p.evaluate(()=>__iron.snapshot())).held.fire,false);await p.evaluate(()=>__iron.step(1));
 await p.evaluate(()=>{__iron.warp(90);__iron.step(3);});const crouch=p.locator('[data-action="crouch"]');await crouch.dispatchEvent('pointerdown',{pointerId:12,pointerType:'touch',bubbles:true});await p.evaluate(()=>__iron.step(2));assert.equal((await p.evaluate(()=>__iron.snapshot())).player.h,26);await crouch.dispatchEvent('pointerup',{pointerId:12,bubbles:true});await p.evaluate(()=>__iron.step(1));assert.equal((await p.evaluate(()=>__iron.snapshot())).player.h,44);
 await fire.dispatchEvent('pointerdown',{pointerId:13,pointerType:'touch',bubbles:true});await p.evaluate(()=>__iron.step(48));assert.equal(await p.evaluate(()=>__iron.bullets().filter(b=>b.owner==='player').length),0);await fire.dispatchEvent('pointerup',{pointerId:13,bubbles:true});await p.evaluate(()=>__iron.step(1));assert.equal(await p.evaluate(()=>__iron.bullets().filter(b=>b.owner==='player'&&b.charged).length),1);
 const dash=p.locator('[data-action="dash"]');await dash.dispatchEvent('pointerdown',{pointerId:10,pointerType:'touch',bubbles:true});await p.evaluate(()=>__iron.step(3));assert((await p.evaluate(()=>__iron.snapshot())).player.dash>0);await dash.dispatchEvent('pointerup',{pointerId:10,bubbles:true});
 assert(await p.locator('#touch-controls').evaluate(el=>{const e=new MouseEvent('contextmenu',{cancelable:true,bubbles:true});el.dispatchEvent(e);return e.defaultPrevented;}));
 await p.locator('.vibecade-mobile-restart').click();assert.equal((await p.evaluate(()=>__iron.snapshot())).checkpoint,90);assert.equal((await p.evaluate(()=>__iron.snapshot())).lives,3);
 await p.screenshot({path:path.join(__dirname,`gameplay-mobile-${width}.png`)});report.push(`${width}px touch: fullscreen refusal, clear rails, joystick hold/slide/neutral/release, jump/cancel, fire/lost capture, touch charge/release, crouch, dash, context-menu suppression, mobile restart and saved direction-button preference passed.`);
 await fire.dispatchEvent('pointerdown',{pointerId:11,pointerType:'touch',bubbles:true});await p.evaluate(()=>dispatchEvent(new Event('blur')));assert.equal((await p.evaluate(()=>__iron.snapshot())).held.fire,false);assert.equal(await fire.evaluate(b=>b.classList.contains('pressed')),false);assert.equal((await p.evaluate(()=>__iron.snapshot())).mode,'instructions');await mobile.close();
}
const portrait=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});await portrait.addInitScript(()=>{Element.prototype.requestFullscreen=()=>Promise.reject(new Error('Unavailable in test'));});const pp=await portrait.newPage();pp.on('pageerror',e=>errors.push(e.message));await pp.goto(base+'/iron-meridian/?test');await pp.locator('#instruction-close').click();await pp.waitForTimeout(1700);await pp.locator('.sector').first().click();const pc=await pp.locator('canvas').boundingBox(),pa=await pp.locator('.control-cluster').boundingBox();assert(pa.y>=pc.y+pc.height);assert(pa.y+pa.height<=824);await pp.locator('[data-action="map"]').dispatchEvent('pointerdown',{pointerId:4,pointerType:'touch',bubbles:true});await pp.locator('#map-sound-button').click();assert.equal(await pp.locator('#map-sound-button').innerText(),'SOUND OFF');await pp.locator('#resume-button').click();await pp.screenshot({path:path.join(__dirname,'gameplay-portrait.png')});await portrait.close();report.push('390×844 portrait: reachable instructions, controls below playfield, mission-control sound toggle and resume passed.');
assert.deepEqual(errors,[]);report.push('No browser page errors.');fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify({date:new Date().toISOString().slice(0,10),checks:report,errors},null,2));console.log(report.join('\n'));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
