(() => {
'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const COLS=24,ROWS=14,CELL=36,OX=48,OY=132;
const vaults=[{quota:6,interval:.24,growth:2,lives:4,time:95},{quota:8,interval:.22,growth:2,lives:4,time:105},{quota:10,interval:.20,growth:2,lives:4,time:115},{quota:12,interval:.18,growth:3,lives:4,time:125},{quota:16,interval:.115,growth:4,lives:2,time:115}];
const names=['The Foyer','Silk Gallery','Ruby Salon','Crown Treasury','The Midnight Vault'];
const pillars=[{x:7,y:4},{x:16,y:4},{x:7,y:9},{x:16,y:9}];
const dirs=[{x:0,y:-1},{x:1,y:0},{x:0,y:1},{x:-1,y:0}];
const params=new URLSearchParams(location.search),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let seed=Number(params.get('seed'))||15927;
const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
let level=1,score=0,gems=0,lives=4,time=95,charge=4,snake=[],gem=null,dir=1,queue=[],grow=0,phase='instructions',resumePhase='playing',elapsed=0,acc=0,slow=false,recovery=0,flash=0,effects=[],last=0,dirty=true,sound=true,audio=null;
const same=(a,b)=>a.x===b.x&&a.y===b.y;
function tone(freq,duration=.1){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.7,audio.currentTime+duration);g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch(_){}}
function clearInput(){queue=[];slow=false;$('slow').classList.remove('is-pressed');}
function announce(s){$('callout').textContent=s;}
function refresh(){const v=vaults[level-1];$('level').textContent=`${level} / 5`;$('gems').textContent=`${gems} / ${v.quota}`;$('lives').textContent=lives===1?'1 LAST':lives;$('time').textContent=Math.ceil(time);$('score').textContent=score.toLocaleString();$('brake-meter').value=charge;$('charge').textContent=`${charge.toFixed(1)}s`;$('time').classList.toggle('urgent',time<=15);$('lives').classList.toggle('urgent',lives===1);}
function placeGem(){const choices=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const p={x,y};if(!snake.some(a=>same(a,p))&&!pillars.some(a=>same(a,p))&&Math.abs(x-snake[0].x)+Math.abs(y-snake[0].y)>3)choices.push(p);}gem=choices[Math.floor(random()*choices.length)];}
function resetSnake(){snake=Array.from({length:6},(_,i)=>({x:5-i,y:7}));dir=1;grow=0;clearInput();acc=0;}
function startVault(n){level=n;const v=vaults[n-1];gems=0;lives=v.lives;time=v.time;charge=4;elapsed=0;gemAge=0;effects=[];flash=0;recovery=1.1;resetSnake();placeGem();phase='playing';$('result-modal').classList.remove('is-visible');document.body.classList.remove('gameover-open');$('pause').textContent='Pause';$('touch-pause').textContent='PAUSE';announce(`${names[n-1]} · collect ${v.quota} rubies`);refresh();dirty=true;}
function reset(){score=0;startVault(1);if($('instruction-modal').classList.contains('is-visible')){phase='instructions';resumePhase='playing';}else canvas.focus({preventScroll:true});}
function turn(d){if(phase!=='playing')return;const previous=queue.length?queue[queue.length-1]:dir;if(d===previous||d===(previous+2)%4||queue.length>=2)return;queue.push(d);}
function finish(won){phase='result';clearInput();$('result-modal').classList.add('is-visible');document.body.classList.add('gameover-open');const next=won&&level<5;$('result-title').textContent=next?'Vault unlocked':won?'The collection is yours':'The vault stays closed';$('result-text').textContent=won?`${gems} rubies collected. ${lives} lives preserved. Score ${score.toLocaleString()}. ${next?'Your lives and slow charge refill in the next vault.':'All five vaults mastered.'}`:`Vault ${level}: ${gems} / ${vaults[level-1].quota} rubies. ${lives===0?'Your last life was spent.':'Time ran out.'} Score ${score.toLocaleString()}. Leave a route around your tail and slow down before the turn.`;$('next').hidden=!next;(next?$('next'):$('restart')).focus();tone(won?880:130,.25);dirty=true;}
function crash(){lives--;flash=.6;tone(130,.2);if(lives<=0){finish(false);refresh();return;}resetSnake();recovery=1.6;charge=Math.max(charge,2);if(snake.some(a=>same(a,gem)))placeGem();announce(`Coil restored · ${lives} lives · gems kept · choose your route`);refresh();}
function tick(){if(queue.length)dir=queue.shift();const d=dirs[dir],head={x:snake[0].x+d.x,y:snake[0].y+d.y};const eating=same(head,gem),body=snake.slice(0,grow>0||eating?snake.length:snake.length-1);if(head.x<0||head.x>=COLS||head.y<0||head.y>=ROWS||pillars.some(a=>same(a,head))||body.some(a=>same(a,head))){crash();return;}snake.unshift(head);if(eating){gems++;score+=100+Math.max(0,Math.round(50-gemAge*2));gemAge=0;grow+=vaults[level-1].growth;charge=Math.min(4,charge+1);effects.push({x:OX+(head.x+.5)*CELL,y:OY+(head.y+.5)*CELL,life:.65});if(effects.length>8)effects.shift();tone(500+(gems%5)*70);announce(`${gems} / ${vaults[level-1].quota} rubies · +1 second slow`);if(gems>=vaults[level-1].quota){score+=lives*200+Math.ceil(time)*5;finish(true);refresh();return;}placeGem();}if(grow>0)grow--;else snake.pop();refresh();dirty=true;}
let gemAge=0;
function step(dt){if(phase!=='playing')return;if(document.body.classList.contains('touch-device')&&innerWidth<600&&innerHeight>innerWidth)return;elapsed+=dt;effects.forEach(e=>e.life-=dt);effects=effects.filter(e=>e.life>0);flash=Math.max(0,flash-dt);if(recovery>0){recovery=Math.max(0,recovery-dt);if(recovery===0)announce(`${names[level-1]} · ${gems} / ${vaults[level-1].quota} rubies · keep an exit open`);dirty=true;return;}time=Math.max(0,time-dt);gemAge+=dt;if(time<=0){finish(false);refresh();return;}const braking=slow&&charge>0;if(braking)charge=Math.max(0,charge-dt);acc+=dt;const interval=vaults[level-1].interval*(braking?2:1);let steps=0;while(acc>=interval&&phase==='playing'&&recovery<=0&&steps++<3){acc-=interval;tick();}refresh();dirty=true;}
function help(){if(phase==='result')return;resumePhase=phase==='instructions'?resumePhase:phase;phase='instructions';clearInput();$('instruction-modal').classList.add('is-visible');document.body.classList.add('instructions-open');$('instruction-close').textContent='RETURN TO THE VAULT';$('instruction-close').focus();dirty=true;}
function dismiss(){try{sessionStorage.setItem('velvet-coil-intro','1');}catch(_){}$('instruction-modal').classList.remove('is-visible');document.body.classList.remove('instructions-open');phase=resumePhase;last=performance.now();canvas.focus({preventScroll:true});dirty=true;}
function pause(){if(phase==='playing'){phase='paused';clearInput();}else if(phase==='paused'){phase='playing';last=performance.now();}else return;$('pause').textContent=phase==='paused'?'Resume':'Pause';$('touch-pause').textContent=phase==='paused'?'RESUME':'PAUSE';dirty=true;}
function toggleSound(){sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('touch-sound').textContent=sound?'SOUND ON':'SOUND OFF';for(const id of ['sound','touch-sound'])$(id).setAttribute('aria-pressed',String(!sound));}
function path(points,color,width=2){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));ctx.stroke();}
function text(s,x,y,size,color='#e3c586'){ctx.fillStyle=color;ctx.font=`${size}px Georgia`;ctx.textAlign='center';ctx.fillText(s,x,y);}
function diamond(x,y,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.closePath();ctx.fill();}
const backdrop=document.createElement('canvas');backdrop.width=960;backdrop.height=720;
function makeBackdrop(){ctx.fillStyle='#142237';ctx.fillRect(0,0,960,720);for(let i=0;i<8;i++){path([[14+i*7,105-i*9],[120+i*12,14],[840-i*12,14],[946-i*7,105-i*9]],'#89734b55');path([[14+i*7,615+i*9],[120+i*12,706],[840-i*12,706],[946-i*7,615+i*9]],'#89734b55');}ctx.strokeStyle='#c2a365';ctx.lineWidth=2;ctx.strokeRect(19,19,922,682);text('V E L V E T   C O I L',480,61,30);diamond(238,51,7,'#dfbd7b');diamond(722,51,7,'#dfbd7b');ctx.fillStyle='#1c3047';ctx.fillRect(OX-5,OY-5,COLS*CELL+10,ROWS*CELL+10);ctx.strokeStyle='#b89a63';ctx.strokeRect(OX-5,OY-5,COLS*CELL+10,ROWS*CELL+10);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){ctx.fillStyle=(x+y)%2?'#1a2b40':'#1c2e43';ctx.fillRect(OX+x*CELL,OY+y*CELL,CELL,CELL);ctx.fillStyle='#71809433';ctx.fillRect(OX+x*CELL,OY+y*CELL,1,1);}pillars.forEach(p=>{const x=OX+p.x*CELL,y=OY+p.y*CELL;ctx.fillStyle='#090f1c';ctx.fillRect(x+5,y+7,30,30);ctx.fillStyle='#8e744e';ctx.fillRect(x+1,y+1,34,34);ctx.fillStyle='#aa8650';ctx.fillRect(x+3,y+3,30,30);ctx.strokeStyle='#f3d799';ctx.strokeRect(x+6,y+6,24,24);diamond(x+18,y+18,8,'#e6ca8d');});backdrop.getContext('2d').drawImage(canvas,0,0);}
function draw(){ctx.drawImage(backdrop,0,0);if(gem){const x=OX+(gem.x+.5)*CELL,y=OY+(gem.y+.5)*CELL;diamond(x,y,18,'#f3d296');diamond(x,y,14,'#d75165');ctx.save();ctx.beginPath();ctx.moveTo(x,y-14);ctx.lineTo(x+14,y);ctx.lineTo(x,y+14);ctx.closePath();ctx.fillStyle='#8c2945';ctx.fill();ctx.restore();path([[x-9,y],[x,y-10],[x+6,y]],'#ffcab4',2);if(!reduced){const r=21+Math.sin(elapsed*3)*2;ctx.strokeStyle='#e3c58670';ctx.strokeRect(x-r,y-r,r*2,r*2);}}
// Fine gold links make the chain readable through every bend.
ctx.lineCap='round';for(let i=1;i<snake.length;i++){const a=snake[i-1],b=snake[i];path([[OX+(a.x+.5)*CELL,OY+(a.y+.5)*CELL],[OX+(b.x+.5)*CELL,OY+(b.y+.5)*CELL]],'#e9c985',12);}ctx.lineCap='butt';
for(let i=snake.length-1;i>=0;i--){const p=snake[i],x=OX+p.x*CELL,y=OY+p.y*CELL;ctx.fillStyle='#07122080';ctx.beginPath();ctx.roundRect(x+5,y+7,30,30,8);ctx.fill();ctx.fillStyle=i===0?'#fff1cd':i%3===0?'#e4ba72':'#c69155';ctx.beginPath();ctx.roundRect(x+3,y+3,30,30,i===0?10:8);ctx.fill();ctx.strokeStyle='#745337';ctx.lineWidth=2;ctx.stroke();if(i>0){ctx.strokeStyle='#f9dfab99';ctx.strokeRect(x+9,y+9,18,18);diamond(x+18,y+18,i%4===0?6:4,i%4===0?'#a83955':'#f5d99b');}else{const d=dirs[dir],px=-d.y,py=d.x;for(const side of [-1,1]){ctx.fillStyle='#142237';ctx.beginPath();ctx.arc(x+18+d.x*7+px*side*6,y+18+d.y*7+py*side*6,3,0,7);ctx.fill();}path([[x+18+d.x*14,y+18+d.y*14],[x+18+d.x*19,y+18+d.y*19]],'#d9576c',2);}}
if(phase==='playing'&&recovery<=0){const d=dirs[queue[0]??dir],h={x:snake[0].x+d.x,y:snake[0].y+d.y};const danger=h.x<0||h.x>=COLS||h.y<0||h.y>=ROWS||pillars.some(p=>same(p,h))||snake.slice(0,grow>0?snake.length:-1).some(p=>same(p,h));if(danger){const x=OX+(snake[0].x+.5)*CELL+d.x*17,y=OY+(snake[0].y+.5)*CELL+d.y*17;diamond(x,y,7,'#fb7c80');}}
effects.forEach(e=>{ctx.globalAlpha=Math.max(0,e.life/.65);const r=reduced?20:20+(1-e.life/.65)*22;diamond(e.x,e.y,r,'#f1d28c55');text('+ RUBY',e.x,e.y-24,16,'#fff1cd');ctx.globalAlpha=1;});if(slow&&charge>0){ctx.strokeStyle='#b6e4ed';ctx.lineWidth=3;ctx.strokeRect(OX-8,OY-8,COLS*CELL+16,ROWS*CELL+16);}if(flash>0){ctx.fillStyle=`rgba(227,108,99,${flash*.2})`;ctx.fillRect(OX,OY,COLS*CELL,ROWS*CELL);}if(recovery>0){text(`CHOOSE YOUR ROUTE · ${Math.ceil(recovery)}`,480,OY+CELL*5,22,'#fff1d3');}if(phase==='paused'){ctx.fillStyle='#101a2de8';ctx.fillRect(OX,OY,COLS*CELL,ROWS*CELL);text('THE VAULT CAN WAIT',480,350,30);text('Resume when you are ready',480,388,19,'#fff1d3');}dirty=false;}
function frame(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;step(dt);if(dirty)draw();requestAnimationFrame(frame);}
$('instruction-close').onclick=dismiss;$('help-button').onclick=help;$('reset').onclick=reset;$('restart').onclick=reset;$('next').onclick=()=>{startVault(level+1);canvas.focus({preventScroll:true});};$('pause').onclick=pause;$('touch-pause').onclick=pause;$('sound').onclick=toggleSound;$('touch-sound').onclick=toggleSound;
const keyDirs={arrowup:0,w:0,arrowright:1,d:1,arrowdown:2,s:2,arrowleft:3,a:3};
addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(e.target.closest?.('.modal.is-visible'))return;if(key in keyDirs){e.preventDefault();if(!e.repeat)turn(keyDirs[key]);}else if(key===' '){e.preventDefault();if(phase==='playing')slow=true;}else if(!e.repeat){if(key==='r'){e.preventDefault();reset();}if(key==='m')toggleSound();if(key==='?')help();if(key==='escape')pause();}});
addEventListener('keyup',e=>{if(e.key===' ')slow=false;});
const slowButton=$('slow');slowButton.addEventListener('pointerdown',e=>{e.preventDefault();if(phase==='playing'){slow=true;slowButton.classList.add('is-pressed');slowButton.setPointerCapture(e.pointerId);}});for(const event of ['pointerup','pointercancel','lostpointercapture'])slowButton.addEventListener(event,()=>{slow=false;slowButton.classList.remove('is-pressed');});
let swipe=null;canvas.addEventListener('pointerdown',e=>{e.preventDefault();canvas.focus({preventScroll:true});swipe={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!swipe)return;const x=e.clientX-swipe.x,y=e.clientY-swipe.y;if(Math.max(Math.abs(x),Math.abs(y))<16)return;turn(Math.abs(x)>Math.abs(y)?x>0?1:3:y>0?2:0);swipe={x:e.clientX,y:e.clientY};});for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>swipe=null);
function bindJoystick(){window.VibeCadeJoystick(document.querySelector('[data-joystick]'),{mode:'cardinal',onChange:(x,y)=>{if(x||y)turn(Math.abs(x)>Math.abs(y)?x>0?1:3:y>0?2:0);}});}if(window.VibeCadeJoystick)bindJoystick();else addEventListener('vibecade-controls-ready',bindJoystick,{once:true});
addEventListener('vibecade:restart',e=>{e.preventDefault();reset();});addEventListener('vibecade:reset-input',clearInput);addEventListener('blur',()=>{clearInput();swipe=null;if(phase==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(phase==='playing')pause();}});
for(const modal of document.querySelectorAll('.modal'))modal.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const buttons=[...modal.querySelectorAll('button')].filter(b=>!b.hidden);const first=buttons[0],end=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}});
makeBackdrop();startVault(1);let seen=false;try{seen=sessionStorage.getItem('velvet-coil-intro')==='1';}catch(_){}if(!seen){phase='instructions';$('instruction-close').focus();}else{$('instruction-modal').classList.remove('is-visible');document.body.classList.remove('instructions-open');}
if(params.has('test'))window.coilTest={state:()=>({level,score,gems,lives,time,charge,snake:snake.map(p=>({...p})),gem:{...gem},dir,queue:[...queue],grow,phase,recovery,slow,elapsed,vaults,pillars}),jump:n=>{startVault(n);gemAge=0;},step,turn,crash,draw,setTime:t=>time=t,setGem:p=>gem=p,setSnake:(a,d)=>{snake=a;dir=d;grow=0;queue=[];recovery=0;acc=0;},setGems:n=>gems=n};
requestAnimationFrame(frame);
})();
