(() => {
'use strict';
const $ = id => document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
const W=960,H=600,FLOOR=534,GRAVITY=480,RADII=[15,29,49],BOUNCE=[230,335,430];
const rooms=[
 {name:'Morning light',sizes:[2],speed:100,time:85,lives:4},
 {name:'Rose gallery',sizes:[2,1],speed:108,time:90,lives:4},
 {name:'Fern arcade',sizes:[2,2],speed:116,time:95,lives:4},
 {name:'Crystal hall',sizes:[2,2,1],speed:130,time:100,lives:4},
 {name:'The crown room',sizes:[2,2,2,2],speed:168,time:75,lives:2}
];
const colors=['#b8e6d5','#f3b6d0','#eaca8d'],keys=new Set();
const s={level:1,phase:'play',paused:true,started:false,x:480,joy:0,fire:false,score:0,lives:4,time:85,inv:0,shots:[],bubbles:[],sparks:[],cooldown:0,age:0,transition:0,muted:false,combo:0,lastPop:-10,pops:0};
let audio,previous=0,portrait=false,needsPaint=true;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function tone(f,d=.09){if(s.muted||!s.started||s.paused)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(f*.6,audio.currentTime+d);g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d);}catch{}}
function clearInput(){keys.clear();s.joy=0;s.fire=false;$('fire').classList.remove('is-pressed');dispatchEvent(new Event('vibecade:reset-input'));}
function bubble(size,x,y,dir){return {size,x,y,vx:dir*rooms[s.level-1].speed*(size===0?1.1:1),vy:-BOUNCE[size]*.55};}
function startRoom(level){needsPaint=true;s.level=level;s.phase='play';s.time=rooms[level-1].time;s.lives=rooms[level-1].lives;s.x=480;s.inv=2.5;s.shots=[];s.sparks=[];s.cooldown=0;s.combo=0;s.pops=0;s.transition=0;clearInput();s.bubbles=rooms[level-1].sizes.map((size,i,a)=>bubble(size,[170,790,310,650][i],160+i%2*70,i%2?-1:1));}
function restart(){startRoom(1);s.score=0;$('result-modal').classList.remove('is-visible');document.body.classList.remove('gameover-open');canvas.focus({preventScroll:true});}
function help(){if(s.phase==='over'||s.phase==='win')return;s.paused=true;clearInput();$('instruction-modal').classList.add('is-visible');document.body.classList.add('instructions-open');$('instruction-close').textContent=s.started?'BACK TO THE GLASSHOUSE':'OPEN THE GLASSHOUSE';$('instruction-close').focus();}
function launch(){s.started=true;s.paused=false;$('instruction-modal').classList.remove('is-visible');document.body.classList.remove('instructions-open');try{sessionStorage.setItem('prism-panic-instructions','seen');}catch{}canvas.focus({preventScroll:true});tone(620);}
function finish(win){s.phase=win?'win':'over';clearInput();$('result-title').textContent=win?'A flawless glasshouse.':'A little broken glass.';$('result-text').textContent=(win?'All five rooms restored. ':`Room ${s.level} · ${s.time<=0?'Time ran out.':'Your last heart shattered.'} `)+`Score ${s.score.toLocaleString()}. Fire ahead of each bounce and keep an escape route.`;$('result-modal').classList.add('is-visible');document.body.classList.add('gameover-open');$('restart').focus();}
function burst(x,y,color){for(let i=0;i<(reduced?3:10)&&s.sparks.length<90;i++){const a=i*2.4;s.sparks.push({x,y,vx:Math.cos(a)*100,vy:Math.sin(a)*100-60,t:.6,color});}}
function split(index){const b=s.bubbles[index];s.bubbles.splice(index,1);s.combo=s.age-s.lastPop<2.2?Math.min(5,s.combo+1):1;s.lastPop=s.age;s.score+=(3-b.size)*50*s.combo;s.pops++;burst(b.x,b.y,colors[b.size]);tone(420+(2-b.size)*200);if(b.size>0){for(const dir of [-1,1]){const child=bubble(b.size-1,Math.max(35,Math.min(925,b.x+dir*9)),b.y,dir);child.vy=-BOUNCE[b.size-1]*.8;s.bubbles.push(child);}}if(!s.bubbles.length){s.phase='clear';s.transition=2.2;s.score+=Math.ceil(s.time)*10+s.lives*100;clearInput();}}
function damage(){if(s.inv>0||s.phase!=='play')return;s.lives--;s.inv=3;s.combo=0;burst(s.x,FLOOR-24,'#fff1d4');tone(140,.25);s.bubbles.forEach(b=>{if(Math.abs(b.x-s.x)<130&&b.y>FLOOR-150){b.vy=-BOUNCE[b.size];b.vx=Math.sign(b.x-s.x||1)*Math.abs(b.vx);b.y=Math.min(b.y,FLOOR-110);}});if(s.lives<=0)finish(false);}
function fire(){if(s.paused||!s.started||s.phase!=='play'||s.cooldown>0||s.shots.length>=2)return;s.shots.push({x:s.x,y:FLOOR-36,life:1.1});s.cooldown=.24;tone(260,.06);}
function update(dt){if(s.paused||!s.started||document.hidden||portrait)return;if(s.phase==='clear'){s.transition-=dt;if(s.transition<=0){if(s.level===5)finish(true);else startRoom(s.level+1);}return;}if(s.phase!=='play')return;s.age+=dt;s.time=Math.max(0,s.time-dt);s.inv=Math.max(0,s.inv-dt);s.cooldown=Math.max(0,s.cooldown-dt);if(s.time===0){finish(false);return;}
const move=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);s.x=Math.max(37,Math.min(923,s.x+(move||s.joy)*280*dt));if(s.fire||keys.has(' '))fire();
for(const b of s.bubbles){b.vy+=GRAVITY*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;const r=RADII[b.size];if(b.x<26+r){b.x=26+r;b.vx=Math.abs(b.vx);}if(b.x>934-r){b.x=934-r;b.vx=-Math.abs(b.vx);}if(b.y>FLOOR-r){b.y=FLOOR-r;b.vy=-BOUNCE[b.size];}if(b.y<88+r){b.y=88+r;b.vy=Math.abs(b.vy);}const px=Math.max(s.x-10,Math.min(s.x+10,b.x)),py=Math.max(FLOOR-39,Math.min(FLOOR-3,b.y));if(Math.hypot(b.x-px,b.y-py)<r-3)damage();}
if(s.phase!=='play')return;
for(let j=s.shots.length-1;j>=0;j--){const h=s.shots[j];h.y=Math.max(88,h.y-850*dt);h.life-=dt;let hit=-1;for(let i=0;i<s.bubbles.length;i++){const b=s.bubbles[i],r=RADII[b.size];if(Math.abs(b.x-h.x)<r+2&&b.y+r>h.y&&b.y-r<FLOOR){hit=i;break;}}if(hit>=0){s.shots.splice(j,1);split(hit);}else if(h.life<=0)s.shots.splice(j,1);}
for(let i=s.sparks.length-1;i>=0;i--){const p=s.sparks[i];p.t-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=180*dt;if(p.t<=0)s.sparks.splice(i,1);}}
// The static leadwork is cached once; moving glass uses a few simple paths.
const scenery=document.createElement('canvas');scenery.width=W;scenery.height=H;const bg=scenery.getContext('2d');
function path(c,points,fill,stroke){c.beginPath();points.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.closePath();if(fill){c.fillStyle=fill;c.fill();}if(stroke){c.strokeStyle=stroke;c.stroke();}}
function background(){bg.fillStyle='#29263e';bg.fillRect(0,0,W,H);const palette=['#665174','#77718b','#8a6178','#5c7d7c','#a78285'];for(let n=0;n<5;n++){const x=44+n*180;bg.save();bg.beginPath();bg.moveTo(x,510);bg.lineTo(x,234);bg.bezierCurveTo(x,140,x+77,106,x+77,106);bg.bezierCurveTo(x+77,106,x+154,140,x+154,234);bg.lineTo(x+154,510);bg.closePath();bg.fillStyle='#bdac9a';bg.fill();bg.clip();for(let row=0;row<6;row++)for(let col=0;col<3;col++){let xx=x+col*54,yy=175+row*62;path(bg,[[xx,yy],[xx+54,yy+30],[xx,yy+62],[xx-54,yy+30]],palette[(row+col+n)%5],'#3e344e');}for(let petal=0;petal<8;petal++){const a=petal*Math.PI/4;path(bg,[[x+77,184],[x+77+Math.cos(a)*38,184+Math.sin(a)*38],[x+77+Math.cos(a+.4)*28,184+Math.sin(a+.4)*28]],palette[(petal+n)%5],'#6c546f');}bg.strokeStyle='#cfb88c';bg.lineWidth=5;bg.beginPath();bg.moveTo(x+77,108);bg.lineTo(x+77,510);bg.stroke();bg.restore();bg.strokeStyle='#b99c78';bg.lineWidth=4;bg.strokeRect(x-5,250,164,268);}
bg.fillStyle='#29283c';bg.fillRect(0,510,W,90);bg.fillStyle='#d4b88a';bg.fillRect(20,FLOOR,W-40,3);for(let i=0;i<16;i++)path(bg,[[i*80-110,600],[i*60,538],[i*60+1,538],[i*80-108,600]],'#575166');bg.strokeStyle='#514857';for(let y=555;y<600;y+=18){bg.beginPath();bg.moveTo(0,y);bg.lineTo(W,y);bg.stroke();}bg.fillStyle='#201e32';bg.fillRect(0,0,W,82);bg.fillStyle='#a7906c';bg.fillRect(25,80,910,2);
// Small potted topiary anchors either end of the conservatory.
for(const x of [30,930]){bg.fillStyle='#916b72';bg.fillRect(x-15,502,30,30);bg.fillStyle='#496a68';for(let i=0;i<3;i++){bg.beginPath();bg.ellipse(x+(i-1)*10,484-i%2*15,13,26,(i-1)*.3,0,Math.PI*2);bg.fill();}}}
background();
function text(str,x,y,size,color='#fff1d4',align='left'){ctx.font=`${size>=28?'bold ':''}${size}px ${size>=28?'Georgia':'system-ui'}`;ctx.fillStyle=color;ctx.textAlign=align;ctx.fillText(str,x,y);}
let hudValue='';function draw(){const nextHud=s.level+'|'+s.lives+'|'+Math.ceil(s.time);if(nextHud!==hudValue){hudValue=nextHud;$('mobile-room').textContent='ROOM '+s.level+' / 5';$('mobile-health').textContent='♥'.repeat(Math.max(0,s.lives))+' · '+Math.ceil(s.time)+'s';}ctx.drawImage(scenery,0,0);ctx.fillStyle='#201d342c';ctx.fillRect(26,84,908,446);text('PRISM PANIC',36,38,27,'#f1c5d5');text(`${s.level} / 5  ·  ${rooms[s.level-1].name.toUpperCase()}`,36,65,15,'#ddccad');text(String(s.score).padStart(6,'0'),485,42,30,'#fff1d4','center');text('SCORE',485,64,12,'#cdbb9b','center');text(`${Math.ceil(s.time)}s`,900,43,32,s.time<15?'#ffb3b3':'#fff1d4','right');text('♥'.repeat(Math.max(0,s.lives))+'♡'.repeat(Math.max(0,rooms[s.level-1].lives-s.lives)),737,43,29,'#f1b0ca','right');
for(const b of s.bubbles){const r=RADII[b.size];ctx.save();ctx.translate(b.x,b.y);ctx.globalAlpha=.15+.28*Math.max(0,1-(FLOOR-b.y)/350);ctx.fillStyle='#100e20';ctx.beginPath();ctx.ellipse(0,FLOOR-b.y+4,r*.8,5,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle=colors[b.size];ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill();ctx.lineWidth=2.5;ctx.strokeStyle='#fff4de';ctx.stroke();path(ctx,[[0,-r+4],[r-4,0],[0,r-4],[-r+4,0]],null,'#655573');ctx.globalAlpha=.35;path(ctx,[[0,-r+4],[r-4,0],[0,0]],'#fff');path(ctx,[[0,0],[0,r-4],[-r+4,0]],'#66547d');ctx.globalAlpha=.8;ctx.strokeStyle='white';ctx.lineWidth=3;ctx.beginPath();ctx.arc(-r*.15,-r*.12,r*.62,3.6,4.7);ctx.stroke();ctx.restore();}
for(const h of s.shots){ctx.strokeStyle='#fff2c3';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(h.x,FLOOR);ctx.lineTo(h.x,h.y);ctx.stroke();path(ctx,[[h.x,h.y-7],[h.x+7,h.y+8],[h.x-7,h.y+8]],'#fff2c3');}
ctx.save();ctx.translate(s.x,FLOOR);ctx.fillStyle='#14122288';ctx.beginPath();ctx.ellipse(0,2,23,5,0,0,Math.PI*2);ctx.fill();if(s.inv>0){ctx.strokeStyle='#e1f8ea';ctx.lineWidth=3;ctx.setLineDash([7,5]);ctx.beginPath();ctx.ellipse(0,-23,28,35,0,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}const stride=(keys.size||Math.abs(s.joy)>.02)&&!s.paused?Math.sin(s.age*18)*4:0;ctx.fillStyle='#d9b38b';ctx.fillRect(-13,-9,10,9+stride);ctx.fillRect(3,-9,10,9-stride);path(ctx,[[-15,-10],[-12,-33],[10,-33],[16,-10]],'#b9dfd0','#385454');ctx.fillStyle='#f2ccac';ctx.beginPath();ctx.arc(0,-42,10,0,Math.PI*2);ctx.fill();path(ctx,[[-13,-44],[-8,-55],[7,-55],[14,-43]],'#744d6c');ctx.fillStyle='#312a3c';ctx.fillRect(3,-44,3,3);ctx.fillStyle='#eac993';ctx.fillRect(11,-32,6,21);ctx.restore();
for(const p of s.sparks){ctx.globalAlpha=p.t/.6;path(ctx,[[p.x,p.y-4],[p.x+3,p.y],[p.x,p.y+4],[p.x-3,p.y]],p.color);}ctx.globalAlpha=1;
text(s.phase==='clear'?'ROOM RESTORED · HEARTS REFILL':s.inv>0?'SHIELD ACTIVE · FIND YOUR OPENING':`${s.bubbles.length} ORBS LEFT  ·  FIRE, STEP ASIDE, REPEAT`,480,574,17,'#ecddc2','center');if(s.combo>1&&s.age-s.lastPop<2.2)text(`×${s.combo} CHAIN`,900,117,20,'#fff2c3','right');if(s.phase==='clear'){ctx.fillStyle='#211d36dc';ctx.fillRect(180,220,600,132);text(s.level===5?'THE GLASSHOUSE IS SAFE':'BEAUTIFULLY CLEARED',480,274,32,'#f7dbb3','center');text(s.level===5?'A master glazier.':`Next: ${rooms[s.level].name} · fresh hearts`,480,313,20,'#c5e7db','center');}}
function frame(now){const dt=Math.min(.034,(now-previous)/1000||0);previous=now;if(needsPaint||(!s.paused&&s.started&&!portrait&&!document.hidden&&(s.phase==='play'||s.phase==='clear'))){update(dt);draw();needsPaint=false;}requestAnimationFrame(frame);}
function toggleSound(){s.muted=!s.muted;$('sound').textContent=s.muted?'SOUND OFF':'SOUND ON';$('sound').setAttribute('aria-pressed',String(s.muted));$('sound').setAttribute('aria-label',s.muted?'Enable sound':'Mute sound');if(!s.muted)tone(520);}
addEventListener('keydown',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','a','d',' ','r','m','?','Escape'].includes(k))e.preventDefault();if(k==='m'&&!e.repeat){toggleSound();return;}if(s.paused||!s.started)return;if(k==='r'&&!e.repeat){restart();return;}if((k==='?'||k==='Escape')&&!e.repeat){help();return;}if(s.phase!=='play')return;if(!keys.has(k)&&['ArrowLeft','a','ArrowRight','d'].includes(k))s.x=Math.max(37,Math.min(923,s.x+(k==='ArrowLeft'||k==='a'?-7:7)));keys.add(k);if(k===' ')fire();});
addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));addEventListener('blur',clearInput);document.addEventListener('visibilitychange',clearInput);
$('fire').addEventListener('pointerdown',e=>{e.preventDefault();if(s.paused)return;$('fire').setPointerCapture(e.pointerId);s.fire=true;$('fire').classList.add('is-pressed');fire();});for(const type of ['pointerup','pointercancel','lostpointercapture'])$('fire').addEventListener(type,()=>{s.fire=false;$('fire').classList.remove('is-pressed');});$('sound').addEventListener('click',toggleSound);$('help-button').addEventListener('click',help);$('instruction-close').addEventListener('click',launch);$('restart').addEventListener('click',restart);addEventListener('vibecade:restart',e=>{e.preventDefault();restart();});
function bindJoystick(){window.VibeCadeJoystick(document.querySelector('[data-joystick]'),{mode:'horizontal',profile:'precision',onChange:x=>{if(x&&!s.joy&&s.started&&!s.paused&&s.phase==='play')s.x=Math.max(37,Math.min(923,s.x+Math.sign(x)*7));s.joy=x;}});}if(window.VibeCadeJoystick)bindJoystick();else addEventListener('vibecade-controls-ready',bindJoystick,{once:true});
function resize(){portrait=innerWidth<600&&innerHeight>innerWidth;clearInput();}addEventListener('resize',resize);resize();startRoom(Math.max(1,Math.min(5,Number(new URLSearchParams(location.search).get('level'))||1)));
try{if(sessionStorage.getItem('prism-panic-instructions')){if(matchMedia('(max-width:900px), (pointer:coarse)').matches){$('instruction-modal').classList.remove('is-visible');document.body.classList.remove('instructions-open');}else launch();}}catch{}
// Bounded diagnostics allow repeatable collision, transition, and later-room verification.
if(new URLSearchParams(location.search).has('test'))window.PrismTest={snapshot:()=>JSON.parse(JSON.stringify(s)),configurations:rooms,jump:n=>{startRoom(Math.max(1,Math.min(5,n)));return rooms[s.level-1];},damage:()=>{s.inv=0;damage();},lastOrb:()=>{s.bubbles=[bubble(0,s.x,FLOOR-100,1)];s.bubbles[0].vx=0;s.bubbles[0].vy=0;},timeout:()=>{s.time=.01;},step:seconds=>{for(let t=0;t<seconds;t+=1/120)update(1/120);},setPlayer:x=>s.x=x};
requestAnimationFrame(frame);
})();



