(() => {
 'use strict';
 const $=id=>document.getElementById(id),A=window.SpireArt,N=A.N,canvas=$('game'),g=canvas.getContext('2d');
 const levels=[
  {count:12,cadence:1.05,speed:.115,shields:5,pulses:2,title:'First light',note:'Diamonds climb straight. Rotate, line up, hold FIRE.'},
  {count:17,cadence:.9,speed:.14,shields:5,pulses:2,title:'The turning gears',note:'Bow ties flash, then switch one spoke. Track their new lane.'},
  {count:22,cadence:.78,speed:.17,shields:5,pulses:2,title:'Needlework',note:'Shoot the ivory needle heads before their spines reach the rim.'},
  {count:27,cadence:.61,speed:.24,shields:5,pulses:2,title:'Plated machinery',note:'Teal hexagons take two hits. Hold your line for the second shot.'},
  {count:32,cadence:.5,speed:.3,shields:5,pulses:2,title:'The storm engine',note:'Gold wings warn before surging. Save PULSE for crowded spokes.'},
  {count:38,cadence:.4,speed:.36,shields:3,pulses:1,title:'Master instrument',note:'Faster approach, tighter arrivals. One pulse. Choose the next threat.'},
  {count:44,cadence:.35,speed:.38,shields:2,pulses:0,title:'The perfect silence',note:'No pulses. Two shields. Read every spoke and keep moving.'}
 ];
 const mod=n=>(n%N+N)%N,delta=(a,b)=>mod(a-b+N/2)-N/2;
 const s={level:1,mode:'instructions',time:0,lane:0,drawLane:0,score:0,baseScore:0,shields:5,pulses:2,enemies:[],shots:[],particles:[],spawned:0,kills:0,breaches:0,shieldTime:0,pulseTime:0,flash:0,chain:0,shotTimer:0,moveTimer:0,seed:1};
 const input={left:false,right:false,fire:false,touch:0,touchFire:false};let bg,manual=false,muted=false,audio,last=0,hudTime=0,returnMode='playing',dirty=true,feedback='',feedbackTime=0;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 function clearInput(){Object.keys(input).forEach(k=>input[k]=k==='touch'?0:false);s.moveTimer=0;$('fire').setAttribute('aria-pressed','false');window.dispatchEvent(new CustomEvent('vibecade:reset-input'));}
 // The shared reset event may also be emitted by the joystick; never redispatch it in its listener.
 function released(){input.left=input.right=input.fire=input.touchFire=false;input.touch=0;s.moveTimer=0;$('fire').setAttribute('aria-pressed','false');}
 function wake(){if(muted||s.mode!=='playing')return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch(_){}}
 function tone(freq,duration=.06){if(muted||!audio||audio.state!=='running'||s.mode!=='playing')return;const o=audio.createOscillator(),v=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);v.gain.setValueAtTime(.025,audio.currentTime);v.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(v);v.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
 function message(text,seconds=2.4){feedback=text;feedbackTime=seconds;dirty=true;}
 function startLevel(level,score=s.score){clearInput();Object.assign(s,{level,mode:'playing',time:0,lane:0,drawLane:0,score,baseScore:score,shields:levels[level-1].shields,pulses:levels[level-1].pulses,enemies:[],shots:[],particles:[],spawned:0,kills:0,breaches:0,shieldTime:1,pulseTime:0,flash:0,chain:0,shotTimer:0,moveTimer:0,seed:level*937});bg=A.background(level);$('result-modal').classList.remove('is-visible');$('instruction-modal').classList.remove('is-visible');$('pause').textContent='Pause';$('touch-pause').textContent='PAUSE';message(levels[level-1].note,5);dirty=true;hud();canvas.focus();}
 function rand(){s.seed=(Math.imul(s.seed,1664525)+1013904223)>>>0;return s.seed/4294967296;}
 function spawn(){const i=s.spawned++,types=['climb'];if(s.level>=2)types.push('flip');if(s.level>=3)types.push('needle');if(s.level>=4)types.push('armor');if(s.level>=5)types.push('surge');let type=types[i%types.length];if(i===0)type='climb';const lane=i===0?0:Math.floor(rand()*N);s.enemies.push({lane,p:.02,type,hp:type==='armor'?2:1,age:0,flipAt:1.4+rand()*.4,warning:0,dir:rand()<.5?-1:1,dead:false});}
 function burst(lane,p,color){const q=A.point(lane,p);for(let i=0;i<(reduced?3:9);i++){if(s.particles.length>=100)s.particles.shift();const a=i/9*Math.PI*2;s.particles.push({x:q.x,y:q.y,vx:Math.cos(a)*70,vy:Math.sin(a)*70,life:.4,color});}}
 function destroy(e,pulse=false){if(e.dead)return;e.dead=true;s.kills++;s.chain++;s.score+=(e.type==='armor'?180:e.type==='climb'?100:140)+Math.min(10,s.chain)*10;burst(e.lane,e.p,pulse?'#f8e9cc':'#efa878');tone(330+s.chain*14);}
 function damage(e){e.dead=true;s.breaches++;s.chain=0;if(s.shieldTime>0)return;s.shields--;s.shieldTime=s.level===7?.45:2;s.flash=.3;if(s.level<7)s.enemies.forEach(v=>{if(v.p>.76&&!v.dead){v.dead=true;s.breaches++;}});burst(e.lane,1,'#ed6965');tone(90,.2);message(`RIM BREACHED · ${s.shields} shield${s.shields===1?'':'s'} left · ${s.level===7?'brief':'2s'} protection`,2);if(s.shields<=0)finish(false);}
 function pulse(){if(s.mode!=='playing'||s.pulses<=0||s.pulseTime>0)return;const targets=s.enemies.filter(e=>e.p>.25&&!e.dead);if(!targets.length){message('PULSE reaches beyond the inner quarter. Wait for machines to approach.');return;}s.pulses--;s.pulseTime=3;s.flash=.45;targets.forEach(e=>destroy(e,true));tone(150,.18);message(`PULSE · ${targets.length} machines silenced`);}
 function fire(){if(s.mode!=='playing'||s.shotTimer>0)return;s.shotTimer=.17;s.shots.push({lane:s.lane,p:1,dead:false});tone(640,.035);}
 function rotate(dir){s.lane=mod(s.lane+dir);dirty=true;}
 function finish(win){if(s.mode!=='playing')return;s.mode=win?(s.level===7?'victory':'cleared'):'lost';clearInput();$('result-title').textContent=win?(s.level===7?'The Spire is silent.':`Depth ${s.level} secured.`):'The rim has fallen.';$('result-text').textContent=win?`${s.kills} machines silenced · ${s.breaches} breaches · ${s.shields} shields left. Score ${s.score.toLocaleString()}. ${s.level===7?'You mastered every depth.':levels[s.level].title+' awaits.'}`:`All shields broken in depth ${s.level}. ${s.kills}/${levels[s.level-1].count} machines silenced. Retry restores the score and supplies from this depth’s start.`;$('next').hidden=!win||s.level===7;$('retry').hidden=win;$('result-modal').classList.add('is-visible');dirty=true;hud();$(win&&s.level<7?'next':win?'again':'retry').focus();}
 function update(dt){if(s.mode!=='playing')return;if(document.body.classList.contains('touch-device')&&innerHeight>innerWidth&&!manual)return;s.time+=dt;s.shieldTime=Math.max(0,s.shieldTime-dt);s.pulseTime=Math.max(0,s.pulseTime-dt);s.flash=Math.max(0,s.flash-dt);s.shotTimer=Math.max(0,s.shotTimer-dt);feedbackTime=Math.max(0,feedbackTime-dt);
  const direction=input.touch||((input.right?1:0)-(input.left?1:0));if(direction){s.moveTimer-=dt;if(s.moveTimer<=0){rotate(Math.sign(direction));s.moveTimer+=.13/Math.max(.12,Math.abs(direction));}}else s.moveTimer=0;
  s.drawLane+=delta(s.lane,s.drawLane)*Math.min(1,dt*24);s.drawLane=mod(s.drawLane);if(input.fire||input.touchFire)fire();
  const cfg=levels[s.level-1];if(s.spawned<cfg.count&&s.time>=.65+s.spawned*cfg.cadence)spawn();
  for(const e of s.enemies){if(e.dead)continue;e.age+=dt;e.warning=0;let speed=cfg.speed;
   if(e.type==='flip'&&e.p>.3){e.flipAt-=dt;e.warning=e.flipAt<.32?1:0;if(e.flipAt<=0){e.lane=mod(e.lane+e.dir);e.flipAt=1.45;}}
   if(e.type==='needle')speed*=.85;
   if(e.type==='surge'){const phase=e.age%2.1;e.warning=phase>1.05&&phase<1.4?1:0;speed*=phase>=1.4?1.9:.8;}
   e.p+=speed*dt;if(e.p>=1)damage(e);if(s.mode!=='playing')return;
  }
  for(const shot of s.shots){shot.p-=dt*1.85;for(const e of s.enemies){if(e.dead||shot.dead||e.lane!==shot.lane)continue;if(shot.p<=e.p+.035&&shot.p>=e.p-.095){shot.dead=true;e.hp--;if(e.hp<=0)destroy(e);else{burst(e.lane,e.p,'#a1dcd3');message('PLATE CRACKED · one more hit',.7);}break;}}if(shot.p<0)shot.dead=true;}
  s.enemies=s.enemies.filter(e=>!e.dead);s.shots=s.shots.filter(e=>!e.dead);for(const p of s.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}s.particles=s.particles.filter(p=>p.life>0);
  if(s.spawned>=cfg.count&&!s.enemies.length)finish(true);dirty=true;hudTime-=dt;if(hudTime<=0){hud();hudTime=.1;}
 }
 function hud(){const cfg=levels[s.level-1];$('level').textContent=`${s.level} / 7`;$('score').textContent=s.score.toLocaleString();$('shields').textContent=s.shields;$('remaining').textContent=cfg.count-s.kills-s.breaches;$('pulses').textContent=s.pulses;$('pulse').disabled=s.mode!=='playing'||!s.pulses||s.pulseTime>0;$('pulse').textContent=s.pulseTime>0?`PULSE ${Math.ceil(s.pulseTime)}s`:`PULSE · ${s.pulses}`;$('message').textContent=feedbackTime>0?feedback:`${cfg.title.toUpperCase()} · ${s.chain?`CHAIN ×${Math.min(10,s.chain)} · `:''}${s.shieldTime>0?'RIM PROTECTED':'WATCH THE OUTER SPOKES'}`;}
 function draw(){if(!dirty)return;dirty=false;g.clearRect(0,0,960,720);g.drawImage(bg,0,0);const a=A.point(s.lane-.5,1),b=A.point(s.lane+.5,1),c=A.point(s.lane+.5,0),d=A.point(s.lane-.5,0);A.path(g,[[a.x,a.y],[b.x,b.y],[c.x,c.y],[d.x,d.y]],'#ffe8c219','#fbe0ad88',1);const line0=A.point(s.lane,0),line1=A.point(s.lane,1);g.beginPath();g.moveTo(line0.x,line0.y);g.lineTo(line1.x,line1.y);g.strokeStyle='#f7e5c282';g.lineWidth=2;g.stroke();
  for(const e of s.enemies)A.actor(g,e,s.time);for(const shot of s.shots){const p=A.point(shot.lane,shot.p),q=A.point(shot.lane,shot.p+.08);g.beginPath();g.moveTo(p.x,p.y);g.lineTo(q.x,q.y);g.strokeStyle='#fff8dc';g.lineWidth=4;g.stroke();}
  for(const p of s.particles){g.globalAlpha=p.life/.4;g.fillStyle=p.color;g.fillRect(p.x-2,p.y-2,4,4);}g.globalAlpha=1;
  const ship=A.point(s.drawLane,1.04);g.save();g.translate(ship.x,ship.y);g.rotate(ship.a+Math.PI/2);A.path(g,[[-22,12],[-12,-13],[0,-2],[12,-13],[22,12],[9,7],[0,16],[-9,7]],'#efc89b','#fff3d9',3);A.path(g,[[-8,6],[0,-1],[8,6],[0,11]],'#683644','#e99070',2);g.restore();if(s.shieldTime>0)A.circle(g,ship.x,ship.y,31,null,'#91bfc1',3);if(s.flash>0&&!reduced){A.circle(g,A.CX,A.CY,60+(1-s.flash/.45)*235,null,'#f0b994',s.flash*16);}
  if(s.mode==='paused'){g.fillStyle='#17101bd9';g.fillRect(0,0,960,720);g.fillStyle='#fff0d7';g.font='bold 34px Georgia';g.textAlign='center';g.fillText('INSTRUMENT PAUSED',480,375);g.font='18px Trebuchet MS';g.fillText('P / PAUSE to return to the rim',480,413);}
 }
 function help(){if($('instruction-modal').classList.contains('is-visible'))return;returnMode=s.mode;clearInput();s.mode='instructions';$('instruction-modal').classList.add('is-visible');$('instruction-close').textContent='RETURN TO THE RIM';$('instruction-close').focus();dirty=true;}
 function dismiss(){try{sessionStorage.setItem('copper-spire-instructions','seen');}catch(_){}$('instruction-modal').classList.remove('is-visible');s.mode=returnMode;clearInput();wake();canvas.focus();dirty=true;}
 function pause(){if(!['playing','paused'].includes(s.mode))return;s.mode=s.mode==='playing'?'paused':'playing';clearInput();$('pause').textContent=s.mode==='paused'?'Resume':'Pause';$('touch-pause').textContent=s.mode==='paused'?'RESUME':'PAUSE';dirty=true;}
 function restart(){const blocked=$('instruction-modal').classList.contains('is-visible');startLevel(1,0);if(blocked){s.mode='instructions';returnMode='playing';$('instruction-modal').classList.add('is-visible');}dirty=true;}
 function mute(){muted=!muted;$('sound').textContent=muted?'Sound off':'Sound on';$('touch-sound').textContent=muted?'MUTED':'SOUND';if(!muted)wake();}
 const gameKeys=['ArrowLeft','ArrowRight','KeyA','KeyD','Space','KeyX','KeyP','KeyR','KeyM','Escape'];
 document.addEventListener('keydown',e=>{if(!gameKeys.includes(e.code))return;const onButton=e.target instanceof HTMLButtonElement;if(e.code==='Space'&&onButton&&e.target.closest('.modal, #vibecade-options'))return;e.preventDefault();if(e.code==='KeyR'){if(!e.repeat)restart();return;}if(e.code==='KeyM'){if(!e.repeat)mute();return;}if(e.code==='KeyP'||e.code==='Escape'){if(!e.repeat)pause();return;}if(s.mode!=='playing')return;wake();if(['ArrowLeft','KeyA','ArrowRight','KeyD'].includes(e.code)){const right=['ArrowRight','KeyD'].includes(e.code);input[right?'right':'left']=true;if(!e.repeat){rotate(right?1:-1);s.moveTimer=.15;}}if(e.code==='Space'){input.fire=true;fire();}if(e.code==='KeyX'&&!e.repeat)pulse();});
 document.addEventListener('keyup',e=>{if(['ArrowLeft','KeyA'].includes(e.code))input.left=false;if(['ArrowRight','KeyD'].includes(e.code))input.right=false;if(e.code==='Space')input.fire=false;});
 $('instruction-close').onclick=dismiss;$('help-button').onclick=help;$('pause').onclick=$('touch-pause').onclick=pause;$('reset').onclick=$('again').onclick=restart;$('retry').onclick=()=>{startLevel(s.level,s.baseScore);wake();};$('next').onclick=()=>{startLevel(s.level+1);wake();};$('sound').onclick=$('touch-sound').onclick=mute;$('pulse').onclick=()=>{wake();pulse();};
 const fireButton=$('fire');let firePointer=null;fireButton.addEventListener('pointerdown',e=>{e.preventDefault();if(s.mode!=='playing')return;firePointer=e.pointerId;fireButton.setPointerCapture(e.pointerId);input.touchFire=true;fireButton.setAttribute('aria-pressed','true');wake();fire();});const stopFire=()=>{firePointer=null;input.touchFire=false;fireButton.setAttribute('aria-pressed','false');};for(const event of ['pointerup','pointercancel','lostpointercapture'])fireButton.addEventListener(event,stopFire);
 window.VibeCadeJoystick(document.querySelector('[data-joystick]'),{mode:'horizontal',profile:'precision',onChange:x=>{input.touch=s.mode==='playing'?x:0;if(input.touch)wake();}});
 window.addEventListener('vibecade:reset-input',released);window.addEventListener('vibecade:restart',e=>{e.preventDefault();restart();});window.addEventListener('blur',()=>{clearInput();if(s.mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(s.mode==='playing')pause();}});window.addEventListener('resize',()=>{dirty=true;draw();});
 // Keep native Space/Enter button activation inside dialogs; cycle focus within the active dialog.
 document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const modal=document.querySelector('.modal.is-visible');if(!modal)return;const buttons=[...modal.querySelectorAll('button:not([hidden])')];if(!buttons.length)return;if(e.shiftKey&&document.activeElement===buttons[0]){e.preventDefault();buttons.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===buttons.at(-1)){e.preventDefault();buttons[0].focus();}});
 const requested=Math.max(1,Math.min(7,Number(new URLSearchParams(location.search).get('depth'))||1));startLevel(requested,0);try{if(!sessionStorage.getItem('copper-spire-instructions')){s.mode='instructions';returnMode='playing';$('instruction-modal').classList.add('is-visible');$('instruction-close').focus();}}catch(_){s.mode='instructions';$('instruction-modal').classList.add('is-visible');}
 function frame(t){const dt=Math.min(.04,(t-last)/1000||0);last=t;if(!manual)update(dt);draw();requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);
 if(new URLSearchParams(location.search).has('test'))window.__spireTest={state:s,input,levels,step:dt=>{update(dt);hud();draw();},start:startLevel,pulse,fire,damage,rotate,finish,help,clearInput,manual:v=>{manual=v;},draw:()=>{dirty=true;draw();},muted:()=>muted};
})();
