(()=>{'use strict';
const $=id=>document.getElementById(id), canvas=$('game'),ctx=canvas.getContext('2d');
const W=960,H=600,FLOOR_Y=[125,218,311,404,497], SHAFTS=[108,852];
const profiles=[
  {files:2,guards:1,cameras:0,armor:0,time:110,hearts:5,speed:44,shot:3.9},
  {files:2,guards:2,cameras:0,armor:0,time:105,hearts:5,speed:50,shot:3.5},
  {files:3,guards:3,cameras:1,armor:0,time:100,hearts:5,speed:54,shot:3.3},
  {files:3,guards:4,cameras:1,armor:1,time:96,hearts:5,speed:58,shot:3.1},
  {files:4,guards:5,cameras:2,armor:2,time:92,hearts:5,speed:62,shot:2.9},
  {files:4,guards:6,cameras:2,armor:3,time:83,hearts:4,speed:70,shot:2.5},
  {files:5,guards:7,cameras:3,armor:4,time:76,hearts:3,speed:78,shot:2.15}
];
const fileLayouts=[[[520,1],[365,3]],[[650,1],[300,3]],[[610,1],[340,2],[615,3]],[[650,1],[305,2],[635,3]],[[620,0],[360,1],[645,2],[330,3]],[[640,0],[350,1],[640,2],[350,3]],[[600,0],[350,1],[625,2],[320,3],[565,4]]];
const state={mode:'intro',stage:1,score:0,time:0,hearts:5,player:{x:108,floor:0,face:1,inv:0,lift:0,fire:0},files:[],guards:[],cameras:[],bullets:[],hitLog:[],beam:0,flash:0,shake:0,notice:'',noticeTime:0,muted:false};
let keys={left:false,right:false,up:false,down:false,fire:false},joy=[0,0],audio,last=performance.now(),helpWasPaused=false;
const test=location.search.includes('test=1');
function sound(freq,dur=.08,type='square',vol=.025){if(state.muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
function unlockSound(){try{audio ||=new(window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}}
function notice(message,duration=1.4){state.notice=message;state.noticeTime=duration;$('announcement').textContent=message}
function clearInput(){keys={left:false,right:false,up:false,down:false,fire:false};joy=[0,0]}
function beginStage(n){const p=profiles[n-1];state.stage=n;state.mode='playing';state.time=p.time;state.hearts=p.hearts;state.player={x:108,floor:0,face:1,inv:1.2,lift:0,fire:0};state.files=fileLayouts[n-1].map(([x,floor])=>({x,floor,taken:false}));state.guards=[];state.cameras=[];state.bullets=[];state.flash=0;state.shake=0;clearInput();
  state.hitLog=[];state.beam=0;for(let i=0;i<p.guards;i++){let floor=1+i%4,x=260+(i*207)%475;state.guards.push({x,floor,dir:i%2?1:-1,speed:p.speed+(i%3)*5,stun:0,hp:i<p.armor?2:1,armor:i<p.armor,shot:p.shot*(.75+(i%3)*.2)})}
  for(let i=0;i<p.cameras;i++)state.cameras.push({floor:1+(i*2)%4,x:410+i*140,phase:i*2.1});
  $('result-modal').classList.remove('is-visible');$('pause').textContent='Pause';notice(`SHIFT ${n} · FIND THE FILES`,1.9);hud();last=performance.now()}
function reset(){if(state.mode==='intro'||state.mode==='help')return;state.score=0;beginStage(1)}
function hud(){$('stage').textContent=`${state.stage} / 7`;$('files').textContent=`${state.files.filter(f=>f.taken).length} / ${state.files.length}`;$('time').textContent=Math.max(0,Math.ceil(state.time));$('hearts').textContent='♥'.repeat(state.hearts)||'0';$('score').textContent=state.score.toLocaleString()}
function end(win){state.mode=win?'clear':'over';clearInput();const final=win&&state.stage===7;$('result-title').textContent=final?'THE FILES ARE SAFE!':win?'SHIFT CLEARED':'MISSION FAILED';$('result-text').textContent=win?final?`Seven escapes complete · ${state.score.toLocaleString()} points`:`${state.files.length} files secured · ${Math.ceil(state.time)} seconds left`:'The tower caught you. Reset and plan another route.';$('next').hidden=!win||final;$('again').hidden=win&&!final;$('result-modal').classList.add('is-visible');sound(win?600:150,.25,'sawtooth',.035)}
function damage(source){const pl=state.player;if(pl.inv>0||state.mode!=='playing')return;state.hearts--;if(test)state.hitLog.push({source,time:+state.time.toFixed(1),floor:pl.floor,x:+pl.x.toFixed(1)});pl.inv=2.15;state.shake=.35;state.flash=.2;sound(120,.18,'sawtooth',.04);notice('HIT! KEEP MOVING',.7);hud();if(state.hearts<=0)end(false)}
function fire(){const pl=state.player;if(state.mode!=='playing'||pl.fire>0)return;pl.fire=.33;state.beam=.1;let hit=null,dist=220;for(const g of state.guards){const dx=g.x-pl.x;if(g.floor!==pl.floor||g.stun>0||Math.sign(dx)!==pl.face||Math.abs(dx)>dist)continue;dist=Math.abs(dx);hit=g}let blocked=false;for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i],dx=(b.x-pl.x)*pl.face;if(b.floor===pl.floor&&dx>0&&dx<125){state.bullets.splice(i,1);blocked=true;state.score+=15}}if(hit){hit.hp--;if(hit.hp<=0){hit.stun=5.5;hit.hp=hit.armor?2:1;state.score+=hit.armor?180:100;notice(hit.armor?'ARMORED GUARD DOWN':'GUARD STUNNED',.55)}else notice('ARMOR CRACKED',.55);sound(350,.08,'triangle',.04)}else if(blocked){notice('SHOT BLOCKED',.4);sound(510,.07,'triangle',.025)}else sound(190,.055,'square',.017);state.flash=.08;hud()}
function tick(dt){if(state.mode!=='playing')return;dt=Math.min(dt,.05);const p=profiles[state.stage-1],pl=state.player;state.time-=dt;if(state.time<=0){state.time=0;end(false);return}pl.inv=Math.max(0,pl.inv-dt);pl.lift=Math.max(0,pl.lift-dt);pl.fire=Math.max(0,pl.fire-dt);state.flash=Math.max(0,state.flash-dt);state.shake=Math.max(0,state.shake-dt);state.noticeTime=Math.max(0,state.noticeTime-dt);if(!state.noticeTime){state.notice='';$('announcement').textContent=''}
  state.beam=Math.max(0,state.beam-dt);const h=(Number(keys.right)-Number(keys.left))||joy[0],v=(Number(keys.down)-Number(keys.up))||joy[1],nearLift=SHAFTS.some(x=>Math.abs(pl.x-x)<27);pl.crouch=v>.3&&!nearLift&&Math.abs(h)<.3;if(Math.abs(h)>.3){pl.x=Math.max(26,Math.min(934,pl.x+h*196*dt));pl.face=Math.sign(h)}
  if(Math.abs(v)>.3&&pl.lift===0&&nearLift){const next=pl.floor+Math.sign(v);if(next>=0&&next<5){pl.floor=next;pl.lift=.52;pl.inv=Math.max(pl.inv,.32);sound(270,.09,'sine',.018)}}
  if(keys.fire)fire();
  for(const f of state.files)if(!f.taken&&f.floor===pl.floor&&Math.abs(f.x-pl.x)<23){f.taken=true;state.score+=250;state.flash=.14;notice('FILE SECURED',.7);sound(660,.11,'triangle',.035)}
  if(state.files.every(f=>f.taken)&&pl.floor===4&&pl.x>905){state.score+=Math.ceil(state.time)*10+state.hearts*150;hud();end(true);return}
  for(const g of state.guards){if(g.stun>0){g.stun=Math.max(0,g.stun-dt);continue}g.x+=g.dir*g.speed*dt;if(g.x<185||g.x>775){g.x=Math.max(185,Math.min(775,g.x));g.dir*=-1}g.shot-=dt;if(g.floor===pl.floor){const dx=pl.x-g.x;if(Math.abs(dx)<28)damage('guard');if(g.shot<=0&&Math.abs(dx)<380&&Math.abs(dx)>60){state.bullets.push({x:g.x,y:FLOOR_Y[g.floor]-20,floor:g.floor,vx:Math.sign(dx)*(215+state.stage*17)});g.shot=p.shot*(.8+(g.x%90)/150);sound(95,.04,'square',.008)}}else if(g.shot<.3)g.shot=.3}
  for(let i=state.bullets.length-1;i>=0;i--){const b=state.bullets[i];b.x+=b.vx*dt;if(b.x<35||b.x>925){state.bullets.splice(i,1);continue}if(b.floor===pl.floor&&Math.abs(b.x-pl.x)<14){state.bullets.splice(i,1);if(!pl.crouch)damage('bullet')}}
  for(const c of state.cameras){c.phase+=dt*(1.15+state.stage*.11);const beamX=c.x+Math.sin(c.phase)*85;if(c.floor===pl.floor&&Math.abs(pl.x-beamX)<18)damage('camera')}
  hud()}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}
function label(str,x,y,size=14,color='#e9dcbf',align='left'){ctx.fillStyle=color;ctx.font=`900 ${size}px Georgia,serif`;ctx.textAlign=align;ctx.fillText(str,x,y)}
function draw(){ctx.save();if(state.shake>0)ctx.translate(Math.sin(performance.now()*.1)*state.shake*7,0);rect(0,0,W,H,'#10282c');
  // Built as a night-time cutaway: warm offices against a cool exterior.
  rect(30,30,900,520,'#244045');rect(48,44,864,495,'#2f4b4d');
  for(let i=0;i<5;i++){const y=FLOOR_Y[i];rect(47,y+11,866,12,'#a7835e');rect(47,y+23,866,5,'#20373a');rect(48,y-69,864,79,i%2?'#314d4e':'#365354');for(let j=0;j<9;j++){let x=185+j*68;rect(x,y-57,43,50,(i+j)%3?'#465d57':'#53635a');rect(x+6,y-49,31,31,(i+j)%4?'#baaa80':'#7f987f');rect(x+13,y-46,17,29,'#d6c6a0')}label(`0${5-i}`,152,y-52,15,'#eedbb7')}
  for(const x of SHAFTS){rect(x-39,36,78,490,'#16383c');for(let i=0;i<5;i++){const y=FLOOR_Y[i];rect(x-31,y-62,62,73,'#34595b');rect(x-25,y-57,50,62,'#b99e73');rect(x-20,y-52,40,56,'#24494a');rect(x-2,y-52,4,56,'#d9ba78');rect(x-25,y+5,50,5,'#e2c48b');label('◆',x,y-66,12,'#f0ce80','center')}}
  for(const f of state.files)if(!f.taken){const y=FLOOR_Y[f.floor];rect(f.x-17,y-50,34,35,'#a44443');rect(f.x-12,y-45,24,26,'#e7d8bb');rect(f.x-8,y-40,16,3,'#a44443');rect(f.x-8,y-32,13,2,'#a44443');label('!',f.x,y-55,14,'#ffe4a7','center')}
  for(const c of state.cameras){const y=FLOOR_Y[c.floor],bx=c.x+Math.sin(c.phase)*85;ctx.fillStyle='#eac77528';ctx.beginPath();ctx.moveTo(c.x,y-68);ctx.lineTo(bx-20,y+5);ctx.lineTo(bx+20,y+5);ctx.fill();rect(c.x-13,y-70,26,11,'#e5b772');rect(bx-5,y+5,10,3,'#f4d78d')}
  for(const g of state.guards){const y=FLOOR_Y[g.floor];if(g.stun>0){label('✦',g.x,y-37,18,'#f4d584','center');rect(g.x-14,y-20,28,8,'#8a6258');continue}rect(g.x-12,y-39,24,30,g.armor?'#5b6f75':'#a8524e');rect(g.x-9,y-49,18,13,g.armor?'#839a9b':'#c27461');rect(g.x-14,y-13,9,15,'#273d3e');rect(g.x+5,y-13,9,15,'#273d3e');rect(g.x-13,y-29,26,5,'#edd0a0');if(g.armor)rect(g.x-16,y-33,32,12,'#91a5a0')}
  for(const b of state.bullets){rect(b.x-6,b.y-2,12,4,'#f6ca86')}
  const pl=state.player,py=FLOOR_Y[pl.floor];if(state.beam>0){rect(pl.face>0?pl.x+15:pl.x-235,py-32,220,4,'#f6deb0');rect(pl.face>0?pl.x+15:pl.x-235,py-31,220,2,'#fff8dc')}if(pl.inv<=0||Math.floor(pl.inv*9)%2===0){if(pl.crouch){rect(pl.x-14,py-22,28,15,'#b9d0b2');rect(pl.x-7,py-33,17,13,'#e4c39c');rect(pl.x-17,py-10,34,9,'#233b3c')}else{rect(pl.x-12,py-43,24,30,'#b9d0b2');rect(pl.x-9,py-53,18,14,'#e4c39c');rect(pl.x-13,py-14,9,16,'#233b3c');rect(pl.x+4,py-14,9,16,'#233b3c');rect(pl.x+pl.face*8,py-35,pl.face*17,5,'#d4e1c4');rect(pl.x-5,py-49,10,3,'#203c3d')}}
  rect(895,FLOOR_Y[4]-59,29,70,state.files.every(f=>f.taken)?'#6eb9a7':'#496b69');label('EXIT',907,FLOOR_Y[4]-64,13,state.files.every(f=>f.taken)?'#d4f4df':'#9aaeb0','center');
  rect(48,548,864,30,'#162d30');label(`LIFT HEIST  /  SHIFT ${state.stage}`,64,569,13,'#d9c596');label(state.files.every(f=>f.taken)?'ALL FILES FOUND — REACH THE GROUND EXIT':'FIND THE RED FILES · USE THE LIFTS',896,569,13,'#d9c596','right');if(state.flash>0)rect(0,0,W,H,`rgba(255,239,191,${state.flash*.35})`);ctx.restore()}
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;tick(dt);draw();requestAnimationFrame(frame)}
document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown',' '].includes(k))e.preventDefault();if(state.mode==='intro'||state.mode==='help')return;if(k==='arrowleft'||k==='a')keys.left=true;if(k==='arrowright'||k==='d')keys.right=true;if(k==='arrowup'||k==='w')keys.up=true;if(k==='arrowdown'||k==='s')keys.down=true;if(k===' ')keys.fire=true;if(k==='p')togglePause();if(k==='r')reset();if(k==='m')toggleSound()});
document.addEventListener('keyup',e=>{const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')keys.left=false;if(k==='arrowright'||k==='d')keys.right=false;if(k==='arrowup'||k==='w')keys.up=false;if(k==='arrowdown'||k==='s')keys.down=false;if(k===' ')keys.fire=false});
function togglePause(){if(state.mode==='playing'){state.mode='paused';clearInput();$('pause').textContent='Resume';notice('PAUSED',999)}else if(state.mode==='paused'){state.mode='playing';$('pause').textContent='Pause';notice('',0);last=performance.now()}}
function showHelp(){if(!['playing','paused'].includes(state.mode))return;helpWasPaused=state.mode==='paused';state.mode='help';clearInput();$('instruction-modal').classList.add('is-visible')}
function hideHelp(){if(state.mode==='intro'){sessionStorage.setItem('vibecade-lift-heist-instructions-v1','1');unlockSound();beginStage(1)}else if(state.mode==='help'){state.mode=helpWasPaused?'paused':'playing';if(helpWasPaused)notice('PAUSED',999);last=performance.now()}$('instruction-modal').classList.remove('is-visible');canvas.focus()}
function toggleSound(){state.muted=!state.muted;$('sound').textContent=state.muted?'Sound off':'Sound on';$('touch-sound').textContent=state.muted?'SOUND OFF':'SOUND';if(!state.muted)unlockSound()}
$('instruction-close').addEventListener('click',hideHelp);$('help-button').addEventListener('click',showHelp);$('pause').addEventListener('click',togglePause);$('reset').addEventListener('click',reset);$('sound').addEventListener('click',toggleSound);$('touch-sound').addEventListener('click',toggleSound);$('next').addEventListener('click',()=>beginStage(state.stage+1));$('again').addEventListener('click',()=>{state.score=0;beginStage(1)});
const fireButton=$('touch-fire');fireButton.addEventListener('pointerdown',e=>{e.preventDefault();try{fireButton.setPointerCapture(e.pointerId)}catch{}keys.fire=true;fireButton.classList.add('pressed');fire()});function releaseFire(){keys.fire=false;fireButton.classList.remove('pressed')}for(const type of ['pointerup','pointercancel','lostpointercapture'])fireButton.addEventListener(type,releaseFire);
window.addEventListener('vibecade:restart',e=>{e.preventDefault();reset()});window.addEventListener('vibecade:reset-input',clearInput);window.addEventListener('blur',()=>{clearInput();if(state.mode==='playing')togglePause()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='playing')togglePause()});
const bind=()=>window.VibeCadeJoystick?.(document.querySelector('[data-joystick]'),{mode:'cardinal',onChange:(x,y)=>joy=[x,y]});if(window.VibeCadeJoystick)bind();else window.addEventListener('vibecade-controls-ready',bind,{once:true});
if(sessionStorage.getItem('vibecade-lift-heist-instructions-v1')){$('instruction-modal').classList.remove('is-visible');beginStage(1)}else{state.mode='intro';state.files=fileLayouts[0].map(([x,floor])=>({x,floor,taken:false}));notice('',0);hud()}
if(test)window.__liftTest={state,profiles,tick,beginStage,fire,draw};requestAnimationFrame(frame);
})();
